// PHRASAL VERBS - 150 lessons
export const phrasalVerbLessons = [
  // Common Phrasal Verbs (50)
  { en: 'Please wake up early tomorrow.', hi: 'कृपया कल जल्दी उठना।', cat: 'Phrasal Verbs' },
  { en: 'I need to get up at 6 AM.', hi: 'मुझे सुबह 6 बजे उठना है।', cat: 'Phrasal Verbs' },
  { en: 'Can you pick me up from the station?', hi: 'क्या तुम मुझे स्टेशन से ले सकते हो?', cat: 'Phrasal Verbs' },
  { en: 'Please drop me off at the corner.', hi: 'कृपया मुझे कोने पर उतार दो।', cat: 'Phrasal Verbs' },
  { en: 'I will look after your children.', hi: 'मैं तुम्हारे बच्चों की देखभाल करूंगा।', cat: 'Phrasal Verbs' },
  { en: 'She takes after her mother.', hi: 'वह अपनी माँ पर गई है।', cat: 'Phrasal Verbs' },
  { en: 'Please turn on the lights.', hi: 'कृपया लाइट चालू करो।', cat: 'Phrasal Verbs' },
  { en: 'Turn off the TV before sleeping.', hi: 'सोने से पहले टीवी बंद करो।', cat: 'Phrasal Verbs' },
  { en: 'I am looking for my keys.', hi: 'मैं अपनी चाबियां ढूंढ रहा हूँ।', cat: 'Phrasal Verbs' },
  { en: 'Look out! There is a car coming.', hi: 'सावधान! गाड़ी आ रही है।', cat: 'Phrasal Verbs' },
  { en: 'Please fill out this form.', hi: 'कृपया यह फॉर्म भरें।', cat: 'Phrasal Verbs' },
  { en: 'I need to figure out the problem.', hi: 'मुझे समस्या समझनी है।', cat: 'Phrasal Verbs' },
  { en: 'The meeting was called off.', hi: 'मीटिंग रद्द कर दी गई।', cat: 'Phrasal Verbs' },
  { en: 'Please carry on with your work.', hi: 'कृपया अपना काम जारी रखें।', cat: 'Phrasal Verbs' },
  { en: 'I will catch up with you later.', hi: 'मैं बाद में तुमसे मिलूंगा।', cat: 'Phrasal Verbs' },
  { en: 'She broke down and cried.', hi: 'वह टूट गई और रो पड़ी।', cat: 'Phrasal Verbs' },
  { en: 'The car broke down on the highway.', hi: 'गाड़ी हाईवे पर खराब हो गई।', cat: 'Phrasal Verbs' },
  { en: 'They broke up last month.', hi: 'उनका पिछले महीने ब्रेकअप हो गया।', cat: 'Phrasal Verbs' },
  { en: 'Please calm down and listen.', hi: 'कृपया शांत हो जाओ और सुनो।', cat: 'Phrasal Verbs' },
  { en: 'I came across an old friend.', hi: 'मुझे एक पुराना दोस्त मिल गया।', cat: 'Phrasal Verbs' },
  { en: 'When did this problem come up?', hi: 'यह समस्या कब आई?', cat: 'Phrasal Verbs' },
  { en: 'Please come in and sit down.', hi: 'कृपया अंदर आइए और बैठिए।', cat: 'Phrasal Verbs' },
  { en: 'The truth will come out eventually.', hi: 'सच आखिरकार सामने आ जाएगा।', cat: 'Phrasal Verbs' },
  { en: 'I need to cut down on sugar.', hi: 'मुझे चीनी कम करनी होगी।', cat: 'Phrasal Verbs' },
  { en: 'Do not give up so easily.', hi: 'इतनी आसानी से हार मत मानो।', cat: 'Phrasal Verbs' },
  { en: 'Please give back my book.', hi: 'कृपया मेरी किताब वापस करो।', cat: 'Phrasal Verbs' },
  { en: 'I will get back to you soon.', hi: 'मैं जल्दी आपको जवाब दूंगा।', cat: 'Phrasal Verbs' },
  { en: 'We need to get along with everyone.', hi: 'हमें सबके साथ मिलकर रहना चाहिए।', cat: 'Phrasal Verbs' },
  { en: 'How do you get by on such low salary?', hi: 'इतनी कम तनख्वाह में कैसे गुजारा करते हो?', cat: 'Phrasal Verbs' },
  { en: 'I cannot get over this loss.', hi: 'मैं इस नुकसान से उबर नहीं पा रहा।', cat: 'Phrasal Verbs' },
  { en: 'Please go ahead with your plan.', hi: 'कृपया अपनी योजना के साथ आगे बढ़ें।', cat: 'Phrasal Verbs' },
  { en: 'The prices are going up.', hi: 'कीमतें बढ़ रही हैं।', cat: 'Phrasal Verbs' },
  { en: 'What is going on here?', hi: 'यहाँ क्या हो रहा है?', cat: 'Phrasal Verbs' },
  { en: 'I will go through the documents.', hi: 'मैं दस्तावेजों को देखूंगा।', cat: 'Phrasal Verbs' },
  { en: 'Please hang on for a moment.', hi: 'कृपया एक पल रुकें।', cat: 'Phrasal Verbs' },
  { en: 'I like to hang out with friends.', hi: 'मुझे दोस्तों के साथ घूमना पसंद है।', cat: 'Phrasal Verbs' },
  { en: 'Please hold on, I am coming.', hi: 'कृपया रुकें, मैं आ रहा हूँ।', cat: 'Phrasal Verbs' },
  { en: 'Keep up the good work.', hi: 'अच्छा काम जारी रखो।', cat: 'Phrasal Verbs' },
  { en: 'I cannot keep up with you.', hi: 'मैं तुम्हारे साथ नहीं चल पा रहा।', cat: 'Phrasal Verbs' },
  { en: 'Please let me know your decision.', hi: 'कृपया मुझे अपना फैसला बताएं।', cat: 'Phrasal Verbs' },
  { en: 'I am looking forward to meeting you.', hi: 'मुझे आपसे मिलने का इंतजार है।', cat: 'Phrasal Verbs' },
  { en: 'Look up the word in the dictionary.', hi: 'शब्दकोश में शब्द देखो।', cat: 'Phrasal Verbs' },
  { en: 'I look up to my father.', hi: 'मैं अपने पिता का सम्मान करता हूँ।', cat: 'Phrasal Verbs' },
  { en: 'Please make up your mind.', hi: 'कृपया अपना मन बना लो।', cat: 'Phrasal Verbs' },
  { en: 'They made up after the fight.', hi: 'लड़ाई के बाद उनकी सुलह हो गई।', cat: 'Phrasal Verbs' },
  { en: 'I need to move on with my life.', hi: 'मुझे अपनी जिंदगी में आगे बढ़ना है।', cat: 'Phrasal Verbs' },
  { en: 'Please pass on my message.', hi: 'कृपया मेरा संदेश पहुंचा दें।', cat: 'Phrasal Verbs' },
  { en: 'I will pay back the money.', hi: 'मैं पैसे वापस कर दूंगा।', cat: 'Phrasal Verbs' },
  { en: 'Please put away your toys.', hi: 'कृपया अपने खिलौने रख दो।', cat: 'Phrasal Verbs' },
  { en: 'Do not put off important work.', hi: 'जरूरी काम को टालो मत।', cat: 'Phrasal Verbs' },

  // More Phrasal Verbs (50)
  { en: 'Please put on your jacket.', hi: 'कृपया अपनी जैकेट पहनो।', cat: 'Phrasal Verbs' },
  { en: 'I cannot put up with this noise.', hi: 'मैं यह शोर बर्दाश्त नहीं कर सकता।', cat: 'Phrasal Verbs' },
  { en: 'Can you put me through to the manager?', hi: 'क्या आप मुझे मैनेजर से मिला सकते हैं?', cat: 'Phrasal Verbs' },
  { en: 'Please run through the presentation.', hi: 'कृपया प्रेजेंटेशन दोहरा दें।', cat: 'Phrasal Verbs' },
  { en: 'We have run out of milk.', hi: 'हमारा दूध खत्म हो गया।', cat: 'Phrasal Verbs' },
  { en: 'I ran into my old teacher.', hi: 'मैं अपने पुराने टीचर से मिल गया।', cat: 'Phrasal Verbs' },
  { en: 'Please set up the meeting room.', hi: 'कृपया मीटिंग रूम तैयार करें।', cat: 'Phrasal Verbs' },
  { en: 'We need to set off early.', hi: 'हमें जल्दी निकलना होगा।', cat: 'Phrasal Verbs' },
  { en: 'Please show up on time.', hi: 'कृपया समय पर आएं।', cat: 'Phrasal Verbs' },
  { en: 'I will sort out this problem.', hi: 'मैं यह समस्या सुलझा दूंगा।', cat: 'Phrasal Verbs' },
  { en: 'Please speak up, I cannot hear you.', hi: 'कृपया जोर से बोलो, मुझे सुनाई नहीं दे रहा।', cat: 'Phrasal Verbs' },
  { en: 'I need to stand up for myself.', hi: 'मुझे अपने लिए खड़ा होना होगा।', cat: 'Phrasal Verbs' },
  { en: 'Please take off your shoes.', hi: 'कृपया अपने जूते उतारो।', cat: 'Phrasal Verbs' },
  { en: 'The plane will take off soon.', hi: 'विमान जल्दी उड़ान भरेगा।', cat: 'Phrasal Verbs' },
  { en: 'I will take over the project.', hi: 'मैं प्रोजेक्ट संभाल लूंगा।', cat: 'Phrasal Verbs' },
  { en: 'Please take down the notes.', hi: 'कृपया नोट्स लिख लो।', cat: 'Phrasal Verbs' },
  { en: 'I need to think over your offer.', hi: 'मुझे आपके प्रस्ताव पर सोचना है।', cat: 'Phrasal Verbs' },
  { en: 'Please throw away the garbage.', hi: 'कृपया कचरा फेंक दो।', cat: 'Phrasal Verbs' },
  { en: 'I will try on this dress.', hi: 'मैं यह ड्रेस पहनकर देखूंगी।', cat: 'Phrasal Verbs' },
  { en: 'Please turn around slowly.', hi: 'कृपया धीरे से मुड़ो।', cat: 'Phrasal Verbs' },
  { en: 'Can you turn down the volume?', hi: 'क्या तुम आवाज कम कर सकते हो?', cat: 'Phrasal Verbs' },
  { en: 'I had to turn down the offer.', hi: 'मुझे प्रस्ताव ठुकराना पड़ा।', cat: 'Phrasal Verbs' },
  { en: 'Please turn up the heat.', hi: 'कृपया गर्मी बढ़ा दो।', cat: 'Phrasal Verbs' },
  { en: 'He turned up late as usual.', hi: 'वह हमेशा की तरह देर से आया।', cat: 'Phrasal Verbs' },
  { en: 'I need to work out regularly.', hi: 'मुझे नियमित व्यायाम करना है।', cat: 'Phrasal Verbs' },
  { en: 'Everything will work out fine.', hi: 'सब कुछ ठीक हो जाएगा।', cat: 'Phrasal Verbs' },
  { en: 'Please write down your address.', hi: 'कृपया अपना पता लिख दो।', cat: 'Phrasal Verbs' },
  { en: 'I need to wrap up this meeting.', hi: 'मुझे यह मीटिंग खत्म करनी है।', cat: 'Phrasal Verbs' },
  { en: 'Please zoom in on the picture.', hi: 'कृपया तस्वीर को बड़ा करो।', cat: 'Phrasal Verbs' },
  { en: 'Let us zoom out to see the full view.', hi: 'पूरा दृश्य देखने के लिए छोटा करें।', cat: 'Phrasal Verbs' },
  { en: 'I need to back up my files.', hi: 'मुझे अपनी फाइलों का बैकअप लेना है।', cat: 'Phrasal Verbs' },
  { en: 'Please back off, you are too close.', hi: 'कृपया पीछे हटो, तुम बहुत करीब हो।', cat: 'Phrasal Verbs' },
  { en: 'I will bring up this issue.', hi: 'मैं यह मुद्दा उठाऊंगा।', cat: 'Phrasal Verbs' },
  { en: 'She was brought up by her grandparents.', hi: 'उसका पालन-पोषण दादा-दादी ने किया।', cat: 'Phrasal Verbs' },
  { en: 'Please check in at the reception.', hi: 'कृपया रिसेप्शन पर चेक इन करें।', cat: 'Phrasal Verbs' },
  { en: 'I need to check out by noon.', hi: 'मुझे दोपहर तक चेक आउट करना है।', cat: 'Phrasal Verbs' },
  { en: 'Please check up on the patient.', hi: 'कृपया मरीज की जांच करें।', cat: 'Phrasal Verbs' },
  { en: 'I will clean up the room.', hi: 'मैं कमरा साफ कर दूंगा।', cat: 'Phrasal Verbs' },
  { en: 'Please close down the application.', hi: 'कृपया एप्लिकेशन बंद करें।', cat: 'Phrasal Verbs' },
  { en: 'The factory was closed down.', hi: 'फैक्ट्री बंद कर दी गई।', cat: 'Phrasal Verbs' },
  { en: 'I need to cool down after exercise.', hi: 'व्यायाम के बाद मुझे ठंडा होना है।', cat: 'Phrasal Verbs' },
  { en: 'Please count on me for help.', hi: 'मदद के लिए मुझ पर भरोसा रखो।', cat: 'Phrasal Verbs' },
  { en: 'I will deal with this matter.', hi: 'मैं इस मामले को संभालूंगा।', cat: 'Phrasal Verbs' },
  { en: 'Please do away with old habits.', hi: 'कृपया पुरानी आदतें छोड़ दो।', cat: 'Phrasal Verbs' },
  { en: 'I need to dress up for the party.', hi: 'मुझे पार्टी के लिए तैयार होना है।', cat: 'Phrasal Verbs' },
  { en: 'Please drop by whenever you can.', hi: 'जब भी हो सके आ जाना।', cat: 'Phrasal Verbs' },
  { en: 'I will drop in to see you.', hi: 'मैं तुमसे मिलने आऊंगा।', cat: 'Phrasal Verbs' },
  { en: 'Please eat up all your food.', hi: 'कृपया अपना सारा खाना खा लो।', cat: 'Phrasal Verbs' },
  { en: 'I need to end up this project.', hi: 'मुझे यह प्रोजेक्ट खत्म करना है।', cat: 'Phrasal Verbs' },
  { en: 'We ended up going to the beach.', hi: 'आखिरकार हम समुद्र तट पर गए।', cat: 'Phrasal Verbs' },

  // Business Phrasal Verbs (50)
  { en: 'We need to branch out into new markets.', hi: 'हमें नए बाजारों में विस्तार करना होगा।', cat: 'Business Phrasal' },
  { en: 'The company is scaling up operations.', hi: 'कंपनी अपने संचालन का विस्तार कर रही है।', cat: 'Business Phrasal' },
  { en: 'We had to lay off some employees.', hi: 'हमें कुछ कर्मचारियों को निकालना पड़ा।', cat: 'Business Phrasal' },
  { en: 'Please draw up a contract.', hi: 'कृपया एक अनुबंध तैयार करें।', cat: 'Business Phrasal' },
  { en: 'I will follow up on this matter.', hi: 'मैं इस मामले पर फॉलो अप करूंगा।', cat: 'Business Phrasal' },
  { en: 'We need to iron out the details.', hi: 'हमें विवरण सुलझाने होंगे।', cat: 'Business Phrasal' },
  { en: 'Please pencil in a meeting for Monday.', hi: 'कृपया सोमवार के लिए मीटिंग तय करें।', cat: 'Business Phrasal' },
  { en: 'I will phase out the old system.', hi: 'मैं पुरानी प्रणाली को धीरे-धीरे बंद करूंगा।', cat: 'Business Phrasal' },
  { en: 'We need to ramp up production.', hi: 'हमें उत्पादन बढ़ाना होगा।', cat: 'Business Phrasal' },
  { en: 'Please roll out the new policy.', hi: 'कृपया नई नीति लागू करें।', cat: 'Business Phrasal' },
  { en: 'I will sign off on this proposal.', hi: 'मैं इस प्रस्ताव को मंजूरी दूंगा।', cat: 'Business Phrasal' },
  { en: 'We need to step up our efforts.', hi: 'हमें अपने प्रयास बढ़ाने होंगे।', cat: 'Business Phrasal' },
  { en: 'Please sum up the main points.', hi: 'कृपया मुख्य बिंदुओं का सारांश दें।', cat: 'Business Phrasal' },
  { en: 'I will take on this responsibility.', hi: 'मैं यह जिम्मेदारी लूंगा।', cat: 'Business Phrasal' },
  { en: 'We need to team up with them.', hi: 'हमें उनके साथ मिलकर काम करना होगा।', cat: 'Business Phrasal' },
  { en: 'Please touch base with the client.', hi: 'कृपया क्लाइंट से संपर्क करें।', cat: 'Business Phrasal' },
  { en: 'I will weigh in on this decision.', hi: 'मैं इस फैसले पर अपनी राय दूंगा।', cat: 'Business Phrasal' },
  { en: 'We need to wind down the project.', hi: 'हमें प्रोजेक्ट को समाप्त करना होगा।', cat: 'Business Phrasal' },
  { en: 'Please zero in on the problem.', hi: 'कृपया समस्या पर ध्यान केंद्रित करें।', cat: 'Business Phrasal' },
  { en: 'I will bail out the company.', hi: 'मैं कंपनी को बचाऊंगा।', cat: 'Business Phrasal' },
  { en: 'We need to buy out the competitor.', hi: 'हमें प्रतिस्पर्धी को खरीदना होगा।', cat: 'Business Phrasal' },
  { en: 'Please cash in on this opportunity.', hi: 'कृपया इस अवसर का लाभ उठाएं।', cat: 'Business Phrasal' },
  { en: 'I will chip in for the gift.', hi: 'मैं उपहार के लिए योगदान दूंगा।', cat: 'Business Phrasal' },
  { en: 'We need to factor in all costs.', hi: 'हमें सभी लागतों को शामिल करना होगा।', cat: 'Business Phrasal' },
  { en: 'Please fork out the money.', hi: 'कृपया पैसे दे दो।', cat: 'Business Phrasal' },
  { en: 'I will hammer out an agreement.', hi: 'मैं एक समझौता तैयार करूंगा।', cat: 'Business Phrasal' },
  { en: 'We need to hash out the details.', hi: 'हमें विवरण पर चर्चा करनी होगी।', cat: 'Business Phrasal' },
  { en: 'Please kick off the meeting.', hi: 'कृपया मीटिंग शुरू करें।', cat: 'Business Phrasal' },
  { en: 'I will map out the strategy.', hi: 'मैं रणनीति बनाऊंगा।', cat: 'Business Phrasal' },
  { en: 'We need to opt out of this deal.', hi: 'हमें इस सौदे से बाहर निकलना होगा।', cat: 'Business Phrasal' },
  { en: 'Please pan out the budget.', hi: 'कृपया बजट का विस्तार करें।', cat: 'Business Phrasal' },
  { en: 'I hope this plan pans out.', hi: 'मुझे उम्मीद है यह योजना सफल होगी।', cat: 'Business Phrasal' },
  { en: 'We need to phase in the changes.', hi: 'हमें बदलाव धीरे-धीरे लागू करने होंगे।', cat: 'Business Phrasal' },
  { en: 'Please pitch in with ideas.', hi: 'कृपया विचारों में योगदान दें।', cat: 'Business Phrasal' },
  { en: 'I will pull off this deal.', hi: 'मैं यह सौदा पूरा करूंगा।', cat: 'Business Phrasal' },
  { en: 'We need to push through the reforms.', hi: 'हमें सुधारों को आगे बढ़ाना होगा।', cat: 'Business Phrasal' },
  { en: 'Please rack up the sales.', hi: 'कृपया बिक्री बढ़ाएं।', cat: 'Business Phrasal' },
  { en: 'I will round up the team.', hi: 'मैं टीम को इकट्ठा करूंगा।', cat: 'Business Phrasal' },
  { en: 'We need to scale back expenses.', hi: 'हमें खर्च कम करने होंगे।', cat: 'Business Phrasal' },
  { en: 'Please sell off the assets.', hi: 'कृपया संपत्ति बेच दें।', cat: 'Business Phrasal' },
  { en: 'I will set aside some funds.', hi: 'मैं कुछ धन अलग रखूंगा।', cat: 'Business Phrasal' },
  { en: 'We need to shore up our finances.', hi: 'हमें अपने वित्त को मजबूत करना होगा।', cat: 'Business Phrasal' },
  { en: 'Please sign up for the newsletter.', hi: 'कृपया न्यूजलेटर के लिए साइन अप करें।', cat: 'Business Phrasal' },
  { en: 'I will size up the competition.', hi: 'मैं प्रतिस्पर्धा का आकलन करूंगा।', cat: 'Business Phrasal' },
  { en: 'We need to smooth over the conflict.', hi: 'हमें विवाद को सुलझाना होगा।', cat: 'Business Phrasal' },
  { en: 'Please spell out the terms.', hi: 'कृपया शर्तें स्पष्ट करें।', cat: 'Business Phrasal' },
  { en: 'I will stake out our position.', hi: 'मैं हमारी स्थिति स्पष्ट करूंगा।', cat: 'Business Phrasal' },
  { en: 'We need to stand by our decision.', hi: 'हमें अपने फैसले पर कायम रहना होगा।', cat: 'Business Phrasal' },
  { en: 'Please start up the new venture.', hi: 'कृपया नया उद्यम शुरू करें।', cat: 'Business Phrasal' },
  { en: 'I will stick to the plan.', hi: 'मैं योजना पर कायम रहूंगा।', cat: 'Business Phrasal' },
];
