// CULTURAL CONTEXT LESSONS - 120 lessons
export const culturalLessons = [
  // British vs American English (40)
  { en: 'Flat (UK) = Apartment (US)', hi: 'Flat (ब्रिटिश) = Apartment (अमेरिकी) - दोनों का मतलब फ्लैट है।', cat: 'British vs American' },
  { en: 'Lift (UK) = Elevator (US)', hi: 'Lift (ब्रिटिश) = Elevator (अमेरिकी) - दोनों का मतलब लिफ्ट है।', cat: 'British vs American' },
  { en: 'Lorry (UK) = Truck (US)', hi: 'Lorry (ब्रिटिश) = Truck (अमेरिकी) - दोनों का मतलब ट्रक है।', cat: 'British vs American' },
  { en: 'Petrol (UK) = Gas/Gasoline (US)', hi: 'Petrol (ब्रिटिश) = Gas (अमेरिकी) - दोनों का मतलब पेट्रोल है।', cat: 'British vs American' },
  { en: 'Bonnet (UK) = Hood (US)', hi: 'Bonnet (ब्रिटिश) = Hood (अमेरिकी) - गाड़ी का बोनट।', cat: 'British vs American' },
  { en: 'Boot (UK) = Trunk (US)', hi: 'Boot (ब्रिटिश) = Trunk (अमेरिकी) - गाड़ी की डिक्की।', cat: 'British vs American' },
  { en: 'Pavement (UK) = Sidewalk (US)', hi: 'Pavement (ब्रिटिश) = Sidewalk (अमेरिकी) - फुटपाथ।', cat: 'British vs American' },
  { en: 'Queue (UK) = Line (US)', hi: 'Queue (ब्रिटिश) = Line (अमेरिकी) - कतार।', cat: 'British vs American' },
  { en: 'Rubbish (UK) = Garbage/Trash (US)', hi: 'Rubbish (ब्रिटिश) = Garbage (अमेरिकी) - कचरा।', cat: 'British vs American' },
  { en: 'Bin (UK) = Trash can (US)', hi: 'Bin (ब्रिटिश) = Trash can (अमेरिकी) - कूड़ेदान।', cat: 'British vs American' },
  { en: 'Chemist (UK) = Pharmacy/Drugstore (US)', hi: 'Chemist (ब्रिटिश) = Pharmacy (अमेरिकी) - दवाई की दुकान।', cat: 'British vs American' },
  { en: 'Holiday (UK) = Vacation (US)', hi: 'Holiday (ब्रिटिश) = Vacation (अमेरिकी) - छुट्टी।', cat: 'British vs American' },
  { en: 'Biscuit (UK) = Cookie (US)', hi: 'Biscuit (ब्रिटिश) = Cookie (अमेरिकी) - बिस्कुट।', cat: 'British vs American' },
  { en: 'Chips (UK) = French fries (US)', hi: 'Chips (ब्रिटिश) = French fries (अमेरिकी) - फ्रेंच फ्राइज।', cat: 'British vs American' },
  { en: 'Crisps (UK) = Chips (US)', hi: 'Crisps (ब्रिटिश) = Chips (अमेरिकी) - आलू के चिप्स।', cat: 'British vs American' },
  { en: 'Football (UK) = Soccer (US)', hi: 'Football (ब्रिटिश) = Soccer (अमेरिकी) - फुटबॉल।', cat: 'British vs American' },
  { en: 'Torch (UK) = Flashlight (US)', hi: 'Torch (ब्रिटिश) = Flashlight (अमेरिकी) - टॉर्च।', cat: 'British vs American' },
  { en: 'Mobile (UK) = Cell phone (US)', hi: 'Mobile (ब्रिटिश) = Cell phone (अमेरिकी) - मोबाइल फोन।', cat: 'British vs American' },
  { en: 'Post (UK) = Mail (US)', hi: 'Post (ब्रिटिश) = Mail (अमेरिकी) - डाक।', cat: 'British vs American' },
  { en: 'Postbox (UK) = Mailbox (US)', hi: 'Postbox (ब्रिटिश) = Mailbox (अमेरिकी) - डाक पेटी।', cat: 'British vs American' },
  { en: 'Colour (UK) = Color (US)', hi: 'Colour (ब्रिटिश) = Color (अमेरिकी) - स्पेलिंग में अंतर।', cat: 'British vs American' },
  { en: 'Favour (UK) = Favor (US)', hi: 'Favour (ब्रिटिश) = Favor (अमेरिकी) - स्पेलिंग में अंतर।', cat: 'British vs American' },
  { en: 'Centre (UK) = Center (US)', hi: 'Centre (ब्रिटिश) = Center (अमेरिकी) - स्पेलिंग में अंतर।', cat: 'British vs American' },
  { en: 'Theatre (UK) = Theater (US)', hi: 'Theatre (ब्रिटिश) = Theater (अमेरिकी) - स्पेलिंग में अंतर।', cat: 'British vs American' },
  { en: 'Programme (UK) = Program (US)', hi: 'Programme (ब्रिटिश) = Program (अमेरिकी) - स्पेलिंग में अंतर।', cat: 'British vs American' },
  { en: 'Travelling (UK) = Traveling (US)', hi: 'Travelling (ब्रिटिश) = Traveling (अमेरिकी) - डबल L vs सिंगल L।', cat: 'British vs American' },
  { en: 'Cancelled (UK) = Canceled (US)', hi: 'Cancelled (ब्रिटिश) = Canceled (अमेरिकी) - डबल L vs सिंगल L।', cat: 'British vs American' },
  { en: 'Realise (UK) = Realize (US)', hi: 'Realise (ब्रिटिश) = Realize (अमेरिकी) - S vs Z।', cat: 'British vs American' },
  { en: 'Organise (UK) = Organize (US)', hi: 'Organise (ब्रिटिश) = Organize (अमेरिकी) - S vs Z।', cat: 'British vs American' },
  { en: 'Analyse (UK) = Analyze (US)', hi: 'Analyse (ब्रिटिश) = Analyze (अमेरिकी) - S vs Z।', cat: 'British vs American' },
  { en: 'Ground floor (UK) = First floor (US)', hi: 'Ground floor (ब्रिटिश) = First floor (अमेरिकी) - मंजिल गिनती में अंतर।', cat: 'British vs American' },
  { en: 'First floor (UK) = Second floor (US)', hi: 'First floor (ब्रिटिश) = Second floor (अमेरिकी) - मंजिल गिनती में अंतर।', cat: 'British vs American' },
  { en: 'Autumn (UK) = Fall (US)', hi: 'Autumn (ब्रिटिश) = Fall (अमेरिकी) - पतझड़।', cat: 'British vs American' },
  { en: 'Wardrobe (UK) = Closet (US)', hi: 'Wardrobe (ब्रिटिश) = Closet (अमेरिकी) - अलमारी।', cat: 'British vs American' },
  { en: 'Garden (UK) = Yard (US)', hi: 'Garden (ब्रिटिश) = Yard (अमेरिकी) - बगीचा/आंगन।', cat: 'British vs American' },
  { en: 'Nappy (UK) = Diaper (US)', hi: 'Nappy (ब्रिटिश) = Diaper (अमेरिकी) - बच्चे की लंगोट।', cat: 'British vs American' },
  { en: 'Dummy (UK) = Pacifier (US)', hi: 'Dummy (ब्रिटिश) = Pacifier (अमेरिकी) - बच्चे की चुसनी।', cat: 'British vs American' },
  { en: 'Trainers (UK) = Sneakers (US)', hi: 'Trainers (ब्रिटिश) = Sneakers (अमेरिकी) - स्पोर्ट्स जूते।', cat: 'British vs American' },
  { en: 'Trousers (UK) = Pants (US)', hi: 'Trousers (ब्रिटिश) = Pants (अमेरिकी) - पैंट।', cat: 'British vs American' },
  { en: 'Jumper (UK) = Sweater (US)', hi: 'Jumper (ब्रिटिश) = Sweater (अमेरिकी) - स्वेटर।', cat: 'British vs American' },

  // Australian English (20)
  { en: 'G\'day mate! (Australian greeting)', hi: 'G\'day mate! - ऑस्ट्रेलियाई अभिवादन, मतलब "Hello friend!"', cat: 'Australian English' },
  { en: 'No worries! (Australian)', hi: 'No worries! - ऑस्ट्रेलियाई में "कोई बात नहीं" या "ठीक है"।', cat: 'Australian English' },
  { en: 'Arvo (Australian) = Afternoon', hi: 'Arvo - ऑस्ट्रेलियाई में दोपहर के लिए।', cat: 'Australian English' },
  { en: 'Brekkie (Australian) = Breakfast', hi: 'Brekkie - ऑस्ट्रेलियाई में नाश्ते के लिए।', cat: 'Australian English' },
  { en: 'Barbie (Australian) = Barbecue', hi: 'Barbie - ऑस्ट्रेलियाई में बारबेक्यू के लिए।', cat: 'Australian English' },
  { en: 'Servo (Australian) = Service station', hi: 'Servo - ऑस्ट्रेलियाई में पेट्रोल पंप के लिए।', cat: 'Australian English' },
  { en: 'Bottle-o (Australian) = Liquor store', hi: 'Bottle-o - ऑस्ट्रेलियाई में शराब की दुकान के लिए।', cat: 'Australian English' },
  { en: 'Chook (Australian) = Chicken', hi: 'Chook - ऑस्ट्रेलियाई में मुर्गी के लिए।', cat: 'Australian English' },
  { en: 'Thongs (Australian) = Flip-flops', hi: 'Thongs - ऑस्ट्रेलियाई में चप्पल के लिए।', cat: 'Australian English' },
  { en: 'Sunnies (Australian) = Sunglasses', hi: 'Sunnies - ऑस्ट्रेलियाई में धूप का चश्मा के लिए।', cat: 'Australian English' },
  { en: 'Maccas (Australian) = McDonald\'s', hi: 'Maccas - ऑस्ट्रेलियाई में मैकडॉनल्ड्स के लिए।', cat: 'Australian English' },
  { en: 'Ute (Australian) = Pickup truck', hi: 'Ute - ऑस्ट्रेलियाई में पिकअप ट्रक के लिए।', cat: 'Australian English' },
  { en: 'Esky (Australian) = Cooler box', hi: 'Esky - ऑस्ट्रेलियाई में कूलर बॉक्स के लिए।', cat: 'Australian English' },
  { en: 'Mozzie (Australian) = Mosquito', hi: 'Mozzie - ऑस्ट्रेलियाई में मच्छर के लिए।', cat: 'Australian English' },
  { en: 'Bikkie (Australian) = Biscuit', hi: 'Bikkie - ऑस्ट्रेलियाई में बिस्कुट के लिए।', cat: 'Australian English' },
  { en: 'Cuppa (Australian/British) = Cup of tea', hi: 'Cuppa - एक कप चाय के लिए।', cat: 'Australian English' },
  { en: 'Ta (Australian/British) = Thank you', hi: 'Ta - धन्यवाद का छोटा रूप।', cat: 'Australian English' },
  { en: 'Reckon (Australian) = Think/Believe', hi: 'Reckon - सोचना/मानना।', cat: 'Australian English' },
  { en: 'Heaps (Australian) = A lot', hi: 'Heaps - बहुत सारा।', cat: 'Australian English' },
  { en: 'Fair dinkum (Australian) = Genuine/True', hi: 'Fair dinkum - सच्चा/असली।', cat: 'Australian English' },

  // Business Culture (20)
  { en: 'Let\'s schedule a meeting.', hi: 'पश्चिमी देशों में मीटिंग पहले से शेड्यूल करना जरूरी है। अचानक मिलना अशिष्ट माना जाता है।', cat: 'Business Culture' },
  { en: 'I\'ll get back to you by EOD.', hi: 'EOD = End of Day। पश्चिमी बिजनेस में समय सीमा बहुत महत्वपूर्ण है।', cat: 'Business Culture' },
  { en: 'Let\'s touch base next week.', hi: 'Touch base = संपर्क करना। बिजनेस में फॉलो-अप के लिए आम वाक्य।', cat: 'Business Culture' },
  { en: 'Can we take this offline?', hi: 'Take offline = मीटिंग के बाद अलग से बात करना। ग्रुप में नहीं।', cat: 'Business Culture' },
  { en: 'Let\'s circle back on this.', hi: 'Circle back = बाद में इस विषय पर वापस आना।', cat: 'Business Culture' },
  { en: 'I\'ll loop you in on the email.', hi: 'Loop in = ईमेल में शामिल करना। CC करना।', cat: 'Business Culture' },
  { en: 'We need to align on this.', hi: 'Align = सहमत होना। टीम में एक राय होना।', cat: 'Business Culture' },
  { en: 'Let\'s sync up tomorrow.', hi: 'Sync up = मिलकर अपडेट लेना। स्थिति जानना।', cat: 'Business Culture' },
  { en: 'Can you give me a ballpark figure?', hi: 'Ballpark figure = अनुमानित आंकड़ा। सटीक नहीं।', cat: 'Business Culture' },
  { en: 'We\'re on the same page.', hi: 'On the same page = एक ही राय पर। सहमत।', cat: 'Business Culture' },
  { en: 'Let\'s table this discussion.', hi: 'Table (US) = बाद के लिए रखना। Table (UK) = अभी चर्चा करना। विपरीत अर्थ!', cat: 'Business Culture' },
  { en: 'I\'ll ping you later.', hi: 'Ping = मैसेज करना। जल्दी संपर्क करना।', cat: 'Business Culture' },
  { en: 'Let\'s brainstorm some ideas.', hi: 'Brainstorm = मिलकर विचार करना। नए आइडिया सोचना।', cat: 'Business Culture' },
  { en: 'We need to think outside the box.', hi: 'Think outside the box = नए तरीके से सोचना। अलग दृष्टिकोण।', cat: 'Business Culture' },
  { en: 'Let\'s hit the ground running.', hi: 'Hit the ground running = तुरंत काम शुरू करना। बिना देरी।', cat: 'Business Culture' },
  { en: 'We\'re in the same boat.', hi: 'In the same boat = एक जैसी स्थिति में। साथ में।', cat: 'Business Culture' },
  { en: 'Let\'s put a pin in it.', hi: 'Put a pin in it = अभी रोकें, बाद में करें।', cat: 'Business Culture' },
  { en: 'Can you take the lead on this?', hi: 'Take the lead = नेतृत्व करना। जिम्मेदारी लेना।', cat: 'Business Culture' },
  { en: 'Let\'s leverage our resources.', hi: 'Leverage = उपयोग करना। फायदा उठाना।', cat: 'Business Culture' },
  { en: 'We need to pivot our strategy.', hi: 'Pivot = दिशा बदलना। नई रणनीति अपनाना।', cat: 'Business Culture' },

  // Meeting Etiquette (20)
  { en: 'Shall we begin?', hi: 'मीटिंग शुरू करने का विनम्र तरीका। सभी तैयार हैं?', cat: 'Meeting Etiquette' },
  { en: 'Thank you all for joining.', hi: 'मीटिंग की शुरुआत में सभी का धन्यवाद करना शिष्टाचार है।', cat: 'Meeting Etiquette' },
  { en: 'Let\'s go around the room.', hi: 'Go around the room = सभी से बारी-बारी राय लेना।', cat: 'Meeting Etiquette' },
  { en: 'Does anyone have any questions?', hi: 'प्रेजेंटेशन के बाद सवाल पूछने का मौका देना जरूरी है।', cat: 'Meeting Etiquette' },
  { en: 'I\'d like to add something.', hi: 'बीच में बोलने से पहले अनुमति लेना शिष्टाचार है।', cat: 'Meeting Etiquette' },
  { en: 'Sorry to interrupt, but...', hi: 'बीच में बोलने के लिए माफी मांगना जरूरी है।', cat: 'Meeting Etiquette' },
  { en: 'Could you elaborate on that?', hi: 'Elaborate = विस्तार से बताना। और जानकारी मांगना।', cat: 'Meeting Etiquette' },
  { en: 'Let me share my screen.', hi: 'वर्चुअल मीटिंग में स्क्रीन शेयर करने से पहले बताना।', cat: 'Meeting Etiquette' },
  { en: 'Can everyone see my screen?', hi: 'स्क्रीन शेयर के बाद कन्फर्म करना अच्छा है।', cat: 'Meeting Etiquette' },
  { en: 'You\'re on mute.', hi: 'वर्चुअल मीटिंग में आम वाक्य - माइक बंद है।', cat: 'Meeting Etiquette' },
  { en: 'Let\'s wrap up.', hi: 'Wrap up = समाप्त करना। मीटिंग खत्म करना।', cat: 'Meeting Etiquette' },
  { en: 'To summarize...', hi: 'मीटिंग के अंत में सारांश देना महत्वपूर्ण है।', cat: 'Meeting Etiquette' },
  { en: 'What are the action items?', hi: 'Action items = आगे के काम। किसे क्या करना है।', cat: 'Meeting Etiquette' },
  { en: 'Who\'s taking notes?', hi: 'मीटिंग में नोट्स लेना जरूरी है। मिनट्स ऑफ मीटिंग।', cat: 'Meeting Etiquette' },
  { en: 'Let\'s set a deadline.', hi: 'Deadline = समय सीमा। कब तक पूरा करना है।', cat: 'Meeting Etiquette' },
  { en: 'I\'ll send the minutes.', hi: 'Minutes = मीटिंग का सारांश। ईमेल से भेजना।', cat: 'Meeting Etiquette' },
  { en: 'Any other business?', hi: 'AOB = Any Other Business। और कोई मुद्दा?', cat: 'Meeting Etiquette' },
  { en: 'Let\'s reconvene next week.', hi: 'Reconvene = फिर से मिलना। अगली मीटिंग।', cat: 'Meeting Etiquette' },
  { en: 'Thanks for your time.', hi: 'मीटिंग के अंत में समय के लिए धन्यवाद देना।', cat: 'Meeting Etiquette' },
  { en: 'I\'ll follow up with an email.', hi: 'मीटिंग के बाद ईमेल से फॉलो-अप करना प्रोफेशनल है।', cat: 'Meeting Etiquette' },

  // Gift-Giving Customs (10)
  { en: 'This is just a small token.', hi: 'पश्चिमी देशों में गिफ्ट देते समय विनम्रता दिखाना।', cat: 'Gift-Giving Customs' },
  { en: 'You shouldn\'t have!', hi: 'गिफ्ट मिलने पर कहा जाता है - आपको परेशान नहीं होना चाहिए था।', cat: 'Gift-Giving Customs' },
  { en: 'Can I open it now?', hi: 'पश्चिमी देशों में गिफ्ट तुरंत खोलना सामान्य है। एशिया में नहीं।', cat: 'Gift-Giving Customs' },
  { en: 'I hope you like it.', hi: 'गिफ्ट देते समय कहा जाता है।', cat: 'Gift-Giving Customs' },
  { en: 'It\'s the thought that counts.', hi: 'गिफ्ट की कीमत नहीं, भावना महत्वपूर्ण है।', cat: 'Gift-Giving Customs' },
  { en: 'I got this for you.', hi: 'गिफ्ट देने का सामान्य तरीका।', cat: 'Gift-Giving Customs' },
  { en: 'Thank you so much!', hi: 'गिफ्ट मिलने पर उत्साह दिखाना जरूरी है।', cat: 'Gift-Giving Customs' },
  { en: 'This is too kind of you.', hi: 'गिफ्ट के लिए आभार प्रकट करना।', cat: 'Gift-Giving Customs' },
  { en: 'I\'ll treasure this.', hi: 'Treasure = संभालकर रखना। गिफ्ट की कद्र करना।', cat: 'Gift-Giving Customs' },
  { en: 'Where did you find this?', hi: 'गिफ्ट में रुचि दिखाना शिष्टाचार है।', cat: 'Gift-Giving Customs' },

  // Negotiation Styles (10)
  { en: 'What\'s your best price?', hi: 'सबसे अच्छी कीमत पूछना। मोलभाव शुरू करना।', cat: 'Negotiation Styles' },
  { en: 'Is there any room for negotiation?', hi: 'क्या कीमत में कुछ कमी हो सकती है?', cat: 'Negotiation Styles' },
  { en: 'Let\'s meet in the middle.', hi: 'Meet in the middle = बीच का रास्ता निकालना। समझौता।', cat: 'Negotiation Styles' },
  { en: 'That\'s a deal-breaker.', hi: 'Deal-breaker = जिस पर समझौता नहीं हो सकता।', cat: 'Negotiation Styles' },
  { en: 'We can be flexible on this.', hi: 'Flexible = लचीला। इसमें बदलाव हो सकता है।', cat: 'Negotiation Styles' },
  { en: 'What\'s your bottom line?', hi: 'Bottom line = न्यूनतम स्वीकार्य। आखिरी कीमत।', cat: 'Negotiation Styles' },
  { en: 'Let\'s shake on it.', hi: 'Shake on it = हाथ मिलाकर सौदा पक्का करना।', cat: 'Negotiation Styles' },
  { en: 'I\'ll need to consult my team.', hi: 'बड़े फैसले के लिए टीम से बात करना जरूरी है।', cat: 'Negotiation Styles' },
  { en: 'Can we revisit this later?', hi: 'Revisit = बाद में फिर से विचार करना।', cat: 'Negotiation Styles' },
  { en: 'We have a deal!', hi: 'सौदा पक्का! समझौता हो गया।', cat: 'Negotiation Styles' },
];
