// MORE ADVANCED LESSONS - 200 lessons
export const advancedLessons2 = [
  // Common Mistakes by Hindi Speakers (50)
  { en: 'I am having a car. (Wrong) → I have a car.', hi: 'मेरे पास गाड़ी है। (have का सही प्रयोग)', cat: 'Common Mistakes' },
  { en: 'She is knowing the answer. (Wrong) → She knows the answer.', hi: 'वह जवाब जानती है। (know के साथ -ing नहीं)', cat: 'Common Mistakes' },
  { en: 'I am understanding. (Wrong) → I understand.', hi: 'मैं समझता हूँ। (understand के साथ -ing नहीं)', cat: 'Common Mistakes' },
  { en: 'He is believing me. (Wrong) → He believes me.', hi: 'वह मुझ पर विश्वास करता है।', cat: 'Common Mistakes' },
  { en: 'I am liking this movie. (Wrong) → I like this movie.', hi: 'मुझे यह फिल्म पसंद है।', cat: 'Common Mistakes' },
  { en: 'She is loving her job. (Wrong) → She loves her job.', hi: 'उसे अपनी नौकरी पसंद है।', cat: 'Common Mistakes' },
  { en: 'I am wanting tea. (Wrong) → I want tea.', hi: 'मुझे चाय चाहिए।', cat: 'Common Mistakes' },
  { en: 'He is needing help. (Wrong) → He needs help.', hi: 'उसे मदद चाहिए।', cat: 'Common Mistakes' },
  { en: 'I did not went. (Wrong) → I did not go.', hi: 'मैं नहीं गया। (did के बाद base form)', cat: 'Common Mistakes' },
  { en: 'She did not came. (Wrong) → She did not come.', hi: 'वह नहीं आई।', cat: 'Common Mistakes' },
  { en: 'He did not told me. (Wrong) → He did not tell me.', hi: 'उसने मुझे नहीं बताया।', cat: 'Common Mistakes' },
  { en: 'I have went there. (Wrong) → I have gone there.', hi: 'मैं वहाँ गया हूँ। (have के बाद past participle)', cat: 'Common Mistakes' },
  { en: 'She has came. (Wrong) → She has come.', hi: 'वह आ गई है।', cat: 'Common Mistakes' },
  { en: 'He has wrote a letter. (Wrong) → He has written a letter.', hi: 'उसने पत्र लिखा है।', cat: 'Common Mistakes' },
  { en: 'I am agree with you. (Wrong) → I agree with you.', hi: 'मैं आपसे सहमत हूँ। (agree के पहले am नहीं)', cat: 'Common Mistakes' },
  { en: 'She is not agree. (Wrong) → She does not agree.', hi: 'वह सहमत नहीं है।', cat: 'Common Mistakes' },
  { en: 'I discussed about this. (Wrong) → I discussed this.', hi: 'मैंने इस पर चर्चा की। (discuss के बाद about नहीं)', cat: 'Common Mistakes' },
  { en: 'He entered into the room. (Wrong) → He entered the room.', hi: 'वह कमरे में घुसा। (enter के बाद into नहीं)', cat: 'Common Mistakes' },
  { en: 'She married with him. (Wrong) → She married him.', hi: 'उसने उससे शादी की। (marry के बाद with नहीं)', cat: 'Common Mistakes' },
  { en: 'I reached at the station. (Wrong) → I reached the station.', hi: 'मैं स्टेशन पहुंचा। (reach के बाद at नहीं)', cat: 'Common Mistakes' },
  { en: 'He ordered for tea. (Wrong) → He ordered tea.', hi: 'उसने चाय मंगाई। (order के बाद for नहीं)', cat: 'Common Mistakes' },
  { en: 'She requested for help. (Wrong) → She requested help.', hi: 'उसने मदद मांगी।', cat: 'Common Mistakes' },
  { en: 'I told to him. (Wrong) → I told him.', hi: 'मैंने उसे बताया। (told के बाद to नहीं)', cat: 'Common Mistakes' },
  { en: 'She asked to me. (Wrong) → She asked me.', hi: 'उसने मुझसे पूछा।', cat: 'Common Mistakes' },
  { en: 'He explained me. (Wrong) → He explained to me.', hi: 'उसने मुझे समझाया। (explain के बाद to चाहिए)', cat: 'Common Mistakes' },
  { en: 'She suggested me. (Wrong) → She suggested to me.', hi: 'उसने मुझे सुझाव दिया।', cat: 'Common Mistakes' },
  { en: 'I am working since morning. (Wrong) → I have been working since morning.', hi: 'मैं सुबह से काम कर रहा हूँ।', cat: 'Common Mistakes' },
  { en: 'She is living here since 2010. (Wrong) → She has been living here since 2010.', hi: 'वह 2010 से यहाँ रह रही है।', cat: 'Common Mistakes' },
  { en: 'I know him since childhood. (Wrong) → I have known him since childhood.', hi: 'मैं उसे बचपन से जानता हूँ।', cat: 'Common Mistakes' },
  { en: 'He is my cousin brother. (Wrong) → He is my cousin.', hi: 'वह मेरा चचेरा भाई है। (cousin के बाद brother नहीं)', cat: 'Common Mistakes' },
  { en: 'She is my cousin sister. (Wrong) → She is my cousin.', hi: 'वह मेरी चचेरी बहन है।', cat: 'Common Mistakes' },
  { en: 'I have a doubt. (Wrong) → I have a question.', hi: 'मेरा एक सवाल है। (doubt का मतलब संदेह है)', cat: 'Common Mistakes' },
  { en: 'Please revert back. (Wrong) → Please revert.', hi: 'कृपया जवाब दें। (revert में back शामिल है)', cat: 'Common Mistakes' },
  { en: 'Return back the book. (Wrong) → Return the book.', hi: 'किताब वापस करो।', cat: 'Common Mistakes' },
  { en: 'Repeat again. (Wrong) → Repeat.', hi: 'दोहराओ। (repeat में again शामिल है)', cat: 'Common Mistakes' },
  { en: 'I will cope up with this. (Wrong) → I will cope with this.', hi: 'मैं इससे निपट लूंगा।', cat: 'Common Mistakes' },
  { en: 'She is more better. (Wrong) → She is better.', hi: 'वह बेहतर है। (better के पहले more नहीं)', cat: 'Common Mistakes' },
  { en: 'This is more easier. (Wrong) → This is easier.', hi: 'यह आसान है।', cat: 'Common Mistakes' },
  { en: 'He is the most tallest. (Wrong) → He is the tallest.', hi: 'वह सबसे लंबा है।', cat: 'Common Mistakes' },
  { en: 'I am not able to able to come. (Wrong) → I am unable to come.', hi: 'मैं आने में असमर्थ हूँ।', cat: 'Common Mistakes' },
  { en: 'She gave me an advice. (Wrong) → She gave me advice.', hi: 'उसने मुझे सलाह दी। (advice uncountable है)', cat: 'Common Mistakes' },
  { en: 'I need informations. (Wrong) → I need information.', hi: 'मुझे जानकारी चाहिए। (information uncountable है)', cat: 'Common Mistakes' },
  { en: 'He has many luggages. (Wrong) → He has a lot of luggage.', hi: 'उसके पास बहुत सामान है।', cat: 'Common Mistakes' },
  { en: 'She bought new furnitures. (Wrong) → She bought new furniture.', hi: 'उसने नया फर्नीचर खरीदा।', cat: 'Common Mistakes' },
  { en: 'I have many works. (Wrong) → I have a lot of work.', hi: 'मेरे पास बहुत काम है।', cat: 'Common Mistakes' },
  { en: 'He gave me good news. (Correct)', hi: 'उसने मुझे अच्छी खबर दी। (news singular है)', cat: 'Common Mistakes' },
  { en: 'The news are good. (Wrong) → The news is good.', hi: 'खबर अच्छी है।', cat: 'Common Mistakes' },
  { en: 'Mathematics are difficult. (Wrong) → Mathematics is difficult.', hi: 'गणित कठिन है।', cat: 'Common Mistakes' },
  { en: 'Physics are interesting. (Wrong) → Physics is interesting.', hi: 'भौतिकी दिलचस्प है।', cat: 'Common Mistakes' },
  { en: 'The police is coming. (Wrong) → The police are coming.', hi: 'पुलिस आ रही है। (police plural है)', cat: 'Common Mistakes' },

  // Confusing Words (50)
  { en: 'Accept means to receive. Except means excluding.', hi: 'Accept = स्वीकार करना। Except = को छोड़कर।', cat: 'Confusing Words' },
  { en: 'Affect is a verb. Effect is a noun.', hi: 'Affect = प्रभावित करना (क्रिया)। Effect = प्रभाव (संज्ञा)।', cat: 'Confusing Words' },
  { en: 'Advice is a noun. Advise is a verb.', hi: 'Advice = सलाह (संज्ञा)। Advise = सलाह देना (क्रिया)।', cat: 'Confusing Words' },
  { en: 'Beside means next to. Besides means in addition to.', hi: 'Beside = बगल में। Besides = इसके अलावा।', cat: 'Confusing Words' },
  { en: 'Borrow means to take. Lend means to give.', hi: 'Borrow = उधार लेना। Lend = उधार देना।', cat: 'Confusing Words' },
  { en: 'Bring means towards speaker. Take means away from speaker.', hi: 'Bring = लाना। Take = ले जाना।', cat: 'Confusing Words' },
  { en: 'Cloth is material. Clothes are garments.', hi: 'Cloth = कपड़ा। Clothes = कपड़े।', cat: 'Confusing Words' },
  { en: 'Complement means to complete. Compliment means praise.', hi: 'Complement = पूरक। Compliment = तारीफ।', cat: 'Confusing Words' },
  { en: 'Desert is dry land. Dessert is sweet dish.', hi: 'Desert = रेगिस्तान। Dessert = मिठाई।', cat: 'Confusing Words' },
  { en: 'Emigrate means to leave a country. Immigrate means to enter a country.', hi: 'Emigrate = देश छोड़ना। Immigrate = देश में आना।', cat: 'Confusing Words' },
  { en: 'Farther is for distance. Further is for degree.', hi: 'Farther = दूरी के लिए। Further = और अधिक।', cat: 'Confusing Words' },
  { en: 'Fewer is for countable. Less is for uncountable.', hi: 'Fewer = गिनने योग्य के लिए। Less = न गिनने योग्य के लिए।', cat: 'Confusing Words' },
  { en: 'Historic means important. Historical means related to history.', hi: 'Historic = ऐतिहासिक (महत्वपूर्ण)। Historical = इतिहास संबंधी।', cat: 'Confusing Words' },
  { en: 'Its is possessive. It\'s means it is.', hi: 'Its = इसका। It\'s = यह है।', cat: 'Confusing Words' },
  { en: 'Lay needs an object. Lie does not need an object.', hi: 'Lay = रखना (कुछ को)। Lie = लेटना।', cat: 'Confusing Words' },
  { en: 'Loose is an adjective. Lose is a verb.', hi: 'Loose = ढीला। Lose = खोना।', cat: 'Confusing Words' },
  { en: 'Principal means main or head. Principle means rule.', hi: 'Principal = प्रधान। Principle = सिद्धांत।', cat: 'Confusing Words' },
  { en: 'Quiet means silent. Quite means very.', hi: 'Quiet = शांत। Quite = काफी।', cat: 'Confusing Words' },
  { en: 'Raise needs an object. Rise does not need an object.', hi: 'Raise = उठाना (कुछ को)। Rise = उठना।', cat: 'Confusing Words' },
  { en: 'Stationary means not moving. Stationery means writing materials.', hi: 'Stationary = स्थिर। Stationery = लेखन सामग्री।', cat: 'Confusing Words' },
  { en: 'Than is for comparison. Then is for time.', hi: 'Than = से (तुलना)। Then = फिर।', cat: 'Confusing Words' },
  { en: 'Their is possessive. There is for place. They\'re means they are.', hi: 'Their = उनका। There = वहाँ। They\'re = वे हैं।', cat: 'Confusing Words' },
  { en: 'Weather is climate. Whether is for choices.', hi: 'Weather = मौसम। Whether = क्या (विकल्प)।', cat: 'Confusing Words' },
  { en: 'Your is possessive. You\'re means you are.', hi: 'Your = तुम्हारा। You\'re = तुम हो।', cat: 'Confusing Words' },
  { en: 'Who\'s means who is. Whose is possessive.', hi: 'Who\'s = कौन है। Whose = किसका।', cat: 'Confusing Words' },
  { en: 'Assure is for people. Ensure is for things. Insure is for money.', hi: 'Assure = आश्वस्त करना। Ensure = सुनिश्चित करना। Insure = बीमा करना।', cat: 'Confusing Words' },
  { en: 'Among is for more than two. Between is for two.', hi: 'Among = दो से अधिक में। Between = दो के बीच।', cat: 'Confusing Words' },
  { en: 'Amount is for uncountable. Number is for countable.', hi: 'Amount = मात्रा। Number = संख्या।', cat: 'Confusing Words' },
  { en: 'Continual means repeated. Continuous means without stopping.', hi: 'Continual = बार-बार। Continuous = लगातार।', cat: 'Confusing Words' },
  { en: 'Economic means related to economy. Economical means saving money.', hi: 'Economic = आर्थिक। Economical = किफायती।', cat: 'Confusing Words' },
  { en: 'Elicit means to draw out. Illicit means illegal.', hi: 'Elicit = निकालना। Illicit = अवैध।', cat: 'Confusing Words' },
  { en: 'Eminent means famous. Imminent means about to happen.', hi: 'Eminent = प्रसिद्ध। Imminent = आसन्न।', cat: 'Confusing Words' },
  { en: 'Especially means particularly. Specially means for a special purpose.', hi: 'Especially = विशेष रूप से। Specially = खास तौर पर।', cat: 'Confusing Words' },
  { en: 'Everyday is an adjective. Every day is two words.', hi: 'Everyday = रोजमर्रा का। Every day = हर दिन।', cat: 'Confusing Words' },
  { en: 'Imply means to suggest. Infer means to conclude.', hi: 'Imply = संकेत करना। Infer = निष्कर्ष निकालना।', cat: 'Confusing Words' },
  { en: 'Precede means to come before. Proceed means to continue.', hi: 'Precede = पहले आना। Proceed = आगे बढ़ना।', cat: 'Confusing Words' },
  { en: 'Sensible means practical. Sensitive means easily affected.', hi: 'Sensible = समझदार। Sensitive = संवेदनशील।', cat: 'Confusing Words' },
  { en: 'Sometime means at some time. Sometimes means occasionally.', hi: 'Sometime = कभी। Sometimes = कभी-कभी।', cat: 'Confusing Words' },
  { en: 'Uninterested means not interested. Disinterested means neutral.', hi: 'Uninterested = उदासीन। Disinterested = निष्पक्ष।', cat: 'Confusing Words' },
  { en: 'Allude means to refer indirectly. Elude means to escape.', hi: 'Allude = संकेत करना। Elude = बचना।', cat: 'Confusing Words' },
  { en: 'Allusion is indirect reference. Illusion is false impression.', hi: 'Allusion = संकेत। Illusion = भ्रम।', cat: 'Confusing Words' },
  { en: 'Amoral means without morals. Immoral means against morals.', hi: 'Amoral = नैतिकता रहित। Immoral = अनैतिक।', cat: 'Confusing Words' },
  { en: 'Appraise means to evaluate. Apprise means to inform.', hi: 'Appraise = मूल्यांकन करना। Apprise = सूचित करना।', cat: 'Confusing Words' },
  { en: 'Averse means opposed to. Adverse means unfavorable.', hi: 'Averse = विरोधी। Adverse = प्रतिकूल।', cat: 'Confusing Words' },
  { en: 'Canvas is cloth. Canvass means to seek votes.', hi: 'Canvas = कैनवास। Canvass = वोट मांगना।', cat: 'Confusing Words' },
  { en: 'Capital is city or money. Capitol is building.', hi: 'Capital = राजधानी/पूंजी। Capitol = संसद भवन।', cat: 'Confusing Words' },
  { en: 'Cite means to quote. Site is a place. Sight is vision.', hi: 'Cite = उद्धृत करना। Site = स्थान। Sight = दृष्टि।', cat: 'Confusing Words' },
  { en: 'Coarse means rough. Course is a path or class.', hi: 'Coarse = मोटा। Course = पाठ्यक्रम।', cat: 'Confusing Words' },
  { en: 'Conscience is moral sense. Conscious means aware.', hi: 'Conscience = अंतरात्मा। Conscious = सचेत।', cat: 'Confusing Words' },
  { en: 'Council is a group. Counsel is advice.', hi: 'Council = परिषद। Counsel = सलाह।', cat: 'Confusing Words' },

  // Email & Letter Writing (50)
  { en: 'Dear Sir/Madam, I am writing to inquire about...', hi: 'महोदय/महोदया, मैं... के बारे में पूछताछ के लिए लिख रहा हूँ।', cat: 'Email Writing' },
  { en: 'I hope this email finds you well.', hi: 'मुझे आशा है कि आप कुशल होंगे।', cat: 'Email Writing' },
  { en: 'Thank you for your prompt response.', hi: 'आपके त्वरित उत्तर के लिए धन्यवाद।', cat: 'Email Writing' },
  { en: 'I am writing to follow up on my previous email.', hi: 'मैं अपने पिछले ईमेल के संबंध में लिख रहा हूँ।', cat: 'Email Writing' },
  { en: 'Please find attached the requested documents.', hi: 'कृपया अनुरोधित दस्तावेज संलग्न देखें।', cat: 'Email Writing' },
  { en: 'I would appreciate it if you could...', hi: 'मैं आभारी रहूंगा अगर आप...', cat: 'Email Writing' },
  { en: 'Could you please clarify the following points?', hi: 'क्या आप निम्नलिखित बिंदुओं को स्पष्ट कर सकते हैं?', cat: 'Email Writing' },
  { en: 'I apologize for any inconvenience caused.', hi: 'किसी भी असुविधा के लिए क्षमा चाहता हूँ।', cat: 'Email Writing' },
  { en: 'Please do not hesitate to contact me.', hi: 'कृपया मुझसे संपर्क करने में संकोच न करें।', cat: 'Email Writing' },
  { en: 'I look forward to hearing from you soon.', hi: 'आपके जल्द उत्तर की प्रतीक्षा है।', cat: 'Email Writing' },
  { en: 'Best regards, / Kind regards, / Sincerely,', hi: 'सादर, / शुभकामनाओं सहित, / भवदीय,', cat: 'Email Writing' },
  { en: 'As per our telephone conversation...', hi: 'हमारी टेलीफोन वार्ता के अनुसार...', cat: 'Email Writing' },
  { en: 'With reference to your email dated...', hi: 'आपके... दिनांकित ईमेल के संदर्भ में...', cat: 'Email Writing' },
  { en: 'I am pleased to inform you that...', hi: 'मुझे आपको सूचित करते हुए खुशी है कि...', cat: 'Email Writing' },
  { en: 'I regret to inform you that...', hi: 'मुझे आपको सूचित करते हुए खेद है कि...', cat: 'Email Writing' },
  { en: 'Please acknowledge receipt of this email.', hi: 'कृपया इस ईमेल की प्राप्ति की पुष्टि करें।', cat: 'Email Writing' },
  { en: 'I would like to bring to your attention...', hi: 'मैं आपका ध्यान आकर्षित करना चाहूंगा...', cat: 'Email Writing' },
  { en: 'For your information (FYI)...', hi: 'आपकी जानकारी के लिए...', cat: 'Email Writing' },
  { en: 'Please be advised that...', hi: 'कृपया ध्यान दें कि...', cat: 'Email Writing' },
  { en: 'I am writing on behalf of...', hi: 'मैं... की ओर से लिख रहा हूँ।', cat: 'Email Writing' },
  { en: 'Thank you for your cooperation.', hi: 'आपके सहयोग के लिए धन्यवाद।', cat: 'Email Writing' },
  { en: 'I trust this meets with your approval.', hi: 'मुझे विश्वास है यह आपकी स्वीकृति के अनुरूप है।', cat: 'Email Writing' },
  { en: 'Should you have any questions, please let me know.', hi: 'यदि कोई प्रश्न हो तो कृपया बताएं।', cat: 'Email Writing' },
  { en: 'I am available at your convenience.', hi: 'मैं आपकी सुविधानुसार उपलब्ध हूँ।', cat: 'Email Writing' },
  { en: 'Please treat this matter as urgent.', hi: 'कृपया इस मामले को अत्यावश्यक मानें।', cat: 'Email Writing' },
  { en: 'I would be grateful for your assistance.', hi: 'आपकी सहायता के लिए आभारी रहूंगा।', cat: 'Email Writing' },
  { en: 'Kindly revert at the earliest.', hi: 'कृपया जल्द से जल्द जवाब दें।', cat: 'Email Writing' },
  { en: 'I hereby confirm that...', hi: 'मैं इसके द्वारा पुष्टि करता हूँ कि...', cat: 'Email Writing' },
  { en: 'Please note that...', hi: 'कृपया ध्यान दें कि...', cat: 'Email Writing' },
  { en: 'I am writing to express my concern about...', hi: 'मैं... के बारे में अपनी चिंता व्यक्त करने के लिए लिख रहा हूँ।', cat: 'Email Writing' },
  { en: 'I would like to request...', hi: 'मैं... का अनुरोध करना चाहूंगा।', cat: 'Email Writing' },
  { en: 'Thank you for considering my request.', hi: 'मेरे अनुरोध पर विचार करने के लिए धन्यवाद।', cat: 'Email Writing' },
  { en: 'I am writing to complain about...', hi: 'मैं... के बारे में शिकायत करने के लिए लिख रहा हूँ।', cat: 'Email Writing' },
  { en: 'I demand an immediate explanation.', hi: 'मैं तत्काल स्पष्टीकरण की मांग करता हूँ।', cat: 'Email Writing' },
  { en: 'I expect a full refund.', hi: 'मैं पूर्ण धनवापसी की अपेक्षा करता हूँ।', cat: 'Email Writing' },
  { en: 'I am writing to apply for the position of...', hi: 'मैं... के पद के लिए आवेदन करने के लिए लिख रहा हूँ।', cat: 'Email Writing' },
  { en: 'I believe I am a suitable candidate because...', hi: 'मेरा मानना है कि मैं उपयुक्त उम्मीदवार हूँ क्योंकि...', cat: 'Email Writing' },
  { en: 'I have attached my resume for your review.', hi: 'मैंने आपकी समीक्षा के लिए अपना रिज्यूमे संलग्न किया है।', cat: 'Email Writing' },
  { en: 'I am available for an interview at your convenience.', hi: 'मैं आपकी सुविधानुसार साक्षात्कार के लिए उपलब्ध हूँ।', cat: 'Email Writing' },
  { en: 'Thank you for the opportunity.', hi: 'इस अवसर के लिए धन्यवाद।', cat: 'Email Writing' },
  { en: 'I am writing to resign from my position.', hi: 'मैं अपने पद से इस्तीफा देने के लिए लिख रहा हूँ।', cat: 'Email Writing' },
  { en: 'My last working day will be...', hi: 'मेरा अंतिम कार्य दिवस... होगा।', cat: 'Email Writing' },
  { en: 'I am grateful for the opportunities provided.', hi: 'मैं दिए गए अवसरों के लिए आभारी हूँ।', cat: 'Email Writing' },
  { en: 'I wish the company continued success.', hi: 'मैं कंपनी की निरंतर सफलता की कामना करता हूँ।', cat: 'Email Writing' },
  { en: 'Please accept this as my formal notice.', hi: 'कृपया इसे मेरी औपचारिक सूचना के रूप में स्वीकार करें।', cat: 'Email Writing' },
  { en: 'I am writing to request leave from... to...', hi: 'मैं... से... तक छुट्टी का अनुरोध करने के लिए लिख रहा हूँ।', cat: 'Email Writing' },
  { en: 'The reason for my leave is...', hi: 'मेरी छुट्टी का कारण... है।', cat: 'Email Writing' },
  { en: 'I will ensure all pending work is completed.', hi: 'मैं सुनिश्चित करूंगा कि सभी लंबित काम पूरा हो।', cat: 'Email Writing' },
  { en: 'I will be reachable on my mobile if needed.', hi: 'जरूरत पड़ने पर मैं मोबाइल पर उपलब्ध रहूंगा।', cat: 'Email Writing' },
  { en: 'Thank you for your understanding.', hi: 'आपकी समझ के लिए धन्यवाद।', cat: 'Email Writing' },

  // Telephone Conversations (50)
  { en: 'Hello, this is... speaking.', hi: 'हैलो, मैं... बोल रहा हूँ।', cat: 'Telephone' },
  { en: 'May I speak to Mr./Ms...?', hi: 'क्या मैं श्री/श्रीमती... से बात कर सकता हूँ?', cat: 'Telephone' },
  { en: 'Who is calling, please?', hi: 'कौन बोल रहा है?', cat: 'Telephone' },
  { en: 'May I know who is calling?', hi: 'क्या मैं जान सकता हूँ कौन बोल रहा है?', cat: 'Telephone' },
  { en: 'Please hold the line.', hi: 'कृपया लाइन पर रहें।', cat: 'Telephone' },
  { en: 'I will transfer your call.', hi: 'मैं आपका कॉल ट्रांसफर कर रहा हूँ।', cat: 'Telephone' },
  { en: 'The line is busy. Please hold.', hi: 'लाइन व्यस्त है। कृपया रुकें।', cat: 'Telephone' },
  { en: 'I am sorry, he/she is not available.', hi: 'माफ करें, वह उपलब्ध नहीं हैं।', cat: 'Telephone' },
  { en: 'Would you like to leave a message?', hi: 'क्या आप संदेश छोड़ना चाहेंगे?', cat: 'Telephone' },
  { en: 'Can I take a message?', hi: 'क्या मैं संदेश ले सकता हूँ?', cat: 'Telephone' },
  { en: 'Please ask him/her to call me back.', hi: 'कृपया उन्हें मुझे वापस कॉल करने को कहें।', cat: 'Telephone' },
  { en: 'I will call back later.', hi: 'मैं बाद में कॉल करूंगा।', cat: 'Telephone' },
  { en: 'When would be a good time to call?', hi: 'कॉल करने का अच्छा समय कब होगा?', cat: 'Telephone' },
  { en: 'I am returning your call.', hi: 'मैं आपका कॉल वापस कर रहा हूँ।', cat: 'Telephone' },
  { en: 'Thank you for calling.', hi: 'कॉल करने के लिए धन्यवाद।', cat: 'Telephone' },
  { en: 'I am sorry, I have the wrong number.', hi: 'माफ करें, गलत नंबर लग गया।', cat: 'Telephone' },
  { en: 'Could you speak a little louder?', hi: 'क्या आप थोड़ा जोर से बोल सकते हैं?', cat: 'Telephone' },
  { en: 'I cannot hear you clearly.', hi: 'मुझे आपकी आवाज साफ नहीं आ रही।', cat: 'Telephone' },
  { en: 'The connection is bad.', hi: 'कनेक्शन खराब है।', cat: 'Telephone' },
  { en: 'Can you repeat that, please?', hi: 'क्या आप दोहरा सकते हैं?', cat: 'Telephone' },
  { en: 'Let me spell that for you.', hi: 'मैं आपके लिए स्पेल करता हूँ।', cat: 'Telephone' },
  { en: 'Could you spell your name, please?', hi: 'क्या आप अपना नाम स्पेल कर सकते हैं?', cat: 'Telephone' },
  { en: 'I am calling regarding...', hi: 'मैं... के संबंध में कॉल कर रहा हूँ।', cat: 'Telephone' },
  { en: 'The purpose of my call is...', hi: 'मेरे कॉल का उद्देश्य... है।', cat: 'Telephone' },
  { en: 'I am calling to confirm...', hi: 'मैं... की पुष्टि के लिए कॉल कर रहा हूँ।', cat: 'Telephone' },
  { en: 'I am calling to inquire about...', hi: 'मैं... के बारे में पूछताछ के लिए कॉल कर रहा हूँ।', cat: 'Telephone' },
  { en: 'I am calling to schedule an appointment.', hi: 'मैं अपॉइंटमेंट शेड्यूल करने के लिए कॉल कर रहा हूँ।', cat: 'Telephone' },
  { en: 'I am calling to cancel my appointment.', hi: 'मैं अपनी अपॉइंटमेंट रद्द करने के लिए कॉल कर रहा हूँ।', cat: 'Telephone' },
  { en: 'I am calling to reschedule...', hi: 'मैं... को दोबारा शेड्यूल करने के लिए कॉल कर रहा हूँ।', cat: 'Telephone' },
  { en: 'Is this a good time to talk?', hi: 'क्या यह बात करने का अच्छा समय है?', cat: 'Telephone' },
  { en: 'I am in a meeting right now.', hi: 'मैं अभी मीटिंग में हूँ।', cat: 'Telephone' },
  { en: 'Can I call you back in five minutes?', hi: 'क्या मैं पांच मिनट में वापस कॉल कर सकता हूँ?', cat: 'Telephone' },
  { en: 'I will get back to you shortly.', hi: 'मैं जल्दी आपसे संपर्क करूंगा।', cat: 'Telephone' },
  { en: 'Let me check and get back to you.', hi: 'मुझे जांचने दें और आपको बताता हूँ।', cat: 'Telephone' },
  { en: 'I will send you an email with the details.', hi: 'मैं आपको विवरण के साथ ईमेल भेजूंगा।', cat: 'Telephone' },
  { en: 'Could you send me that in writing?', hi: 'क्या आप मुझे वह लिखित में भेज सकते हैं?', cat: 'Telephone' },
  { en: 'I need to discuss this with my team.', hi: 'मुझे इस पर अपनी टीम से चर्चा करनी होगी।', cat: 'Telephone' },
  { en: 'Let me connect you to the right department.', hi: 'मैं आपको सही विभाग से जोड़ता हूँ।', cat: 'Telephone' },
  { en: 'Please stay on the line.', hi: 'कृपया लाइन पर रहें।', cat: 'Telephone' },
  { en: 'Your call is important to us.', hi: 'आपका कॉल हमारे लिए महत्वपूर्ण है।', cat: 'Telephone' },
  { en: 'For sales, press 1. For support, press 2.', hi: 'बिक्री के लिए 1 दबाएं। सहायता के लिए 2 दबाएं।', cat: 'Telephone' },
  { en: 'Please enter your account number.', hi: 'कृपया अपना खाता नंबर दर्ज करें।', cat: 'Telephone' },
  { en: 'Your call may be recorded for quality purposes.', hi: 'गुणवत्ता के लिए आपका कॉल रिकॉर्ड किया जा सकता है।', cat: 'Telephone' },
  { en: 'Thank you for your patience.', hi: 'आपके धैर्य के लिए धन्यवाद।', cat: 'Telephone' },
  { en: 'Is there anything else I can help you with?', hi: 'क्या कुछ और है जिसमें मैं आपकी मदद कर सकता हूँ?', cat: 'Telephone' },
  { en: 'Have a nice day. Goodbye.', hi: 'आपका दिन शुभ हो। अलविदा।', cat: 'Telephone' },
  { en: 'I appreciate your call.', hi: 'आपके कॉल की सराहना करता हूँ।', cat: 'Telephone' },
  { en: 'Feel free to call anytime.', hi: 'कभी भी कॉल करने में संकोच न करें।', cat: 'Telephone' },
  { en: 'I will make sure he gets your message.', hi: 'मैं सुनिश्चित करूंगा कि उन्हें आपका संदेश मिले।', cat: 'Telephone' },
  { en: 'Thank you for your time.', hi: 'आपके समय के लिए धन्यवाद।', cat: 'Telephone' },
];
