// EVERYDAY SITUATIONS - 200 lessons
export const situationLessons = [
  // At the Doctor (25)
  { en: 'I have been feeling unwell for three days.', hi: 'मुझे तीन दिनों से तबीयत ठीक नहीं है।', cat: 'Doctor' },
  { en: 'I have pain in my chest.', hi: 'मेरे सीने में दर्द है।', cat: 'Doctor' },
  { en: 'I am having difficulty breathing.', hi: 'मुझे सांस लेने में तकलीफ हो रही है।', cat: 'Doctor' },
  { en: 'My blood pressure is high.', hi: 'मेरा ब्लड प्रेशर बढ़ा हुआ है।', cat: 'Doctor' },
  { en: 'I have diabetes.', hi: 'मुझे मधुमेह है।', cat: 'Doctor' },
  { en: 'I am allergic to penicillin.', hi: 'मुझे पेनिसिलिन से एलर्जी है।', cat: 'Doctor' },
  { en: 'How many times should I take this medicine?', hi: 'यह दवाई कितनी बार लेनी है?', cat: 'Doctor' },
  { en: 'Should I take it before or after meals?', hi: 'खाने से पहले लूं या बाद में?', cat: 'Doctor' },
  { en: 'I need a medical certificate.', hi: 'मुझे मेडिकल सर्टिफिकेट चाहिए।', cat: 'Doctor' },
  { en: 'When should I come for a follow-up?', hi: 'फॉलो-अप के लिए कब आऊं?', cat: 'Doctor' },
  { en: 'I have a skin rash.', hi: 'मुझे त्वचा पर चकत्ते हैं।', cat: 'Doctor' },
  { en: 'I have been vomiting since morning.', hi: 'सुबह से उल्टी हो रही है।', cat: 'Doctor' },
  { en: 'I have loose motions.', hi: 'मुझे दस्त हो रहे हैं।', cat: 'Doctor' },
  { en: 'I have constipation.', hi: 'मुझे कब्ज है।', cat: 'Doctor' },
  { en: 'My joints are paining.', hi: 'मेरे जोड़ों में दर्द है।', cat: 'Doctor' },
  { en: 'I have a swelling in my leg.', hi: 'मेरे पैर में सूजन है।', cat: 'Doctor' },
  { en: 'I need to get my eyes checked.', hi: 'मुझे आंखों की जांच करानी है।', cat: 'Doctor' },
  { en: 'I have been having headaches frequently.', hi: 'मुझे बार-बार सिरदर्द हो रहा है।', cat: 'Doctor' },
  { en: 'I cannot sleep at night.', hi: 'मुझे रात को नींद नहीं आती।', cat: 'Doctor' },
  { en: 'I feel anxious all the time.', hi: 'मुझे हर समय चिंता रहती है।', cat: 'Doctor' },
  { en: 'I need a blood test.', hi: 'मुझे खून की जांच करानी है।', cat: 'Doctor' },
  { en: 'When will the reports be ready?', hi: 'रिपोर्ट कब तैयार होगी?', cat: 'Doctor' },
  { en: 'Is this condition serious?', hi: 'क्या यह गंभीर स्थिति है?', cat: 'Doctor' },
  { en: 'What precautions should I take?', hi: 'मुझे क्या सावधानियां बरतनी चाहिए?', cat: 'Doctor' },
  { en: 'I need a prescription for this medicine.', hi: 'मुझे इस दवाई के लिए पर्चा चाहिए।', cat: 'Doctor' },

  // At the Bank (25)
  { en: 'I want to open a savings account.', hi: 'मैं बचत खाता खोलना चाहता हूँ।', cat: 'Bank' },
  { en: 'What documents are required?', hi: 'कौन से दस्तावेज चाहिए?', cat: 'Bank' },
  { en: 'I want to apply for a home loan.', hi: 'मैं होम लोन के लिए आवेदन करना चाहता हूँ।', cat: 'Bank' },
  { en: 'What is the EMI for this loan?', hi: 'इस लोन की EMI क्या होगी?', cat: 'Bank' },
  { en: 'I want to link my Aadhaar to my account.', hi: 'मैं अपना आधार खाते से जोड़ना चाहता हूँ।', cat: 'Bank' },
  { en: 'I need to update my mobile number.', hi: 'मुझे अपना मोबाइल नंबर अपडेट करना है।', cat: 'Bank' },
  { en: 'I want to apply for a credit card.', hi: 'मैं क्रेडिट कार्ड के लिए आवेदन करना चाहता हूँ।', cat: 'Bank' },
  { en: 'What is the credit limit?', hi: 'क्रेडिट लिमिट क्या है?', cat: 'Bank' },
  { en: 'I want to set up a fixed deposit.', hi: 'मैं फिक्स्ड डिपॉजिट करना चाहता हूँ।', cat: 'Bank' },
  { en: 'What is the interest rate for FD?', hi: 'FD पर ब्याज दर क्या है?', cat: 'Bank' },
  { en: 'I want to transfer money to another bank.', hi: 'मैं दूसरे बैंक में पैसे ट्रांसफर करना चाहता हूँ।', cat: 'Bank' },
  { en: 'What are the NEFT charges?', hi: 'NEFT के चार्ज क्या हैं?', cat: 'Bank' },
  { en: 'I want to stop a cheque.', hi: 'मैं चेक रोकना चाहता हूँ।', cat: 'Bank' },
  { en: 'I need a new cheque book.', hi: 'मुझे नई चेक बुक चाहिए।', cat: 'Bank' },
  { en: 'My ATM card is not working.', hi: 'मेरा ATM कार्ड काम नहीं कर रहा।', cat: 'Bank' },
  { en: 'I want to change my ATM PIN.', hi: 'मैं अपना ATM पिन बदलना चाहता हूँ।', cat: 'Bank' },
  { en: 'I want to register for internet banking.', hi: 'मैं इंटरनेट बैंकिंग के लिए रजिस्टर करना चाहता हूँ।', cat: 'Bank' },
  { en: 'I forgot my net banking password.', hi: 'मैं अपना नेट बैंकिंग पासवर्ड भूल गया।', cat: 'Bank' },
  { en: 'I want to add a nominee to my account.', hi: 'मैं अपने खाते में नॉमिनी जोड़ना चाहता हूँ।', cat: 'Bank' },
  { en: 'I want to convert my account to joint account.', hi: 'मैं अपना खाता जॉइंट अकाउंट में बदलना चाहता हूँ।', cat: 'Bank' },
  { en: 'What is the minimum balance requirement?', hi: 'न्यूनतम बैलेंस कितना रखना है?', cat: 'Bank' },
  { en: 'I want to close my account.', hi: 'मैं अपना खाता बंद करना चाहता हूँ।', cat: 'Bank' },
  { en: 'I need a bank statement for visa.', hi: 'मुझे वीजा के लिए बैंक स्टेटमेंट चाहिए।', cat: 'Bank' },
  { en: 'I want to start a SIP.', hi: 'मैं SIP शुरू करना चाहता हूँ।', cat: 'Bank' },
  { en: 'I want to invest in mutual funds.', hi: 'मैं म्यूचुअल फंड में निवेश करना चाहता हूँ।', cat: 'Bank' },

  // At the Restaurant (25)
  { en: 'A table for four, please.', hi: 'चार लोगों के लिए टेबल चाहिए।', cat: 'Restaurant' },
  { en: 'Do you have a reservation?', hi: 'क्या आपका आरक्षण है?', cat: 'Restaurant' },
  { en: 'Can we sit near the window?', hi: 'क्या हम खिड़की के पास बैठ सकते हैं?', cat: 'Restaurant' },
  { en: 'What are today\'s specials?', hi: 'आज के स्पेशल क्या हैं?', cat: 'Restaurant' },
  { en: 'I would like to order now.', hi: 'मैं अभी ऑर्डर करना चाहूंगा।', cat: 'Restaurant' },
  { en: 'What do you recommend?', hi: 'आप क्या सुझाव देंगे?', cat: 'Restaurant' },
  { en: 'Is this dish spicy?', hi: 'क्या यह डिश तीखी है?', cat: 'Restaurant' },
  { en: 'Can you make it less spicy?', hi: 'क्या आप इसे कम तीखा बना सकते हैं?', cat: 'Restaurant' },
  { en: 'I am allergic to nuts.', hi: 'मुझे मेवों से एलर्जी है।', cat: 'Restaurant' },
  { en: 'Does this contain gluten?', hi: 'क्या इसमें ग्लूटेन है?', cat: 'Restaurant' },
  { en: 'Can I have the vegetarian menu?', hi: 'क्या मुझे शाकाहारी मेन्यू मिल सकता है?', cat: 'Restaurant' },
  { en: 'I would like my steak well done.', hi: 'मुझे स्टेक अच्छी तरह पका हुआ चाहिए।', cat: 'Restaurant' },
  { en: 'Can I have some extra sauce?', hi: 'क्या मुझे थोड़ी और सॉस मिल सकती है?', cat: 'Restaurant' },
  { en: 'This is not what I ordered.', hi: 'यह वो नहीं है जो मैंने ऑर्डर किया था।', cat: 'Restaurant' },
  { en: 'The food is taking too long.', hi: 'खाने में बहुत देर हो रही है।', cat: 'Restaurant' },
  { en: 'Can you heat this up please?', hi: 'क्या आप इसे गर्म कर सकते हैं?', cat: 'Restaurant' },
  { en: 'Can I have the dessert menu?', hi: 'क्या मुझे मिठाई का मेन्यू मिल सकता है?', cat: 'Restaurant' },
  { en: 'I would like to pay separately.', hi: 'मैं अलग से भुगतान करना चाहूंगा।', cat: 'Restaurant' },
  { en: 'Can we split the bill?', hi: 'क्या हम बिल बांट सकते हैं?', cat: 'Restaurant' },
  { en: 'Is service charge included?', hi: 'क्या सर्विस चार्ज शामिल है?', cat: 'Restaurant' },
  { en: 'Can I have a receipt please?', hi: 'क्या मुझे रसीद मिल सकती है?', cat: 'Restaurant' },
  { en: 'The food was excellent.', hi: 'खाना बहुत बढ़िया था।', cat: 'Restaurant' },
  { en: 'I would like to make a complaint.', hi: 'मैं शिकायत करना चाहूंगा।', cat: 'Restaurant' },
  { en: 'Can I speak to the manager?', hi: 'क्या मैं मैनेजर से बात कर सकता हूँ?', cat: 'Restaurant' },
  { en: 'Can you pack this to go?', hi: 'क्या आप इसे पैक कर सकते हैं?', cat: 'Restaurant' },

  // At the Airport (25)
  { en: 'Where is the check-in counter?', hi: 'चेक-इन काउंटर कहाँ है?', cat: 'Airport' },
  { en: 'I would like a window seat.', hi: 'मुझे खिड़की वाली सीट चाहिए।', cat: 'Airport' },
  { en: 'I would like an aisle seat.', hi: 'मुझे गलियारे वाली सीट चाहिए।', cat: 'Airport' },
  { en: 'How much baggage is allowed?', hi: 'कितना सामान ले जा सकते हैं?', cat: 'Airport' },
  { en: 'My luggage is overweight.', hi: 'मेरा सामान ज्यादा वजन का है।', cat: 'Airport' },
  { en: 'Where is the boarding gate?', hi: 'बोर्डिंग गेट कहाँ है?', cat: 'Airport' },
  { en: 'What time does boarding start?', hi: 'बोर्डिंग कितने बजे शुरू होगी?', cat: 'Airport' },
  { en: 'Is the flight on time?', hi: 'क्या फ्लाइट समय पर है?', cat: 'Airport' },
  { en: 'The flight has been delayed.', hi: 'फ्लाइट में देरी हो गई है।', cat: 'Airport' },
  { en: 'The flight has been cancelled.', hi: 'फ्लाइट रद्द हो गई है।', cat: 'Airport' },
  { en: 'I missed my connecting flight.', hi: 'मेरी कनेक्टिंग फ्लाइट छूट गई।', cat: 'Airport' },
  { en: 'Where is the baggage claim?', hi: 'सामान कहाँ मिलेगा?', cat: 'Airport' },
  { en: 'My luggage is missing.', hi: 'मेरा सामान गायब है।', cat: 'Airport' },
  { en: 'I need to file a complaint.', hi: 'मुझे शिकायत दर्ज करनी है।', cat: 'Airport' },
  { en: 'Where is the currency exchange?', hi: 'करेंसी एक्सचेंज कहाँ है?', cat: 'Airport' },
  { en: 'Where can I get a taxi?', hi: 'टैक्सी कहाँ मिलेगी?', cat: 'Airport' },
  { en: 'Is there a bus to the city center?', hi: 'क्या शहर के केंद्र के लिए बस है?', cat: 'Airport' },
  { en: 'I need to declare these items.', hi: 'मुझे इन चीजों की घोषणा करनी है।', cat: 'Airport' },
  { en: 'Do I need a visa for transit?', hi: 'क्या ट्रांजिट के लिए वीजा चाहिए?', cat: 'Airport' },
  { en: 'Where is the immigration counter?', hi: 'इमिग्रेशन काउंटर कहाँ है?', cat: 'Airport' },
  { en: 'Here is my passport and visa.', hi: 'यह रहा मेरा पासपोर्ट और वीजा।', cat: 'Airport' },
  { en: 'What is the purpose of your visit?', hi: 'आपकी यात्रा का उद्देश्य क्या है?', cat: 'Airport' },
  { en: 'I am here for business.', hi: 'मैं व्यापार के लिए आया हूँ।', cat: 'Airport' },
  { en: 'I am here for tourism.', hi: 'मैं पर्यटन के लिए आया हूँ।', cat: 'Airport' },
  { en: 'How long will you stay?', hi: 'आप कितने दिन रहेंगे?', cat: 'Airport' },

  // At the Police Station (20)
  { en: 'I want to file an FIR.', hi: 'मैं FIR दर्ज करना चाहता हूँ।', cat: 'Police' },
  { en: 'My wallet has been stolen.', hi: 'मेरा बटुआ चोरी हो गया।', cat: 'Police' },
  { en: 'I lost my passport.', hi: 'मेरा पासपोर्ट खो गया।', cat: 'Police' },
  { en: 'I was robbed on the street.', hi: 'सड़क पर मेरी लूट हो गई।', cat: 'Police' },
  { en: 'Someone broke into my house.', hi: 'किसी ने मेरे घर में सेंध लगाई।', cat: 'Police' },
  { en: 'I want to report a crime.', hi: 'मैं अपराध की रिपोर्ट करना चाहता हूँ।', cat: 'Police' },
  { en: 'I need a copy of the FIR.', hi: 'मुझे FIR की कॉपी चाहिए।', cat: 'Police' },
  { en: 'I am a witness to an accident.', hi: 'मैं एक दुर्घटना का गवाह हूँ।', cat: 'Police' },
  { en: 'I want to report a missing person.', hi: 'मैं लापता व्यक्ति की रिपोर्ट करना चाहता हूँ।', cat: 'Police' },
  { en: 'I need police verification.', hi: 'मुझे पुलिस वेरिफिकेशन चाहिए।', cat: 'Police' },
  { en: 'I want to file a complaint against someone.', hi: 'मैं किसी के खिलाफ शिकायत दर्ज करना चाहता हूँ।', cat: 'Police' },
  { en: 'I am being harassed.', hi: 'मुझे परेशान किया जा रहा है।', cat: 'Police' },
  { en: 'I received threatening calls.', hi: 'मुझे धमकी भरे फोन आए।', cat: 'Police' },
  { en: 'There was a road accident.', hi: 'सड़क दुर्घटना हुई थी।', cat: 'Police' },
  { en: 'I need an NOC from police.', hi: 'मुझे पुलिस से NOC चाहिए।', cat: 'Police' },
  { en: 'What is the status of my complaint?', hi: 'मेरी शिकायत की स्थिति क्या है?', cat: 'Police' },
  { en: 'I want to withdraw my complaint.', hi: 'मैं अपनी शिकायत वापस लेना चाहता हूँ।', cat: 'Police' },
  { en: 'I need a character certificate.', hi: 'मुझे चरित्र प्रमाण पत्र चाहिए।', cat: 'Police' },
  { en: 'Where is the nearest police station?', hi: 'सबसे नजदीकी थाना कहाँ है?', cat: 'Police' },
  { en: 'I want to speak to the SHO.', hi: 'मैं SHO से बात करना चाहता हूँ।', cat: 'Police' },

  // At the Post Office (15)
  { en: 'I want to send this parcel.', hi: 'मैं यह पार्सल भेजना चाहता हूँ।', cat: 'Post Office' },
  { en: 'How much is the postage?', hi: 'डाक खर्च कितना है?', cat: 'Post Office' },
  { en: 'I want to send it by speed post.', hi: 'मैं इसे स्पीड पोस्ट से भेजना चाहता हूँ।', cat: 'Post Office' },
  { en: 'I want to send a registered letter.', hi: 'मैं रजिस्टर्ड पत्र भेजना चाहता हूँ।', cat: 'Post Office' },
  { en: 'How long will it take to reach?', hi: 'पहुंचने में कितना समय लगेगा?', cat: 'Post Office' },
  { en: 'I want to track my parcel.', hi: 'मैं अपना पार्सल ट्रैक करना चाहता हूँ।', cat: 'Post Office' },
  { en: 'I need stamps for this letter.', hi: 'मुझे इस पत्र के लिए टिकट चाहिए।', cat: 'Post Office' },
  { en: 'Where is the post box?', hi: 'पोस्ट बॉक्स कहाँ है?', cat: 'Post Office' },
  { en: 'I want to open a post office account.', hi: 'मैं पोस्ट ऑफिस खाता खोलना चाहता हूँ।', cat: 'Post Office' },
  { en: 'I want to collect my parcel.', hi: 'मैं अपना पार्सल लेना चाहता हूँ।', cat: 'Post Office' },
  { en: 'I have a delivery notice.', hi: 'मेरे पास डिलीवरी नोटिस है।', cat: 'Post Office' },
  { en: 'I want to send money order.', hi: 'मैं मनी ऑर्डर भेजना चाहता हूँ।', cat: 'Post Office' },
  { en: 'What is the PIN code for this area?', hi: 'इस क्षेत्र का पिन कोड क्या है?', cat: 'Post Office' },
  { en: 'I want to redirect my mail.', hi: 'मैं अपना मेल दूसरे पते पर भेजना चाहता हूँ।', cat: 'Post Office' },
  { en: 'I want to insure this parcel.', hi: 'मैं इस पार्सल का बीमा करना चाहता हूँ।', cat: 'Post Office' },

  // At the Government Office (20)
  { en: 'I want to apply for a passport.', hi: 'मैं पासपोर्ट के लिए आवेदन करना चाहता हूँ।', cat: 'Government' },
  { en: 'I need to renew my driving license.', hi: 'मुझे अपना ड्राइविंग लाइसेंस रिन्यू करना है।', cat: 'Government' },
  { en: 'I want to apply for a PAN card.', hi: 'मैं पैन कार्ड के लिए आवेदन करना चाहता हूँ।', cat: 'Government' },
  { en: 'I need to update my Aadhaar card.', hi: 'मुझे अपना आधार कार्ड अपडेट करना है।', cat: 'Government' },
  { en: 'Where can I get the form?', hi: 'फॉर्म कहाँ मिलेगा?', cat: 'Government' },
  { en: 'What documents do I need?', hi: 'मुझे कौन से दस्तावेज चाहिए?', cat: 'Government' },
  { en: 'I want to file my income tax return.', hi: 'मैं अपना इनकम टैक्स रिटर्न फाइल करना चाहता हूँ।', cat: 'Government' },
  { en: 'I need a birth certificate.', hi: 'मुझे जन्म प्रमाण पत्र चाहिए।', cat: 'Government' },
  { en: 'I need a death certificate.', hi: 'मुझे मृत्यु प्रमाण पत्र चाहिए।', cat: 'Government' },
  { en: 'I want to register my marriage.', hi: 'मैं अपनी शादी का पंजीकरण करना चाहता हूँ।', cat: 'Government' },
  { en: 'I need a domicile certificate.', hi: 'मुझे निवास प्रमाण पत्र चाहिए।', cat: 'Government' },
  { en: 'I need a caste certificate.', hi: 'मुझे जाति प्रमाण पत्र चाहिए।', cat: 'Government' },
  { en: 'I need an income certificate.', hi: 'मुझे आय प्रमाण पत्र चाहिए।', cat: 'Government' },
  { en: 'What is the processing time?', hi: 'प्रोसेसिंग में कितना समय लगेगा?', cat: 'Government' },
  { en: 'What is the fee for this service?', hi: 'इस सेवा की फीस क्या है?', cat: 'Government' },
  { en: 'I want to check my application status.', hi: 'मैं अपने आवेदन की स्थिति जानना चाहता हूँ।', cat: 'Government' },
  { en: 'I want to file an RTI.', hi: 'मैं RTI दायर करना चाहता हूँ।', cat: 'Government' },
  { en: 'I want to register a property.', hi: 'मैं संपत्ति का पंजीकरण करना चाहता हूँ।', cat: 'Government' },
  { en: 'I need a no objection certificate.', hi: 'मुझे अनापत्ति प्रमाण पत्र चाहिए।', cat: 'Government' },
  { en: 'Where is the help desk?', hi: 'हेल्प डेस्क कहाँ है?', cat: 'Government' },

  // Job Interview (25)
  { en: 'Tell me about yourself.', hi: 'अपने बारे में बताइए।', cat: 'Interview' },
  { en: 'Why do you want this job?', hi: 'आप यह नौकरी क्यों चाहते हैं?', cat: 'Interview' },
  { en: 'What are your strengths?', hi: 'आपकी ताकत क्या है?', cat: 'Interview' },
  { en: 'What are your weaknesses?', hi: 'आपकी कमजोरियां क्या हैं?', cat: 'Interview' },
  { en: 'Where do you see yourself in five years?', hi: 'पांच साल में आप खुद को कहाँ देखते हैं?', cat: 'Interview' },
  { en: 'Why should we hire you?', hi: 'हम आपको क्यों नियुक्त करें?', cat: 'Interview' },
  { en: 'What is your expected salary?', hi: 'आपकी अपेक्षित सैलरी क्या है?', cat: 'Interview' },
  { en: 'Why did you leave your last job?', hi: 'आपने अपनी पिछली नौकरी क्यों छोड़ी?', cat: 'Interview' },
  { en: 'What do you know about our company?', hi: 'आप हमारी कंपनी के बारे में क्या जानते हैं?', cat: 'Interview' },
  { en: 'Do you have any questions for us?', hi: 'क्या आपके कोई सवाल हैं?', cat: 'Interview' },
  { en: 'I have five years of experience.', hi: 'मुझे पांच साल का अनुभव है।', cat: 'Interview' },
  { en: 'I am a quick learner.', hi: 'मैं जल्दी सीखता हूँ।', cat: 'Interview' },
  { en: 'I work well under pressure.', hi: 'मैं दबाव में अच्छा काम करता हूँ।', cat: 'Interview' },
  { en: 'I am a team player.', hi: 'मैं टीम के साथ अच्छा काम करता हूँ।', cat: 'Interview' },
  { en: 'I am passionate about this field.', hi: 'मुझे इस क्षेत्र में बहुत रुचि है।', cat: 'Interview' },
  { en: 'I can start immediately.', hi: 'मैं तुरंत शुरू कर सकता हूँ।', cat: 'Interview' },
  { en: 'I need a notice period of one month.', hi: 'मुझे एक महीने का नोटिस पीरियड चाहिए।', cat: 'Interview' },
  { en: 'I am willing to relocate.', hi: 'मैं स्थानांतरण के लिए तैयार हूँ।', cat: 'Interview' },
  { en: 'I am flexible with working hours.', hi: 'मैं काम के घंटों में लचीला हूँ।', cat: 'Interview' },
  { en: 'I have handled similar projects before.', hi: 'मैंने पहले भी ऐसे प्रोजेक्ट संभाले हैं।', cat: 'Interview' },
  { en: 'I achieved my targets consistently.', hi: 'मैंने लगातार अपने लक्ष्य हासिल किए।', cat: 'Interview' },
  { en: 'I led a team of ten people.', hi: 'मैंने दस लोगों की टीम का नेतृत्व किया।', cat: 'Interview' },
  { en: 'I am proficient in Excel and PowerPoint.', hi: 'मैं Excel और PowerPoint में कुशल हूँ।', cat: 'Interview' },
  { en: 'When can I expect to hear from you?', hi: 'मुझे आपसे कब जवाब मिलेगा?', cat: 'Interview' },
  { en: 'Thank you for this opportunity.', hi: 'इस अवसर के लिए धन्यवाद।', cat: 'Interview' },

  // Real Estate (20)
  { en: 'I am looking for a flat to rent.', hi: 'मैं किराए पर फ्लैट ढूंढ रहा हूँ।', cat: 'Real Estate' },
  { en: 'I want to buy a house.', hi: 'मैं घर खरीदना चाहता हूँ।', cat: 'Real Estate' },
  { en: 'What is the rent per month?', hi: 'महीने का किराया कितना है?', cat: 'Real Estate' },
  { en: 'Is the security deposit refundable?', hi: 'क्या सिक्योरिटी डिपॉजिट वापस मिलेगा?', cat: 'Real Estate' },
  { en: 'How many bedrooms does it have?', hi: 'इसमें कितने बेडरूम हैं?', cat: 'Real Estate' },
  { en: 'Is it fully furnished?', hi: 'क्या यह पूरी तरह फर्निश्ड है?', cat: 'Real Estate' },
  { en: 'Is parking available?', hi: 'क्या पार्किंग उपलब्ध है?', cat: 'Real Estate' },
  { en: 'What is the carpet area?', hi: 'कार्पेट एरिया कितना है?', cat: 'Real Estate' },
  { en: 'Is it on a main road?', hi: 'क्या यह मुख्य सड़क पर है?', cat: 'Real Estate' },
  { en: 'What floor is it on?', hi: 'यह किस मंजिल पर है?', cat: 'Real Estate' },
  { en: 'Is there a lift?', hi: 'क्या लिफ्ट है?', cat: 'Real Estate' },
  { en: 'Is water supply available 24 hours?', hi: 'क्या 24 घंटे पानी आता है?', cat: 'Real Estate' },
  { en: 'What is the maintenance charge?', hi: 'मेंटेनेंस चार्ज कितना है?', cat: 'Real Estate' },
  { en: 'Is the society gated?', hi: 'क्या सोसाइटी गेटेड है?', cat: 'Real Estate' },
  { en: 'Are pets allowed?', hi: 'क्या पालतू जानवर रख सकते हैं?', cat: 'Real Estate' },
  { en: 'Can I see the property?', hi: 'क्या मैं प्रॉपर्टी देख सकता हूँ?', cat: 'Real Estate' },
  { en: 'I want to negotiate the price.', hi: 'मैं कीमत पर बातचीत करना चाहता हूँ।', cat: 'Real Estate' },
  { en: 'What is the registration cost?', hi: 'रजिस्ट्रेशन खर्च कितना है?', cat: 'Real Estate' },
  { en: 'Is the property ready to move in?', hi: 'क्या प्रॉपर्टी रहने के लिए तैयार है?', cat: 'Real Estate' },
  { en: 'I need to check the documents.', hi: 'मुझे दस्तावेज देखने हैं।', cat: 'Real Estate' },

  // Education (20)
  { en: 'I want to enroll my child in this school.', hi: 'मैं अपने बच्चे का इस स्कूल में दाखिला कराना चाहता हूँ।', cat: 'Education' },
  { en: 'What is the admission process?', hi: 'दाखिले की प्रक्रिया क्या है?', cat: 'Education' },
  { en: 'What is the fee structure?', hi: 'फीस स्ट्रक्चर क्या है?', cat: 'Education' },
  { en: 'Is there a scholarship available?', hi: 'क्या छात्रवृत्ति उपलब्ध है?', cat: 'Education' },
  { en: 'What is the last date for admission?', hi: 'दाखिले की अंतिम तिथि क्या है?', cat: 'Education' },
  { en: 'I want to apply for a course.', hi: 'मैं एक कोर्स के लिए आवेदन करना चाहता हूँ।', cat: 'Education' },
  { en: 'What are the eligibility criteria?', hi: 'पात्रता मानदंड क्या हैं?', cat: 'Education' },
  { en: 'Is there an entrance exam?', hi: 'क्या प्रवेश परीक्षा है?', cat: 'Education' },
  { en: 'When are the exams scheduled?', hi: 'परीक्षाएं कब होंगी?', cat: 'Education' },
  { en: 'I need the syllabus.', hi: 'मुझे पाठ्यक्रम चाहिए।', cat: 'Education' },
  { en: 'I want to meet the principal.', hi: 'मैं प्रिंसिपल से मिलना चाहता हूँ।', cat: 'Education' },
  { en: 'My child is absent due to illness.', hi: 'मेरा बच्चा बीमारी के कारण अनुपस्थित है।', cat: 'Education' },
  { en: 'I want to see the report card.', hi: 'मैं रिपोर्ट कार्ड देखना चाहता हूँ।', cat: 'Education' },
  { en: 'When is the parent-teacher meeting?', hi: 'पैरेंट-टीचर मीटिंग कब है?', cat: 'Education' },
  { en: 'I want to apply for a transfer certificate.', hi: 'मैं ट्रांसफर सर्टिफिकेट के लिए आवेदन करना चाहता हूँ।', cat: 'Education' },
  { en: 'What extracurricular activities are available?', hi: 'कौन सी अतिरिक्त गतिविधियां उपलब्ध हैं?', cat: 'Education' },
  { en: 'Is there a school bus service?', hi: 'क्या स्कूल बस सेवा है?', cat: 'Education' },
  { en: 'What is the school timing?', hi: 'स्कूल का समय क्या है?', cat: 'Education' },
  { en: 'I want to pay the fees online.', hi: 'मैं फीस ऑनलाइन भरना चाहता हूँ।', cat: 'Education' },
  { en: 'I need a bonafide certificate.', hi: 'मुझे बोनाफाइड सर्टिफिकेट चाहिए।', cat: 'Education' },
];
