// MORE DAILY LIFE LESSONS - 300 lessons
export const dailyLessons2 = [
  // At the Gym (20)
  { en: 'I want to join this gym.', hi: 'मैं इस जिम में शामिल होना चाहता हूँ।', cat: 'Gym' },
  { en: 'What is the monthly membership fee?', hi: 'मासिक सदस्यता शुल्क क्या है?', cat: 'Gym' },
  { en: 'Do you have a personal trainer?', hi: 'क्या आपके पास पर्सनल ट्रेनर है?', cat: 'Gym' },
  { en: 'What are the gym timings?', hi: 'जिम का समय क्या है?', cat: 'Gym' },
  { en: 'Where is the changing room?', hi: 'चेंजिंग रूम कहाँ है?', cat: 'Gym' },
  { en: 'Can I get a locker?', hi: 'क्या मुझे लॉकर मिल सकता है?', cat: 'Gym' },
  { en: 'I want to lose weight.', hi: 'मैं वजन कम करना चाहता हूँ।', cat: 'Gym' },
  { en: 'I want to build muscle.', hi: 'मैं मांसपेशियां बनाना चाहता हूँ।', cat: 'Gym' },
  { en: 'How do I use this machine?', hi: 'यह मशीन कैसे इस्तेमाल करें?', cat: 'Gym' },
  { en: 'Can you show me the correct form?', hi: 'क्या आप मुझे सही तरीका दिखा सकते हैं?', cat: 'Gym' },
  { en: 'I need to warm up first.', hi: 'मुझे पहले वार्म अप करना है।', cat: 'Gym' },
  { en: 'I pulled a muscle.', hi: 'मेरी मांसपेशी खिंच गई।', cat: 'Gym' },
  { en: 'Do you have yoga classes?', hi: 'क्या आपके पास योग कक्षाएं हैं?', cat: 'Gym' },
  { en: 'When is the aerobics class?', hi: 'एरोबिक्स क्लास कब है?', cat: 'Gym' },
  { en: 'I need to stretch after workout.', hi: 'वर्कआउट के बाद मुझे स्ट्रेच करना है।', cat: 'Gym' },
  { en: 'Can I freeze my membership?', hi: 'क्या मैं अपनी सदस्यता रोक सकता हूँ?', cat: 'Gym' },
  { en: 'I want to cancel my membership.', hi: 'मैं अपनी सदस्यता रद्द करना चाहता हूँ।', cat: 'Gym' },
  { en: 'Is there a swimming pool?', hi: 'क्या स्विमिंग पूल है?', cat: 'Gym' },
  { en: 'Do you provide towels?', hi: 'क्या आप तौलिए देते हैं?', cat: 'Gym' },
  { en: 'Where can I get a protein shake?', hi: 'प्रोटीन शेक कहाँ मिलेगा?', cat: 'Gym' },

  // At the Salon/Barber (20)
  { en: 'I want a haircut.', hi: 'मुझे बाल कटवाने हैं।', cat: 'Salon' },
  { en: 'Just a trim, please.', hi: 'बस थोड़ा छोटा कर दें।', cat: 'Salon' },
  { en: 'I want to change my hairstyle.', hi: 'मैं अपना हेयरस्टाइल बदलना चाहता हूँ।', cat: 'Salon' },
  { en: 'Please cut it short.', hi: 'कृपया छोटा काट दें।', cat: 'Salon' },
  { en: 'Do not cut it too short.', hi: 'बहुत छोटा मत काटिए।', cat: 'Salon' },
  { en: 'I want to color my hair.', hi: 'मैं बाल रंगवाना चाहता हूँ।', cat: 'Salon' },
  { en: 'What colors do you have?', hi: 'आपके पास कौन से रंग हैं?', cat: 'Salon' },
  { en: 'I want highlights.', hi: 'मुझे हाइलाइट्स चाहिए।', cat: 'Salon' },
  { en: 'I want a shave.', hi: 'मुझे शेव करवानी है।', cat: 'Salon' },
  { en: 'Please trim my beard.', hi: 'कृपया मेरी दाढ़ी छोटी कर दें।', cat: 'Salon' },
  { en: 'I want a facial.', hi: 'मुझे फेशियल करवाना है।', cat: 'Salon' },
  { en: 'I want a head massage.', hi: 'मुझे सिर की मालिश चाहिए।', cat: 'Salon' },
  { en: 'How long will it take?', hi: 'कितना समय लगेगा?', cat: 'Salon' },
  { en: 'Do I need an appointment?', hi: 'क्या मुझे अपॉइंटमेंट चाहिए?', cat: 'Salon' },
  { en: 'I have an appointment at 3.', hi: 'मेरी 3 बजे अपॉइंटमेंट है।', cat: 'Salon' },
  { en: 'The water is too hot.', hi: 'पानी बहुत गर्म है।', cat: 'Salon' },
  { en: 'This looks perfect.', hi: 'यह बिल्कुल सही है।', cat: 'Salon' },
  { en: 'I do not like this style.', hi: 'मुझे यह स्टाइल पसंद नहीं।', cat: 'Salon' },
  { en: 'Can you fix this?', hi: 'क्या आप इसे ठीक कर सकते हैं?', cat: 'Salon' },
  { en: 'How much do I owe you?', hi: 'मुझे कितना देना है?', cat: 'Salon' },

  // At the Mechanic (20)
  { en: 'My car is not starting.', hi: 'मेरी गाड़ी स्टार्ट नहीं हो रही।', cat: 'Mechanic' },
  { en: 'The engine is making a strange noise.', hi: 'इंजन से अजीब आवाज आ रही है।', cat: 'Mechanic' },
  { en: 'I have a flat tire.', hi: 'मेरा टायर पंक्चर हो गया।', cat: 'Mechanic' },
  { en: 'The brakes are not working properly.', hi: 'ब्रेक ठीक से काम नहीं कर रहे।', cat: 'Mechanic' },
  { en: 'I need an oil change.', hi: 'मुझे ऑयल बदलवाना है।', cat: 'Mechanic' },
  { en: 'The battery is dead.', hi: 'बैटरी खत्म हो गई है।', cat: 'Mechanic' },
  { en: 'The AC is not cooling.', hi: 'AC ठंडा नहीं कर रहा।', cat: 'Mechanic' },
  { en: 'There is a leak somewhere.', hi: 'कहीं से लीक हो रहा है।', cat: 'Mechanic' },
  { en: 'The headlights are not working.', hi: 'हेडलाइट्स काम नहीं कर रही।', cat: 'Mechanic' },
  { en: 'I need new wipers.', hi: 'मुझे नए वाइपर चाहिए।', cat: 'Mechanic' },
  { en: 'How much will the repair cost?', hi: 'मरम्मत में कितना खर्च आएगा?', cat: 'Mechanic' },
  { en: 'How long will it take to fix?', hi: 'ठीक करने में कितना समय लगेगा?', cat: 'Mechanic' },
  { en: 'Can you give me a written estimate?', hi: 'क्या आप लिखित अनुमान दे सकते हैं?', cat: 'Mechanic' },
  { en: 'Is it safe to drive?', hi: 'क्या गाड़ी चलाना सुरक्षित है?', cat: 'Mechanic' },
  { en: 'I need a tow truck.', hi: 'मुझे टो ट्रक चाहिए।', cat: 'Mechanic' },
  { en: 'The car is overheating.', hi: 'गाड़ी ज्यादा गर्म हो रही है।', cat: 'Mechanic' },
  { en: 'I need to get the car serviced.', hi: 'मुझे गाड़ी की सर्विस करवानी है।', cat: 'Mechanic' },
  { en: 'When will the car be ready?', hi: 'गाड़ी कब तैयार होगी?', cat: 'Mechanic' },
  { en: 'Can I get a loaner car?', hi: 'क्या मुझे अस्थायी गाड़ी मिल सकती है?', cat: 'Mechanic' },
  { en: 'Please check the tire pressure.', hi: 'कृपया टायर का प्रेशर चेक करें।', cat: 'Mechanic' },

  // At the Tailor (15)
  { en: 'I want to get this stitched.', hi: 'मुझे यह सिलवाना है।', cat: 'Tailor' },
  { en: 'Can you take my measurements?', hi: 'क्या आप मेरा नाप ले सकते हैं?', cat: 'Tailor' },
  { en: 'I want a suit made.', hi: 'मुझे सूट बनवाना है।', cat: 'Tailor' },
  { en: 'This is too tight.', hi: 'यह बहुत टाइट है।', cat: 'Tailor' },
  { en: 'This is too loose.', hi: 'यह बहुत ढीला है।', cat: 'Tailor' },
  { en: 'Can you alter this?', hi: 'क्या आप इसमें फेरबदल कर सकते हैं?', cat: 'Tailor' },
  { en: 'Please shorten the sleeves.', hi: 'कृपया आस्तीन छोटी कर दें।', cat: 'Tailor' },
  { en: 'Please lengthen the pants.', hi: 'कृपया पैंट लंबी कर दें।', cat: 'Tailor' },
  { en: 'The fitting is not right.', hi: 'फिटिंग सही नहीं है।', cat: 'Tailor' },
  { en: 'When will it be ready?', hi: 'यह कब तैयार होगा?', cat: 'Tailor' },
  { en: 'I need it urgently.', hi: 'मुझे जल्दी चाहिए।', cat: 'Tailor' },
  { en: 'Can you add a pocket?', hi: 'क्या आप जेब लगा सकते हैं?', cat: 'Tailor' },
  { en: 'I want this style.', hi: 'मुझे यह स्टाइल चाहिए।', cat: 'Tailor' },
  { en: 'Please use this fabric.', hi: 'कृपया यह कपड़ा इस्तेमाल करें।', cat: 'Tailor' },
  { en: 'How much will you charge?', hi: 'आप कितना लेंगे?', cat: 'Tailor' },

  // At the Laundry (15)
  { en: 'I want to get these clothes washed.', hi: 'मुझे ये कपड़े धुलवाने हैं।', cat: 'Laundry' },
  { en: 'I need dry cleaning.', hi: 'मुझे ड्राई क्लीनिंग चाहिए।', cat: 'Laundry' },
  { en: 'Please iron these clothes.', hi: 'कृपया इन कपड़ों को प्रेस करें।', cat: 'Laundry' },
  { en: 'This stain is not coming out.', hi: 'यह दाग नहीं जा रहा।', cat: 'Laundry' },
  { en: 'Please be careful with this.', hi: 'कृपया इसके साथ सावधान रहें।', cat: 'Laundry' },
  { en: 'This is delicate fabric.', hi: 'यह नाजुक कपड़ा है।', cat: 'Laundry' },
  { en: 'When can I pick this up?', hi: 'मैं इसे कब ले सकता हूँ?', cat: 'Laundry' },
  { en: 'Do you have express service?', hi: 'क्या आपके पास एक्सप्रेस सेवा है?', cat: 'Laundry' },
  { en: 'This is not my shirt.', hi: 'यह मेरी शर्ट नहीं है।', cat: 'Laundry' },
  { en: 'You have damaged my clothes.', hi: 'आपने मेरे कपड़े खराब कर दिए।', cat: 'Laundry' },
  { en: 'The color has faded.', hi: 'रंग उड़ गया है।', cat: 'Laundry' },
  { en: 'This has shrunk.', hi: 'यह सिकुड़ गया है।', cat: 'Laundry' },
  { en: 'I want a refund.', hi: 'मुझे पैसे वापस चाहिए।', cat: 'Laundry' },
  { en: 'Please fold the clothes.', hi: 'कृपया कपड़े तह करें।', cat: 'Laundry' },
  { en: 'Do you deliver?', hi: 'क्या आप डिलीवरी करते हैं?', cat: 'Laundry' },

  // At the Pharmacy (15)
  { en: 'I need medicine for cold.', hi: 'मुझे सर्दी की दवाई चाहिए।', cat: 'Pharmacy' },
  { en: 'Do you have this medicine?', hi: 'क्या आपके पास यह दवाई है?', cat: 'Pharmacy' },
  { en: 'I have a prescription.', hi: 'मेरे पास पर्चा है।', cat: 'Pharmacy' },
  { en: 'Is this available without prescription?', hi: 'क्या यह बिना पर्चे के मिलती है?', cat: 'Pharmacy' },
  { en: 'What is the dosage?', hi: 'खुराक क्या है?', cat: 'Pharmacy' },
  { en: 'Are there any side effects?', hi: 'क्या कोई साइड इफेक्ट हैं?', cat: 'Pharmacy' },
  { en: 'I need pain killers.', hi: 'मुझे दर्द की दवाई चाहिए।', cat: 'Pharmacy' },
  { en: 'I need bandages.', hi: 'मुझे पट्टी चाहिए।', cat: 'Pharmacy' },
  { en: 'Do you have a generic version?', hi: 'क्या आपके पास जेनेरिक वर्जन है?', cat: 'Pharmacy' },
  { en: 'This medicine is out of stock.', hi: 'यह दवाई स्टॉक में नहीं है।', cat: 'Pharmacy' },
  { en: 'When will it be available?', hi: 'यह कब उपलब्ध होगी?', cat: 'Pharmacy' },
  { en: 'I need a first aid kit.', hi: 'मुझे फर्स्ट एड किट चाहिए।', cat: 'Pharmacy' },
  { en: 'Do you have vitamins?', hi: 'क्या आपके पास विटामिन हैं?', cat: 'Pharmacy' },
  { en: 'I need something for acidity.', hi: 'मुझे एसिडिटी के लिए कुछ चाहिए।', cat: 'Pharmacy' },
  { en: 'Please check the expiry date.', hi: 'कृपया एक्सपायरी डेट देखें।', cat: 'Pharmacy' },

  // At the Optician (15)
  { en: 'I need to get my eyes tested.', hi: 'मुझे आंखों की जांच करानी है।', cat: 'Optician' },
  { en: 'I cannot see clearly.', hi: 'मुझे साफ दिखाई नहीं देता।', cat: 'Optician' },
  { en: 'I need new glasses.', hi: 'मुझे नया चश्मा चाहिए।', cat: 'Optician' },
  { en: 'I want contact lenses.', hi: 'मुझे कॉन्टैक्ट लेंस चाहिए।', cat: 'Optician' },
  { en: 'My prescription has changed.', hi: 'मेरा नंबर बदल गया है।', cat: 'Optician' },
  { en: 'I have difficulty reading.', hi: 'मुझे पढ़ने में दिक्कत होती है।', cat: 'Optician' },
  { en: 'I get headaches while reading.', hi: 'पढ़ते समय सिरदर्द होता है।', cat: 'Optician' },
  { en: 'Can I try these frames?', hi: 'क्या मैं ये फ्रेम पहनकर देख सकता हूँ?', cat: 'Optician' },
  { en: 'Do you have anti-glare lenses?', hi: 'क्या आपके पास एंटी-ग्लेयर लेंस हैं?', cat: 'Optician' },
  { en: 'I want sunglasses with power.', hi: 'मुझे नंबर वाला सनग्लास चाहिए।', cat: 'Optician' },
  { en: 'My glasses are broken.', hi: 'मेरा चश्मा टूट गया है।', cat: 'Optician' },
  { en: 'Can you repair this?', hi: 'क्या आप इसे ठीक कर सकते हैं?', cat: 'Optician' },
  { en: 'The frame is too tight.', hi: 'फ्रेम बहुत टाइट है।', cat: 'Optician' },
  { en: 'Please adjust the nose pads.', hi: 'कृपया नोज पैड एडजस्ट करें।', cat: 'Optician' },
  { en: 'When will my glasses be ready?', hi: 'मेरा चश्मा कब तैयार होगा?', cat: 'Optician' },

  // At the Dentist (15)
  { en: 'I have a toothache.', hi: 'मेरे दांत में दर्द है।', cat: 'Dentist' },
  { en: 'I need to see a dentist.', hi: 'मुझे दंत चिकित्सक से मिलना है।', cat: 'Dentist' },
  { en: 'I have a cavity.', hi: 'मेरे दांत में कीड़ा लगा है।', cat: 'Dentist' },
  { en: 'I need a filling.', hi: 'मुझे फिलिंग करवानी है।', cat: 'Dentist' },
  { en: 'I need to get a tooth extracted.', hi: 'मुझे दांत निकलवाना है।', cat: 'Dentist' },
  { en: 'My gums are bleeding.', hi: 'मेरे मसूड़ों से खून आ रहा है।', cat: 'Dentist' },
  { en: 'I want teeth cleaning.', hi: 'मुझे दांत साफ करवाने हैं।', cat: 'Dentist' },
  { en: 'I want teeth whitening.', hi: 'मुझे दांत सफेद करवाने हैं।', cat: 'Dentist' },
  { en: 'I need braces.', hi: 'मुझे ब्रेसेस लगवाने हैं।', cat: 'Dentist' },
  { en: 'Will it be painful?', hi: 'क्या दर्द होगा?', cat: 'Dentist' },
  { en: 'Please give me anesthesia.', hi: 'कृपया मुझे एनेस्थीसिया दें।', cat: 'Dentist' },
  { en: 'I am scared of the drill.', hi: 'मुझे ड्रिल से डर लगता है।', cat: 'Dentist' },
  { en: 'How much will it cost?', hi: 'कितना खर्च आएगा?', cat: 'Dentist' },
  { en: 'I need a dental X-ray.', hi: 'मुझे दांत का एक्स-रे चाहिए।', cat: 'Dentist' },
  { en: 'My wisdom tooth is coming.', hi: 'मेरा अक्ल दाढ़ निकल रहा है।', cat: 'Dentist' },

  // Online Shopping (20)
  { en: 'I want to order this online.', hi: 'मैं इसे ऑनलाइन ऑर्डर करना चाहता हूँ।', cat: 'Online Shopping' },
  { en: 'Is this product available?', hi: 'क्या यह प्रोडक्ट उपलब्ध है?', cat: 'Online Shopping' },
  { en: 'What is the delivery time?', hi: 'डिलीवरी में कितना समय लगेगा?', cat: 'Online Shopping' },
  { en: 'Is there free shipping?', hi: 'क्या फ्री शिपिंग है?', cat: 'Online Shopping' },
  { en: 'I want to track my order.', hi: 'मैं अपना ऑर्डर ट्रैक करना चाहता हूँ।', cat: 'Online Shopping' },
  { en: 'My order has not arrived.', hi: 'मेरा ऑर्डर नहीं आया।', cat: 'Online Shopping' },
  { en: 'I received a wrong item.', hi: 'मुझे गलत आइटम मिला।', cat: 'Online Shopping' },
  { en: 'I want to return this product.', hi: 'मैं यह प्रोडक्ट वापस करना चाहता हूँ।', cat: 'Online Shopping' },
  { en: 'I want a replacement.', hi: 'मुझे बदला हुआ चाहिए।', cat: 'Online Shopping' },
  { en: 'When will I get my refund?', hi: 'मुझे रिफंड कब मिलेगा?', cat: 'Online Shopping' },
  { en: 'The product is damaged.', hi: 'प्रोडक्ट खराब है।', cat: 'Online Shopping' },
  { en: 'This is not as described.', hi: 'यह वैसा नहीं है जैसा बताया गया था।', cat: 'Online Shopping' },
  { en: 'I want to cancel my order.', hi: 'मैं अपना ऑर्डर रद्द करना चाहता हूँ।', cat: 'Online Shopping' },
  { en: 'Can I pay cash on delivery?', hi: 'क्या मैं कैश ऑन डिलीवरी कर सकता हूँ?', cat: 'Online Shopping' },
  { en: 'I have a coupon code.', hi: 'मेरे पास कूपन कोड है।', cat: 'Online Shopping' },
  { en: 'The discount is not applied.', hi: 'डिस्काउंट लागू नहीं हुआ।', cat: 'Online Shopping' },
  { en: 'I want to change my address.', hi: 'मैं अपना पता बदलना चाहता हूँ।', cat: 'Online Shopping' },
  { en: 'Please deliver to this address.', hi: 'कृपया इस पते पर डिलीवर करें।', cat: 'Online Shopping' },
  { en: 'I was not home during delivery.', hi: 'डिलीवरी के समय मैं घर पर नहीं था।', cat: 'Online Shopping' },
  { en: 'Can you redeliver tomorrow?', hi: 'क्या आप कल दोबारा डिलीवर कर सकते हैं?', cat: 'Online Shopping' },

  // Social Media & Internet (20)
  { en: 'Can you send me a friend request?', hi: 'क्या आप मुझे फ्रेंड रिक्वेस्ट भेज सकते हैं?', cat: 'Social Media' },
  { en: 'I will follow you on Instagram.', hi: 'मैं आपको इंस्टाग्राम पर फॉलो करूंगा।', cat: 'Social Media' },
  { en: 'Please like and share this post.', hi: 'कृपया इस पोस्ट को लाइक और शेयर करें।', cat: 'Social Media' },
  { en: 'I will tag you in the photo.', hi: 'मैं आपको फोटो में टैग करूंगा।', cat: 'Social Media' },
  { en: 'Check your inbox.', hi: 'अपना इनबॉक्स चेक करो।', cat: 'Social Media' },
  { en: 'I sent you a message.', hi: 'मैंने तुम्हें मैसेज भेजा।', cat: 'Social Media' },
  { en: 'Did you see my story?', hi: 'क्या तुमने मेरी स्टोरी देखी?', cat: 'Social Media' },
  { en: 'I will upload the video later.', hi: 'मैं वीडियो बाद में अपलोड करूंगा।', cat: 'Social Media' },
  { en: 'The video is buffering.', hi: 'वीडियो बफर हो रहा है।', cat: 'Social Media' },
  { en: 'My account has been hacked.', hi: 'मेरा अकाउंट हैक हो गया है।', cat: 'Social Media' },
  { en: 'I forgot my password.', hi: 'मैं अपना पासवर्ड भूल गया।', cat: 'Social Media' },
  { en: 'How do I reset my password?', hi: 'पासवर्ड कैसे रीसेट करें?', cat: 'Social Media' },
  { en: 'I want to delete my account.', hi: 'मैं अपना अकाउंट डिलीट करना चाहता हूँ।', cat: 'Social Media' },
  { en: 'I want to change my privacy settings.', hi: 'मैं अपनी प्राइवेसी सेटिंग्स बदलना चाहता हूँ।', cat: 'Social Media' },
  { en: 'Someone is sending me spam.', hi: 'कोई मुझे स्पैम भेज रहा है।', cat: 'Social Media' },
  { en: 'I want to block this person.', hi: 'मैं इस व्यक्ति को ब्लॉक करना चाहता हूँ।', cat: 'Social Media' },
  { en: 'I want to report this account.', hi: 'मैं इस अकाउंट की रिपोर्ट करना चाहता हूँ।', cat: 'Social Media' },
  { en: 'The app is not working.', hi: 'ऐप काम नहीं कर रहा।', cat: 'Social Media' },
  { en: 'I need to update the app.', hi: 'मुझे ऐप अपडेट करना है।', cat: 'Social Media' },
  { en: 'My data is finished.', hi: 'मेरा डेटा खत्म हो गया।', cat: 'Social Media' },

  // Relationships & Feelings (30)
  { en: 'I really like you.', hi: 'तुम मुझे बहुत पसंद हो।', cat: 'Relationships' },
  { en: 'I love you.', hi: 'मैं तुमसे प्यार करता हूँ।', cat: 'Relationships' },
  { en: 'Will you marry me?', hi: 'क्या तुम मुझसे शादी करोगी?', cat: 'Relationships' },
  { en: 'I miss you so much.', hi: 'मुझे तुम्हारी बहुत याद आती है।', cat: 'Relationships' },
  { en: 'I am thinking about you.', hi: 'मैं तुम्हारे बारे में सोच रहा हूँ।', cat: 'Relationships' },
  { en: 'You mean a lot to me.', hi: 'तुम मेरे लिए बहुत मायने रखते हो।', cat: 'Relationships' },
  { en: 'I cannot live without you.', hi: 'मैं तुम्हारे बिना नहीं रह सकता।', cat: 'Relationships' },
  { en: 'You make me happy.', hi: 'तुम मुझे खुश करते हो।', cat: 'Relationships' },
  { en: 'I am sorry for hurting you.', hi: 'तुम्हें दुख पहुंचाने के लिए माफी।', cat: 'Relationships' },
  { en: 'Please forgive me.', hi: 'कृपया मुझे माफ कर दो।', cat: 'Relationships' },
  { en: 'I trust you completely.', hi: 'मुझे तुम पर पूरा भरोसा है।', cat: 'Relationships' },
  { en: 'I am proud of you.', hi: 'मुझे तुम पर गर्व है।', cat: 'Relationships' },
  { en: 'I believe in you.', hi: 'मुझे तुम पर विश्वास है।', cat: 'Relationships' },
  { en: 'I will always support you.', hi: 'मैं हमेशा तुम्हारा साथ दूंगा।', cat: 'Relationships' },
  { en: 'We need to talk.', hi: 'हमें बात करनी है।', cat: 'Relationships' },
  { en: 'I need some space.', hi: 'मुझे थोड़ी जगह चाहिए।', cat: 'Relationships' },
  { en: 'Let us work this out.', hi: 'आओ इसे सुलझाएं।', cat: 'Relationships' },
  { en: 'I did not mean to hurt you.', hi: 'मेरा इरादा तुम्हें दुख पहुंचाने का नहीं था।', cat: 'Relationships' },
  { en: 'I understand how you feel.', hi: 'मैं समझता हूँ तुम कैसा महसूस कर रहे हो।', cat: 'Relationships' },
  { en: 'I am here for you.', hi: 'मैं तुम्हारे साथ हूँ।', cat: 'Relationships' },
  { en: 'You can count on me.', hi: 'तुम मुझ पर भरोसा कर सकते हो।', cat: 'Relationships' },
  { en: 'I appreciate everything you do.', hi: 'तुम जो भी करते हो मैं उसकी कद्र करता हूँ।', cat: 'Relationships' },
  { en: 'Thank you for being there.', hi: 'साथ रहने के लिए धन्यवाद।', cat: 'Relationships' },
  { en: 'I am lucky to have you.', hi: 'मैं भाग्यशाली हूँ कि तुम मेरे साथ हो।', cat: 'Relationships' },
  { en: 'You are my best friend.', hi: 'तुम मेरे सबसे अच्छे दोस्त हो।', cat: 'Relationships' },
  { en: 'I value our friendship.', hi: 'मैं हमारी दोस्ती की कद्र करता हूँ।', cat: 'Relationships' },
  { en: 'Let us stay in touch.', hi: 'संपर्क में रहते हैं।', cat: 'Relationships' },
  { en: 'I will never forget you.', hi: 'मैं तुम्हें कभी नहीं भूलूंगा।', cat: 'Relationships' },
  { en: 'Take care of yourself.', hi: 'अपना ख्याल रखना।', cat: 'Relationships' },
  { en: 'I wish you all the best.', hi: 'मैं तुम्हें शुभकामनाएं देता हूँ।', cat: 'Relationships' },

  // Emergencies (15)
  { en: 'Help! There is a fire!', hi: 'मदद! आग लगी है!', cat: 'Emergency' },
  { en: 'Call the police!', hi: 'पुलिस को बुलाओ!', cat: 'Emergency' },
  { en: 'Call an ambulance!', hi: 'एम्बुलेंस बुलाओ!', cat: 'Emergency' },
  { en: 'There has been an accident.', hi: 'दुर्घटना हो गई है।', cat: 'Emergency' },
  { en: 'Someone is injured.', hi: 'कोई घायल है।', cat: 'Emergency' },
  { en: 'I need a doctor immediately.', hi: 'मुझे तुरंत डॉक्टर चाहिए।', cat: 'Emergency' },
  { en: 'Where is the nearest hospital?', hi: 'सबसे नजदीकी अस्पताल कहाँ है?', cat: 'Emergency' },
  { en: 'I am having chest pain.', hi: 'मेरे सीने में दर्द हो रहा है।', cat: 'Emergency' },
  { en: 'I cannot breathe properly.', hi: 'मुझे सांस लेने में तकलीफ हो रही है।', cat: 'Emergency' },
  { en: 'Someone fainted.', hi: 'कोई बेहोश हो गया।', cat: 'Emergency' },
  { en: 'There is a gas leak.', hi: 'गैस लीक हो रही है।', cat: 'Emergency' },
  { en: 'The building is collapsing.', hi: 'इमारत गिर रही है।', cat: 'Emergency' },
  { en: 'I am being followed.', hi: 'कोई मेरा पीछा कर रहा है।', cat: 'Emergency' },
  { en: 'I feel unsafe here.', hi: 'मुझे यहाँ असुरक्षित लग रहा है।', cat: 'Emergency' },
  { en: 'Please help me.', hi: 'कृपया मेरी मदद करें।', cat: 'Emergency' },
];
