// GRAMMAR LESSONS - 150 lessons
export const grammarLessons = [
  // Present Tense (25)
  { en: 'I eat breakfast every day.', hi: 'मैं रोज नाश्ता करता हूँ।', cat: 'Present Tense' },
  { en: 'She works in a hospital.', hi: 'वह अस्पताल में काम करती है।', cat: 'Present Tense' },
  { en: 'They play cricket on Sundays.', hi: 'वे रविवार को क्रिकेट खेलते हैं।', cat: 'Present Tense' },
  { en: 'He reads the newspaper daily.', hi: 'वह रोज अखबार पढ़ता है।', cat: 'Present Tense' },
  { en: 'We go to temple every week.', hi: 'हम हर हफ्ते मंदिर जाते हैं।', cat: 'Present Tense' },
  { en: 'The sun rises in the east.', hi: 'सूरज पूर्व में उगता है।', cat: 'Present Tense' },
  { en: 'Water boils at 100 degrees.', hi: 'पानी 100 डिग्री पर उबलता है।', cat: 'Present Tense' },
  { en: 'Birds fly in the sky.', hi: 'पक्षी आसमान में उड़ते हैं।', cat: 'Present Tense' },
  { en: 'My father drives carefully.', hi: 'मेरे पिता सावधानी से गाड़ी चलाते हैं।', cat: 'Present Tense' },
  { en: 'She speaks three languages.', hi: 'वह तीन भाषाएं बोलती है।', cat: 'Present Tense' },
  { en: 'I am eating lunch now.', hi: 'मैं अभी दोपहर का खाना खा रहा हूँ।', cat: 'Present Tense' },
  { en: 'She is cooking dinner.', hi: 'वह रात का खाना बना रही है।', cat: 'Present Tense' },
  { en: 'They are watching a movie.', hi: 'वे फिल्म देख रहे हैं।', cat: 'Present Tense' },
  { en: 'He is studying for exams.', hi: 'वह परीक्षा के लिए पढ़ रहा है।', cat: 'Present Tense' },
  { en: 'We are waiting for the bus.', hi: 'हम बस का इंतजार कर रहे हैं।', cat: 'Present Tense' },
  { en: 'The children are playing outside.', hi: 'बच्चे बाहर खेल रहे हैं।', cat: 'Present Tense' },
  { en: 'It is raining heavily.', hi: 'बहुत तेज बारिश हो रही है।', cat: 'Present Tense' },
  { en: 'I am learning to drive.', hi: 'मैं गाड़ी चलाना सीख रहा हूँ।', cat: 'Present Tense' },
  { en: 'She is talking on the phone.', hi: 'वह फोन पर बात कर रही है।', cat: 'Present Tense' },
  { en: 'They are building a new house.', hi: 'वे नया घर बना रहे हैं।', cat: 'Present Tense' },
  { en: 'I have finished my work.', hi: 'मैंने अपना काम खत्म कर लिया है।', cat: 'Present Tense' },
  { en: 'She has already eaten.', hi: 'वह पहले ही खा चुकी है।', cat: 'Present Tense' },
  { en: 'They have gone to the market.', hi: 'वे बाजार गए हैं।', cat: 'Present Tense' },
  { en: 'He has never been to Delhi.', hi: 'वह कभी दिल्ली नहीं गया।', cat: 'Present Tense' },
  { en: 'We have known each other for years.', hi: 'हम सालों से एक दूसरे को जानते हैं।', cat: 'Present Tense' },

  // Past Tense (25)
  { en: 'I went to school yesterday.', hi: 'मैं कल स्कूल गया था।', cat: 'Past Tense' },
  { en: 'She cooked delicious food.', hi: 'उसने स्वादिष्ट खाना बनाया।', cat: 'Past Tense' },
  { en: 'They played football last week.', hi: 'उन्होंने पिछले हफ्ते फुटबॉल खेला।', cat: 'Past Tense' },
  { en: 'He bought a new car.', hi: 'उसने नई गाड़ी खरीदी।', cat: 'Past Tense' },
  { en: 'We visited the Taj Mahal.', hi: 'हमने ताज महल देखा।', cat: 'Past Tense' },
  { en: 'The movie started at seven.', hi: 'फिल्म सात बजे शुरू हुई।', cat: 'Past Tense' },
  { en: 'I met him at the party.', hi: 'मैं उससे पार्टी में मिला।', cat: 'Past Tense' },
  { en: 'She wrote a beautiful poem.', hi: 'उसने एक सुंदर कविता लिखी।', cat: 'Past Tense' },
  { en: 'They sold their old house.', hi: 'उन्होंने अपना पुराना घर बेच दिया।', cat: 'Past Tense' },
  { en: 'He forgot his wallet at home.', hi: 'वह अपना बटुआ घर पर भूल गया।', cat: 'Past Tense' },
  { en: 'I was sleeping when you called.', hi: 'जब तुमने फोन किया मैं सो रहा था।', cat: 'Past Tense' },
  { en: 'She was reading a book.', hi: 'वह किताब पढ़ रही थी।', cat: 'Past Tense' },
  { en: 'They were dancing at the party.', hi: 'वे पार्टी में नाच रहे थे।', cat: 'Past Tense' },
  { en: 'He was working late last night.', hi: 'वह कल रात देर तक काम कर रहा था।', cat: 'Past Tense' },
  { en: 'We were waiting for you.', hi: 'हम तुम्हारा इंतजार कर रहे थे।', cat: 'Past Tense' },
  { en: 'The children were playing in the park.', hi: 'बच्चे पार्क में खेल रहे थे।', cat: 'Past Tense' },
  { en: 'It was raining all day.', hi: 'पूरे दिन बारिश हो रही थी।', cat: 'Past Tense' },
  { en: 'I had eaten before you came.', hi: 'तुम्हारे आने से पहले मैं खा चुका था।', cat: 'Past Tense' },
  { en: 'She had left when I arrived.', hi: 'जब मैं पहुंचा वह जा चुकी थी।', cat: 'Past Tense' },
  { en: 'They had finished the project.', hi: 'उन्होंने प्रोजेक्ट पूरा कर लिया था।', cat: 'Past Tense' },
  { en: 'He had never seen snow before.', hi: 'उसने पहले कभी बर्फ नहीं देखी थी।', cat: 'Past Tense' },
  { en: 'We had already booked the tickets.', hi: 'हमने पहले ही टिकट बुक कर लिए थे।', cat: 'Past Tense' },
  { en: 'I lost my keys yesterday.', hi: 'मैंने कल अपनी चाबियां खो दीं।', cat: 'Past Tense' },
  { en: 'She passed the exam with good marks.', hi: 'वह अच्छे अंकों से परीक्षा पास हुई।', cat: 'Past Tense' },
  { en: 'The train left five minutes ago.', hi: 'ट्रेन पांच मिनट पहले गई।', cat: 'Past Tense' },

  // Future Tense (25)
  { en: 'I will go to office tomorrow.', hi: 'मैं कल ऑफिस जाऊंगा।', cat: 'Future Tense' },
  { en: 'She will cook dinner tonight.', hi: 'वह आज रात खाना बनाएगी।', cat: 'Future Tense' },
  { en: 'They will arrive next week.', hi: 'वे अगले हफ्ते आएंगे।', cat: 'Future Tense' },
  { en: 'He will call you later.', hi: 'वह तुम्हें बाद में फोन करेगा।', cat: 'Future Tense' },
  { en: 'We will meet at the station.', hi: 'हम स्टेशन पर मिलेंगे।', cat: 'Future Tense' },
  { en: 'The shop will open at ten.', hi: 'दुकान दस बजे खुलेगी।', cat: 'Future Tense' },
  { en: 'I will help you with this.', hi: 'मैं इसमें तुम्हारी मदद करूंगा।', cat: 'Future Tense' },
  { en: 'She will finish the work soon.', hi: 'वह जल्दी काम खत्म कर लेगी।', cat: 'Future Tense' },
  { en: 'They will buy a new house.', hi: 'वे नया घर खरीदेंगे।', cat: 'Future Tense' },
  { en: 'He will become a doctor.', hi: 'वह डॉक्टर बनेगा।', cat: 'Future Tense' },
  { en: 'I am going to start a business.', hi: 'मैं व्यापार शुरू करने वाला हूँ।', cat: 'Future Tense' },
  { en: 'She is going to have a baby.', hi: 'उसके बच्चा होने वाला है।', cat: 'Future Tense' },
  { en: 'They are going to move to Mumbai.', hi: 'वे मुंबई जाने वाले हैं।', cat: 'Future Tense' },
  { en: 'It is going to rain today.', hi: 'आज बारिश होने वाली है।', cat: 'Future Tense' },
  { en: 'We are going to celebrate.', hi: 'हम जश्न मनाने वाले हैं।', cat: 'Future Tense' },
  { en: 'I will be working at that time.', hi: 'उस समय मैं काम कर रहा होऊंगा।', cat: 'Future Tense' },
  { en: 'She will be sleeping by then.', hi: 'तब तक वह सो रही होगी।', cat: 'Future Tense' },
  { en: 'They will be traveling tomorrow.', hi: 'वे कल यात्रा कर रहे होंगे।', cat: 'Future Tense' },
  { en: 'I will have finished by evening.', hi: 'शाम तक मैं खत्म कर चुका होऊंगा।', cat: 'Future Tense' },
  { en: 'She will have left by then.', hi: 'तब तक वह जा चुकी होगी।', cat: 'Future Tense' },
  { en: 'Tomorrow will be a holiday.', hi: 'कल छुट्टी होगी।', cat: 'Future Tense' },
  { en: 'Next year I will be 30.', hi: 'अगले साल मैं 30 का हो जाऊंगा।', cat: 'Future Tense' },
  { en: 'The results will come next month.', hi: 'नतीजे अगले महीने आएंगे।', cat: 'Future Tense' },
  { en: 'I will never forget this day.', hi: 'मैं यह दिन कभी नहीं भूलूंगा।', cat: 'Future Tense' },
  { en: 'Everything will be fine.', hi: 'सब ठीक हो जाएगा।', cat: 'Future Tense' },

  // Questions & Negatives (25)
  { en: 'Do you speak English?', hi: 'क्या आप अंग्रेजी बोलते हैं?', cat: 'Questions' },
  { en: 'Does she live here?', hi: 'क्या वह यहाँ रहती है?', cat: 'Questions' },
  { en: 'Did you finish your homework?', hi: 'क्या तुमने होमवर्क पूरा किया?', cat: 'Questions' },
  { en: 'Will you come to the party?', hi: 'क्या तुम पार्टी में आओगे?', cat: 'Questions' },
  { en: 'Can you help me please?', hi: 'क्या आप मेरी मदद कर सकते हैं?', cat: 'Questions' },
  { en: 'Have you ever been abroad?', hi: 'क्या तुम कभी विदेश गए हो?', cat: 'Questions' },
  { en: 'Are you coming with us?', hi: 'क्या तुम हमारे साथ आ रहे हो?', cat: 'Questions' },
  { en: 'Was the movie good?', hi: 'क्या फिल्म अच्छी थी?', cat: 'Questions' },
  { en: 'Were you at home yesterday?', hi: 'क्या तुम कल घर पर थे?', cat: 'Questions' },
  { en: 'Would you like some tea?', hi: 'क्या आप चाय लेंगे?', cat: 'Questions' },
  { en: 'I do not understand this.', hi: 'मुझे यह समझ नहीं आ रहा।', cat: 'Questions' },
  { en: 'She does not eat meat.', hi: 'वह मांस नहीं खाती।', cat: 'Questions' },
  { en: 'They did not come yesterday.', hi: 'वे कल नहीं आए।', cat: 'Questions' },
  { en: 'He will not go there.', hi: 'वह वहाँ नहीं जाएगा।', cat: 'Questions' },
  { en: 'We cannot wait any longer.', hi: 'हम और इंतजार नहीं कर सकते।', cat: 'Questions' },
  { en: 'I have not seen him today.', hi: 'मैंने उसे आज नहीं देखा।', cat: 'Questions' },
  { en: 'She is not feeling well.', hi: 'उसकी तबीयत ठीक नहीं है।', cat: 'Questions' },
  { en: 'They were not at the meeting.', hi: 'वे मीटिंग में नहीं थे।', cat: 'Questions' },
  { en: 'It was not my fault.', hi: 'यह मेरी गलती नहीं थी।', cat: 'Questions' },
  { en: 'I would not do that.', hi: 'मैं ऐसा नहीं करूंगा।', cat: 'Questions' },
  { en: 'Why are you late?', hi: 'तुम्हें देर क्यों हुई?', cat: 'Questions' },
  { en: 'When did you arrive?', hi: 'तुम कब पहुंचे?', cat: 'Questions' },
  { en: 'Where is the nearest bank?', hi: 'सबसे नजदीकी बैंक कहाँ है?', cat: 'Questions' },
  { en: 'How much does it cost?', hi: 'इसकी कीमत कितनी है?', cat: 'Questions' },
  { en: 'Who told you this?', hi: 'तुम्हें यह किसने बताया?', cat: 'Questions' },

  // Modal Verbs (25)
  { en: 'I can swim very well.', hi: 'मैं बहुत अच्छा तैर सकता हूँ।', cat: 'Modals' },
  { en: 'She can speak French fluently.', hi: 'वह धाराप्रवाह फ्रेंच बोल सकती है।', cat: 'Modals' },
  { en: 'Can I use your phone?', hi: 'क्या मैं आपका फोन इस्तेमाल कर सकता हूँ?', cat: 'Modals' },
  { en: 'You cannot park here.', hi: 'आप यहाँ पार्क नहीं कर सकते।', cat: 'Modals' },
  { en: 'I could not sleep last night.', hi: 'मैं कल रात सो नहीं पाया।', cat: 'Modals' },
  { en: 'Could you please close the door?', hi: 'क्या आप कृपया दरवाजा बंद कर सकते हैं?', cat: 'Modals' },
  { en: 'You should see a doctor.', hi: 'तुम्हें डॉक्टर को दिखाना चाहिए।', cat: 'Modals' },
  { en: 'We should leave now.', hi: 'हमें अब निकलना चाहिए।', cat: 'Modals' },
  { en: 'You should not smoke.', hi: 'तुम्हें धूम्रपान नहीं करना चाहिए।', cat: 'Modals' },
  { en: 'I must finish this today.', hi: 'मुझे यह आज खत्म करना है।', cat: 'Modals' },
  { en: 'You must wear a helmet.', hi: 'तुम्हें हेलमेट पहनना जरूरी है।', cat: 'Modals' },
  { en: 'We must not be late.', hi: 'हमें देर नहीं करनी चाहिए।', cat: 'Modals' },
  { en: 'May I come in?', hi: 'क्या मैं अंदर आ सकता हूँ?', cat: 'Modals' },
  { en: 'It may rain today.', hi: 'आज बारिश हो सकती है।', cat: 'Modals' },
  { en: 'She might come tomorrow.', hi: 'वह कल आ सकती है।', cat: 'Modals' },
  { en: 'He might be busy.', hi: 'वह व्यस्त हो सकता है।', cat: 'Modals' },
  { en: 'Would you like some coffee?', hi: 'क्या आप कॉफी लेंगे?', cat: 'Modals' },
  { en: 'I would like to book a table.', hi: 'मैं एक टेबल बुक करना चाहूंगा।', cat: 'Modals' },
  { en: 'You have to submit it today.', hi: 'तुम्हें यह आज जमा करना है।', cat: 'Modals' },
  { en: 'Do I have to pay now?', hi: 'क्या मुझे अभी भुगतान करना है?', cat: 'Modals' },
  { en: 'You need to be careful.', hi: 'तुम्हें सावधान रहना होगा।', cat: 'Modals' },
  { en: 'I need to go now.', hi: 'मुझे अब जाना होगा।', cat: 'Modals' },
  { en: 'You ought to apologize.', hi: 'तुम्हें माफी मांगनी चाहिए।', cat: 'Modals' },
  { en: 'She used to live here.', hi: 'वह पहले यहाँ रहती थी।', cat: 'Modals' },
  { en: 'I used to play cricket.', hi: 'मैं पहले क्रिकेट खेलता था।', cat: 'Modals' },

  // Prepositions (25)
  { en: 'The book is on the table.', hi: 'किताब मेज पर है।', cat: 'Prepositions' },
  { en: 'The cat is under the bed.', hi: 'बिल्ली बिस्तर के नीचे है।', cat: 'Prepositions' },
  { en: 'He is standing behind me.', hi: 'वह मेरे पीछे खड़ा है।', cat: 'Prepositions' },
  { en: 'She is sitting in front of the TV.', hi: 'वह टीवी के सामने बैठी है।', cat: 'Prepositions' },
  { en: 'The shop is between the bank and the hotel.', hi: 'दुकान बैंक और होटल के बीच में है।', cat: 'Prepositions' },
  { en: 'I will meet you at the station.', hi: 'मैं तुमसे स्टेशन पर मिलूंगा।', cat: 'Prepositions' },
  { en: 'She arrived at 5 o clock.', hi: 'वह 5 बजे पहुंची।', cat: 'Prepositions' },
  { en: 'I was born in 1990.', hi: 'मेरा जन्म 1990 में हुआ।', cat: 'Prepositions' },
  { en: 'We go to school in the morning.', hi: 'हम सुबह स्कूल जाते हैं।', cat: 'Prepositions' },
  { en: 'I will call you on Monday.', hi: 'मैं तुम्हें सोमवार को फोन करूंगा।', cat: 'Prepositions' },
  { en: 'He is good at mathematics.', hi: 'वह गणित में अच्छा है।', cat: 'Prepositions' },
  { en: 'She is interested in music.', hi: 'उसे संगीत में रुचि है।', cat: 'Prepositions' },
  { en: 'I am afraid of dogs.', hi: 'मुझे कुत्तों से डर लगता है।', cat: 'Prepositions' },
  { en: 'He is angry with me.', hi: 'वह मुझसे नाराज है।', cat: 'Prepositions' },
  { en: 'She is married to a doctor.', hi: 'उसकी शादी एक डॉक्टर से हुई है।', cat: 'Prepositions' },
  { en: 'I am waiting for the bus.', hi: 'मैं बस का इंतजार कर रहा हूँ।', cat: 'Prepositions' },
  { en: 'He is looking for a job.', hi: 'वह नौकरी ढूंढ रहा है।', cat: 'Prepositions' },
  { en: 'She is listening to music.', hi: 'वह संगीत सुन रही है।', cat: 'Prepositions' },
  { en: 'I agree with you.', hi: 'मैं आपसे सहमत हूँ।', cat: 'Prepositions' },
  { en: 'He depends on his parents.', hi: 'वह अपने माता-पिता पर निर्भर है।', cat: 'Prepositions' },
  { en: 'The train goes through the tunnel.', hi: 'ट्रेन सुरंग से गुजरती है।', cat: 'Prepositions' },
  { en: 'Walk along this road.', hi: 'इस सड़क के साथ चलो।', cat: 'Prepositions' },
  { en: 'Jump over the fence.', hi: 'बाड़ के ऊपर से कूदो।', cat: 'Prepositions' },
  { en: 'The plane flew above the clouds.', hi: 'विमान बादलों के ऊपर उड़ा।', cat: 'Prepositions' },
  { en: 'He walked across the street.', hi: 'वह सड़क पार करके गया।', cat: 'Prepositions' },
];
