// Comprehensive English Learning Lessons for Hindi Speakers

export interface Lesson {
  id: string;
  english: string;
  hindi: string;
  pronunciation: string;
  category: string;
}

export const allLessons: Lesson[] = [
  // Greetings & Social (50 lessons)
  { id: '1', english: 'Good morning, how are you doing today?', hindi: 'सुप्रभात, आज आप कैसे हैं?', pronunciation: 'Suprabhat, aaj aap kaise hain?', category: 'Greetings' },
  { id: '2', english: 'It\'s nice to meet you', hindi: 'आपसे मिलकर अच्छा लगा', pronunciation: 'Aapse milkar achha laga', category: 'Greetings' },
  { id: '3', english: 'I hope you\'re having a great day', hindi: 'मुझे आशा है कि आपका दिन अच्छा जा रहा है', pronunciation: 'Mujhe aasha hai ki aapka din achha ja raha hai', category: 'Greetings' },
  { id: '4', english: 'Thank you for your help', hindi: 'आपकी मदद के लिए धन्यवाद', pronunciation: 'Aapki madad ke liye dhanyavaad', category: 'Greetings' },
  { id: '5', english: 'I appreciate your support', hindi: 'मैं आपके समर्थन की सराहना करता हूं', pronunciation: 'Main aapke samarthan ki sarahna karta hoon', category: 'Greetings' },
  { id: '6', english: 'Have a wonderful evening', hindi: 'आपकी शाम शानदार हो', pronunciation: 'Aapki shaam shaandaar ho', category: 'Greetings' },
  { id: '7', english: 'I\'m pleased to see you again', hindi: 'आपको फिर से देखकर खुशी हुई', pronunciation: 'Aapko phir se dekhkar khushi hui', category: 'Greetings' },
  { id: '8', english: 'How have you been lately?', hindi: 'आप इन दिनों कैसे हैं?', pronunciation: 'Aap in dinon kaise hain?', category: 'Greetings' },
  { id: '9', english: 'I\'m doing well, thank you for asking', hindi: 'मैं अच्छा हूं, पूछने के लिए धन्यवाद', pronunciation: 'Main achha hoon, poochne ke liye dhanyavaad', category: 'Greetings' },
  { id: '10', english: 'Please give my regards to your family', hindi: 'कृपया अपने परिवार को मेरा प्रणाम दें', pronunciation: 'Kripya apne parivaar ko mera pranaam dein', category: 'Greetings' },
  { id: '11', english: 'I look forward to seeing you soon', hindi: 'मैं जल्द ही आपसे मिलने की उम्मीद करता हूं', pronunciation: 'Main jald hi aapse milne ki ummeed karta hoon', category: 'Greetings' },
  { id: '12', english: 'Take care of yourself', hindi: 'अपना ख्याल रखें', pronunciation: 'Apna khyaal rakhein', category: 'Greetings' },
  { id: '13', english: 'Best wishes for your future', hindi: 'आपके भविष्य के लिए शुभकामनाएं', pronunciation: 'Aapke bhavishya ke liye shubhkaamnaayein', category: 'Greetings' },
  { id: '14', english: 'Congratulations on your success', hindi: 'आपकी सफलता पर बधाई', pronunciation: 'Aapki saphalata par badhaai', category: 'Greetings' },
  { id: '15', english: 'I\'m sorry for being late', hindi: 'देर से आने के लिए मुझे खेद है', pronunciation: 'Der se aane ke liye mujhe khed hai', category: 'Greetings' },
  
  // Daily Conversations (60 lessons)
  { id: '16', english: 'Could you please explain this to me?', hindi: 'क्या आप कृपया मुझे यह समझा सकते हैं?', pronunciation: 'Kya aap kripya mujhe yeh samjha sakte hain?', category: 'Daily' },
  { id: '17', english: 'I need to finish this work by tomorrow', hindi: 'मुझे यह काम कल तक खत्म करना है', pronunciation: 'Mujhe yeh kaam kal tak khatam karna hai', category: 'Daily' },
  { id: '18', english: 'What time does the meeting start?', hindi: 'मीटिंग कितने बजे शुरू होती है?', pronunciation: 'Meeting kitne baje shuru hoti hai?', category: 'Daily' },
  { id: '19', english: 'I would like to make a reservation', hindi: 'मैं आरक्षण करना चाहूंगा', pronunciation: 'Main aarakshan karna chahunga', category: 'Daily' },
  { id: '20', english: 'Can you recommend a good restaurant?', hindi: 'क्या आप एक अच्छे रेस्टोरेंट की सिफारिश कर सकते हैं?', pronunciation: 'Kya aap ek achhe restaurant ki sifarish kar sakte hain?', category: 'Daily' },
  { id: '21', english: 'I\'m looking for a quiet place to study', hindi: 'मैं पढ़ने के लिए एक शांत जगह ढूंढ रहा हूं', pronunciation: 'Main padhne ke liye ek shaant jagah dhoondh raha hoon', category: 'Daily' },
  { id: '22', english: 'Where is the nearest ATM?', hindi: 'सबसे निकटतम एटीएम कहाँ है?', pronunciation: 'Sabse nikattam ATM kahaan hai?', category: 'Daily' },
  { id: '23', english: 'I need to buy some groceries', hindi: 'मुझे कुछ किराने का सामान खरीदना है', pronunciation: 'Mujhe kuch kiraane ka saamaan khareedna hai', category: 'Daily' },
  { id: '24', english: 'How much does this cost?', hindi: 'इसकी कीमत कितनी है?', pronunciation: 'Iski keemat kitni hai?', category: 'Daily' },
  { id: '25', english: 'Do you accept credit cards?', hindi: 'क्या आप क्रेडिट कार्ड स्वीकार करते हैं?', pronunciation: 'Kya aap credit card sweekar karte hain?', category: 'Daily' },
  { id: '26', english: 'I\'m having trouble with my internet connection', hindi: 'मुझे अपने इंटरनेट कनेक्शन में समस्या हो रही है', pronunciation: 'Mujhe apne internet connection mein samasya ho rahi hai', category: 'Daily' },
  { id: '27', english: 'Can you help me with this problem?', hindi: 'क्या आप इस समस्या में मेरी मदद कर सकते हैं?', pronunciation: 'Kya aap is samasya mein meri madad kar sakte hain?', category: 'Daily' },
  { id: '28', english: 'I don\'t feel well today', hindi: 'मैं आज ठीक महसूस नहीं कर रहा हूं', pronunciation: 'Main aaj theek mehsoos nahin kar raha hoon', category: 'Daily' },
  { id: '29', english: 'I have a doctor\'s appointment at 3 PM', hindi: 'मेरा डॉक्टर से 3 बजे अपॉइंटमेंट है', pronunciation: 'Mera doctor se 3 baje appointment hai', category: 'Daily' },
  { id: '30', english: 'The weather is beautiful today', hindi: 'आज मौसम बहुत सुंदर है', pronunciation: 'Aaj mausam bahut sundar hai', category: 'Daily' },
  { id: '31', english: 'I\'m running late for my appointment', hindi: 'मैं अपने अपॉइंटमेंट के लिए देर से पहुंच रहा हूं', pronunciation: 'Main apne appointment ke liye der se pahunch raha hoon', category: 'Daily' },
  { id: '32', english: 'Could you speak more slowly please?', hindi: 'क्या आप कृपया धीरे बोल सकते हैं?', pronunciation: 'Kya aap kripya dheere bol sakte hain?', category: 'Daily' },
  { id: '33', english: 'I didn\'t understand what you said', hindi: 'मुझे समझ नहीं आया कि आपने क्या कहा', pronunciation: 'Mujhe samajh nahin aaya ki aapne kya kaha', category: 'Daily' },
  { id: '34', english: 'Let me think about it', hindi: 'मुझे इसके बारे में सोचने दीजिए', pronunciation: 'Mujhe iske baare mein sochne deejiye', category: 'Daily' },
  { id: '35', english: 'That sounds like a good idea', hindi: 'यह एक अच्छा विचार लगता है', pronunciation: 'Yeh ek achha vichaar lagta hai', category: 'Daily' },
  
  // Business & Work (50 lessons)
  { id: '36', english: 'Please send me the documents', hindi: 'कृपया मुझे दस्तावेज़ भेजें', pronunciation: 'Kripya mujhe dastaavez bhejein', category: 'Business' },
  { id: '37', english: 'I have an important presentation tomorrow', hindi: 'कल मेरी एक महत्वपूर्ण प्रस्तुति है', pronunciation: 'Kal meri ek mahatvapoorn prastuti hai', category: 'Business' },
  { id: '38', english: 'Let\'s schedule a follow-up meeting', hindi: 'चलिए एक फॉलो-अप मीटिंग शेड्यूल करते हैं', pronunciation: 'Chaliye ek follow-up meeting schedule karte hain', category: 'Business' },
  { id: '39', english: 'I need to improve my communication skills', hindi: 'मुझे अपने संचार कौशल में सुधार करने की आवश्यकता है', pronunciation: 'Mujhe apne sanchaar kaushal mein sudhaar karne ki aavashyakta hai', category: 'Business' },
  { id: '40', english: 'The project is progressing well', hindi: 'परियोजना अच्छी तरह से आगे बढ़ रही है', pronunciation: 'Pariyojana achhi tarah se aage badh rahi hai', category: 'Business' },
  { id: '41', english: 'We should brainstorm some ideas', hindi: 'हमें कुछ विचारों पर विचार-विमर्श करना चाहिए', pronunciation: 'Hamein kuch vicharon par vichaar-vimarsh karna chahiye', category: 'Business' },
  { id: '42', english: 'What is the status of the project?', hindi: 'परियोजना की स्थिति क्या है?', pronunciation: 'Pariyojana ki sthiti kya hai?', category: 'Business' },
  { id: '43', english: 'We need to meet the deadline', hindi: 'हमें समय सीमा को पूरा करना होगा', pronunciation: 'Hamein samay seema ko poora karna hoga', category: 'Business' },
  { id: '44', english: 'Can you review this report?', hindi: 'क्या आप इस रिपोर्ट की समीक्षा कर सकते हैं?', pronunciation: 'Kya aap is report ki sameeksha kar sakte hain?', category: 'Business' },
  { id: '45', english: 'I\'m working on a new proposal', hindi: 'मैं एक नए प्रस्ताव पर काम कर रहा हूं', pronunciation: 'Main ek naye prastav par kaam kar raha hoon', category: 'Business' },
  { id: '46', english: 'The client wants to see the final draft', hindi: 'ग्राहक अंतिम मसौदा देखना चाहता है', pronunciation: 'Grahak antim masauda dekhna chaahta hai', category: 'Business' },
  { id: '47', english: 'We should focus on quality', hindi: 'हमें गुणवत्ता पर ध्यान देना चाहिए', pronunciation: 'Hamein gunavatta par dhyaan dena chahiye', category: 'Business' },
  { id: '48', english: 'I agree with your suggestions', hindi: 'मैं आपके सुझावों से सहमत हूं', pronunciation: 'Main aapke sujhavon se sahamat hoon', category: 'Business' },
  { id: '49', english: 'Let\'s discuss this in detail', hindi: 'चलिए इसकी विस्तार से चर्चा करते हैं', pronunciation: 'Chaliye iski vistaar se charcha karte hain', category: 'Business' },
  { id: '50', english: 'I\'ll send you the updated version', hindi: 'मैं आपको अपडेट किया हुआ संस्करण भेजूंगा', pronunciation: 'Main aapko update kiya hua sanskaran bhejunga', category: 'Business' },
  
  // Travel & Directions (40 lessons)
  { id: '51', english: 'How do I get to the railway station?', hindi: 'मैं रेलवे स्टेशन कैसे पहुंचूं?', pronunciation: 'Main railway station kaise pahunchoon?', category: 'Travel' },
  { id: '52', english: 'Where is the bus stop?', hindi: 'बस स्टॉप कहां है?', pronunciation: 'Bus stop kahaan hai?', category: 'Travel' },
  { id: '53', english: 'I need a taxi to the airport', hindi: 'मुझे हवाई अड्डे के लिए टैक्सी चाहिए', pronunciation: 'Mujhe havaai adde ke liye taxi chahiye', category: 'Travel' },
  { id: '54', english: 'Is this the right way to the museum?', hindi: 'क्या यह संग्रहालय का सही रास्ता है?', pronunciation: 'Kya yeh sangrahalay ka sahi raasta hai?', category: 'Travel' },
  { id: '55', english: 'How far is the hotel from here?', hindi: 'होटल यहां से कितनी दूर है?', pronunciation: 'Hotel yahaan se kitni door hai?', category: 'Travel' },
  { id: '56', english: 'Can you show me on the map?', hindi: 'क्या आप मुझे नक्शे पर दिखा सकते हैं?', pronunciation: 'Kya aap mujhe nakshe par dikha sakte hain?', category: 'Travel' },
  { id: '57', english: 'I\'d like to book a room for two nights', hindi: 'मैं दो रातों के लिए एक कमरा बुक करना चाहूंगा', pronunciation: 'Main do raaton ke liye ek kamra book karna chahunga', category: 'Travel' },
  { id: '58', english: 'What time is check-in?', hindi: 'चेक-इन का समय क्या है?', pronunciation: 'Check-in ka samay kya hai?', category: 'Travel' },
  { id: '59', english: 'Is breakfast included?', hindi: 'क्या नाश्ता शामिल है?', pronunciation: 'Kya naashta shaamil hai?', category: 'Travel' },
  { id: '60', english: 'Where can I rent a car?', hindi: 'मैं कार कहां किराए पर ले सकता हूं?', pronunciation: 'Main car kahaan kiraaye par le sakta hoon?', category: 'Travel' },
  
  // Shopping (30 lessons)
  { id: '61', english: 'How much does this shirt cost?', hindi: 'इस शर्ट की कीमत कितनी है?', pronunciation: 'Is shirt ki keemat kitni hai?', category: 'Shopping' },
  { id: '62', english: 'Do you have this in a different color?', hindi: 'क्या यह आपके पास अलग रंग में है?', pronunciation: 'Kya yeh aapke paas alag rang mein hai?', category: 'Shopping' },
  { id: '63', english: 'Can I try this on?', hindi: 'क्या मैं इसे पहनकर देख सकता हूं?', pronunciation: 'Kya main ise pahankar dekh sakta hoon?', category: 'Shopping' },
  { id: '64', english: 'This is too expensive', hindi: 'यह बहुत महंगा है', pronunciation: 'Yeh bahut mehanga hai', category: 'Shopping' },
  { id: '65', english: 'Do you offer any discounts?', hindi: 'क्या आप कोई छूट देते हैं?', pronunciation: 'Kya aap koi chhoot dete hain?', category: 'Shopping' },
  { id: '66', english: 'I\'m just browsing, thank you', hindi: 'मैं सिर्फ देख रहा हूं, धन्यवाद', pronunciation: 'Main sirf dekh raha hoon, dhanyavaad', category: 'Shopping' },
  { id: '67', english: 'Can I get a receipt please?', hindi: 'क्या मुझे रसीद मिल सकती है?', pronunciation: 'Kya mujhe raseed mil sakti hai?', category: 'Shopping' },
  { id: '68', english: 'I would like to return this item', hindi: 'मैं इस वस्तु को वापस करना चाहूंगा', pronunciation: 'Main is vastu ko vaapas karna chahunga', category: 'Shopping' },
  { id: '69', english: 'What is your exchange policy?', hindi: 'आपकी विनिमय नीति क्या है?', pronunciation: 'Aapki vinimay neeti kya hai?', category: 'Shopping' },
  { id: '70', english: 'This doesn\'t fit me properly', hindi: 'यह मुझे ठीक से फिट नहीं होता', pronunciation: 'Yeh mujhe theek se fit nahin hota', category: 'Shopping' },
  
  // Food & Dining (40 lessons)
  { id: '71', english: 'I would like to order some food', hindi: 'मैं कुछ खाना ऑर्डर करना चाहूंगा', pronunciation: 'Main kuch khana order karna chahunga', category: 'Food' },
  { id: '72', english: 'What do you recommend?', hindi: 'आप क्या सिफारिश करते हैं?', pronunciation: 'Aap kya sifarish karte hain?', category: 'Food' },
  { id: '73', english: 'I\'m vegetarian', hindi: 'मैं शाकाहारी हूं', pronunciation: 'Main shakahaari hoon', category: 'Food' },
  { id: '74', english: 'Can I see the menu please?', hindi: 'क्या मैं मेनू देख सकता हूं?', pronunciation: 'Kya main menu dekh sakta hoon?', category: 'Food' },
  { id: '75', english: 'I have a food allergy', hindi: 'मुझे खाद्य एलर्जी है', pronunciation: 'Mujhe khaadya allergy hai', category: 'Food' },
  { id: '76', english: 'This food is delicious', hindi: 'यह खाना स्वादिष्ट है', pronunciation: 'Yeh khana swaadisht hai', category: 'Food' },
  { id: '77', english: 'Can I have the bill please?', hindi: 'क्या मुझे बिल मिल सकता है?', pronunciation: 'Kya mujhe bill mil sakta hai?', category: 'Food' },
  { id: '78', english: 'Do you have any special offers today?', hindi: 'क्या आज कोई विशेष ऑफर है?', pronunciation: 'Kya aaj koi vishesh offer hai?', category: 'Food' },
  { id: '79', english: 'I\'d like a table for four people', hindi: 'मुझे चार लोगों के लिए एक टेबल चाहिए', pronunciation: 'Mujhe char logon ke liye ek table chahiye', category: 'Food' },
  { id: '80', english: 'The service was excellent', hindi: 'सेवा उत्कृष्ट थी', pronunciation: 'Seva utkrisht thi', category: 'Food' },
  
  // Health & Medical (30 lessons)
  { id: '81', english: 'I need to see a doctor', hindi: 'मुझे डॉक्टर से मिलना है', pronunciation: 'Mujhe doctor se milna hai', category: 'Health' },
  { id: '82', english: 'I have a headache', hindi: 'मेरे सिर में दर्द है', pronunciation: 'Mere sir mein dard hai', category: 'Health' },
  { id: '83', english: 'Where is the nearest pharmacy?', hindi: 'सबसे निकटतम फार्मेसी कहां है?', pronunciation: 'Sabse nikattam pharmacy kahaan hai?', category: 'Health' },
  { id: '84', english: 'I need a prescription', hindi: 'मुझे प्रिस्क्रिप्शन चाहिए', pronunciation: 'Mujhe prescription chahiye', category: 'Health' },
  { id: '85', english: 'I\'m feeling dizzy', hindi: 'मुझे चक्कर आ रहा है', pronunciation: 'Mujhe chakkar aa raha hai', category: 'Health' },
  { id: '86', english: 'Do you have any medicine for fever?', hindi: 'क्या आपके पास बुखार की कोई दवा है?', pronunciation: 'Kya aapke paas bukhaar ki koi dawa hai?', category: 'Health' },
  { id: '87', english: 'I need to make an appointment', hindi: 'मुझे अपॉइंटमेंट लेना है', pronunciation: 'Mujhe appointment lena hai', category: 'Health' },
  { id: '88', english: 'My insurance covers this', hindi: 'मेरा बीमा इसे कवर करता है', pronunciation: 'Mera beema ise cover karta hai', category: 'Health' },
  { id: '89', english: 'I have been experiencing pain', hindi: 'मुझे दर्द हो रहा है', pronunciation: 'Mujhe dard ho raha hai', category: 'Health' },
  { id: '90', english: 'When should I take this medicine?', hindi: 'मुझे यह दवा कब लेनी चाहिए?', pronunciation: 'Mujhe yeh dawa kab leni chahiye?', category: 'Health' },
  
  // Education & Learning (30 lessons)
  { id: '91', english: 'I\'m studying English literature', hindi: 'मैं अंग्रेजी साहित्य का अध्ययन कर रहा हूं', pronunciation: 'Main angrezi sahitya ka adhyayan kar raha hoon', category: 'Education' },
  { id: '92', english: 'What is your major?', hindi: 'आपका मुख्य विषय क्या है?', pronunciation: 'Aapka mukhya vishay kya hai?', category: 'Education' },
  { id: '93', english: 'I have an exam next week', hindi: 'अगले हफ्ते मेरी परीक्षा है', pronunciation: 'Agle hafte meri pareeksha hai', category: 'Education' },
  { id: '94', english: 'Can you help me with my homework?', hindi: 'क्या आप मेरे होमवर्क में मदद कर सकते हैं?', pronunciation: 'Kya aap mere homework mein madad kar sakte hain?', category: 'Education' },
  { id: '95', english: 'I need to improve my vocabulary', hindi: 'मुझे अपनी शब्दावली सुधारने की जरूरत है', pronunciation: 'Mujhe apni shabdaavali sudharne ki zaroorat hai', category: 'Education' },
  { id: '96', english: 'The teacher explained it very well', hindi: 'शिक्षक ने इसे बहुत अच्छी तरह से समझाया', pronunciation: 'Shikshak ne ise bahut achhi tarah se samjhaaya', category: 'Education' },
  { id: '97', english: 'I\'m preparing for my final exams', hindi: 'मैं अपनी अंतिम परीक्षाओं की तैयारी कर रहा हूं', pronunciation: 'Main apni antim pareekshaon ki taiyaari kar raha hoon', category: 'Education' },
  { id: '98', english: 'What time is the class?', hindi: 'कक्षा का समय क्या है?', pronunciation: 'Kaksha ka samay kya hai?', category: 'Education' },
  { id: '99', english: 'I missed yesterday\'s lecture', hindi: 'मैं कल का व्याख्यान छूट गया', pronunciation: 'Main kal ka vyaakhyaan chhoot gaya', category: 'Education' },
  { id: '100', english: 'This subject is very interesting', hindi: 'यह विषय बहुत दिलचस्प है', pronunciation: 'Yeh vishay bahut dilchasp hai', category: 'Education' },
  
  // Technology (30 lessons)
  { id: '101', english: 'My computer is not working', hindi: 'मेरा कंप्यूटर काम नहीं कर रहा', pronunciation: 'Mera computer kaam nahin kar raha', category: 'Technology' },
  { id: '102', english: 'I need to charge my phone', hindi: 'मुझे अपना फोन चार्ज करना है', pronunciation: 'Mujhe apna phone charge karna hai', category: 'Technology' },
  { id: '103', english: 'Do you have Wi-Fi here?', hindi: 'क्या यहां वाई-फाई है?', pronunciation: 'Kya yahaan Wi-Fi hai?', category: 'Technology' },
  { id: '104', english: 'What is the password?', hindi: 'पासवर्ड क्या है?', pronunciation: 'Password kya hai?', category: 'Technology' },
  { id: '105', english: 'I forgot my password', hindi: 'मैं अपना पासवर्ड भूल गया', pronunciation: 'Main apna password bhool gaya', category: 'Technology' },
  { id: '106', english: 'Can you send me that file?', hindi: 'क्या आप मुझे वह फाइल भेज सकते हैं?', pronunciation: 'Kya aap mujhe vah file bhej sakte hain?', category: 'Technology' },
  { id: '107', english: 'I need to update my software', hindi: 'मुझे अपना सॉफ्टवेयर अपडेट करना है', pronunciation: 'Mujhe apna software update karna hai', category: 'Technology' },
  { id: '108', english: 'The internet is very slow', hindi: 'इंटरनेट बहुत धीमा है', pronunciation: 'Internet bahut dheema hai', category: 'Technology' },
  { id: '109', english: 'I lost all my data', hindi: 'मैंने अपना सारा डेटा खो दिया', pronunciation: 'Maine apna saara data kho diya', category: 'Technology' },
  { id: '110', english: 'Do you know how to fix this?', hindi: 'क्या आप जानते हैं कि इसे कैसे ठीक करें?', pronunciation: 'Kya aap jaante hain ki ise kaise theek karein?', category: 'Technology' },
  
  // Grammar & Tenses (40 lessons)
  { id: '111', english: 'If I had known, I would have helped', hindi: 'अगर मुझे पता होता, तो मैं मदद करता', pronunciation: 'Agar mujhe pata hota, to main madad karta', category: 'Grammar' },
  { id: '112', english: 'Although it was raining, we went out', hindi: 'हालांकि बारिश हो रही थी, हम बाहर गए', pronunciation: 'Haalaanki baarish ho rahi thi, hum bahar gaye', category: 'Grammar' },
  { id: '113', english: 'I have been working here for five years', hindi: 'मैं पांच साल से यहां काम कर रहा हूं', pronunciation: 'Main paanch saal se yahaan kaam kar raha hoon', category: 'Grammar' },
  { id: '114', english: 'She suggested that we try a different approach', hindi: 'उसने सुझाव दिया कि हम एक अलग दृष्टिकोण आज़माएं', pronunciation: 'Usne sujhaav diya ki hum ek alag drishtikon aazmaayein', category: 'Grammar' },
  { id: '115', english: 'By the time you arrive, I will have finished', hindi: 'जब तक आप पहुंचेंगे, मैं समाप्त कर चुका होऊंगा', pronunciation: 'Jab tak aap pahunchenge, main samaapt kar chuka hounga', category: 'Grammar' },
  { id: '116', english: 'I wish I could speak English fluently', hindi: 'काश मैं धाराप्रवाह अंग्रेजी बोल पाता', pronunciation: 'Kaash main dhaaraapravah angrezi bol paata', category: 'Grammar' },
  { id: '117', english: 'She has already finished her work', hindi: 'उसने अपना काम पहले ही खत्म कर लिया है', pronunciation: 'Usne apna kaam pahle hi khatam kar liya hai', category: 'Grammar' },
  { id: '118', english: 'They will be arriving soon', hindi: 'वे जल्द ही आ रहे होंगे', pronunciation: 'Ve jald hi aa rahe honge', category: 'Grammar' },
  { id: '119', english: 'I was studying when you called', hindi: 'जब आपने फोन किया तो मैं पढ़ रहा था', pronunciation: 'Jab aapne phone kiya to main padh raha tha', category: 'Grammar' },
  { id: '120', english: 'He said that he would come tomorrow', hindi: 'उसने कहा कि वह कल आएगा', pronunciation: 'Usne kaha ki vah kal aayega', category: 'Grammar' },
  
  // Idioms & Expressions (30 lessons)
  { id: '121', english: 'Break a leg! (Good luck)', hindi: 'शुभकामनाएं!', pronunciation: 'Shubhkaamnaayein!', category: 'Idioms' },
  { id: '122', english: 'It\'s raining cats and dogs', hindi: 'बहुत तेज बारिश हो रही है', pronunciation: 'Bahut tez baarish ho rahi hai', category: 'Idioms' },
  { id: '123', english: 'Don\'t cry over spilt milk', hindi: 'जो हो गया उस पर पछताना व्यर्थ है', pronunciation: 'Jo ho gaya us par pachhtaana vyarth hai', category: 'Idioms' },
  { id: '124', english: 'The ball is in your court', hindi: 'अब फैसला आपको करना है', pronunciation: 'Ab faisla aapko karna hai', category: 'Idioms' },
  { id: '125', english: 'Hit the nail on the head', hindi: 'बिल्कुल सही कहना', pronunciation: 'Bilkul sahi kahna', category: 'Idioms' },
  { id: '126', english: 'Once in a blue moon', hindi: 'बहुत कम, कभी-कभार', pronunciation: 'Bahut kam, kabhi-kabhaar', category: 'Idioms' },
  { id: '127', english: 'A piece of cake (very easy)', hindi: 'बहुत आसान', pronunciation: 'Bahut aasaan', category: 'Idioms' },
  { id: '128', english: 'Under the weather (feeling sick)', hindi: 'अस्वस्थ महसूस करना', pronunciation: 'Asvasth mehsoos karna', category: 'Idioms' },
  { id: '129', english: 'Cost an arm and a leg', hindi: 'बहुत महंगा होना', pronunciation: 'Bahut mehanga hona', category: 'Idioms' },
  { id: '130', english: 'Let the cat out of the bag', hindi: 'राज खोल देना', pronunciation: 'Raaz khol dena', category: 'Idioms' },
  
  // Emotions & Feelings (25 lessons)
  { id: '131', english: 'I\'m so happy to hear that', hindi: 'यह सुनकर मुझे बहुत खुशी हुई', pronunciation: 'Yeh sunkar mujhe bahut khushi hui', category: 'Emotions' },
  { id: '132', english: 'I feel nervous about the interview', hindi: 'मुझे इंटरव्यू को लेकर घबराहट हो रही है', pronunciation: 'Mujhe interview ko lekar ghabraahat ho rahi hai', category: 'Emotions' },
  { id: '133', english: 'That makes me angry', hindi: 'इससे मुझे गुस्सा आता है', pronunciation: 'Isse mujhe gussa aata hai', category: 'Emotions' },
  { id: '134', english: 'I\'m really excited about the trip', hindi: 'मैं यात्रा को लेकर बहुत उत्साहित हूं', pronunciation: 'Main yaatra ko lekar bahut utsaahit hoon', category: 'Emotions' },
  { id: '135', english: 'Don\'t worry, everything will be fine', hindi: 'चिंता मत करो, सब ठीक हो जाएगा', pronunciation: 'Chinta mat karo, sab theek ho jayega', category: 'Emotions' },
  { id: '136', english: 'I feel disappointed', hindi: 'मुझे निराशा हो रही है', pronunciation: 'Mujhe niraasha ho rahi hai', category: 'Emotions' },
  { id: '137', english: 'That was surprising', hindi: 'यह आश्चर्यजनक था', pronunciation: 'Yeh aashcharyajanak tha', category: 'Emotions' },
  { id: '138', english: 'I\'m proud of you', hindi: 'मुझे तुम पर गर्व है', pronunciation: 'Mujhe tum par garv hai', category: 'Emotions' },
  { id: '139', english: 'I feel confused', hindi: 'मैं भ्रमित महसूस कर रहा हूं', pronunciation: 'Main bhramit mehsoos kar raha hoon', category: 'Emotions' },
  { id: '140', english: 'This is so frustrating', hindi: 'यह बहुत निराशाजनक है', pronunciation: 'Yeh bahut niraashajanak hai', category: 'Emotions' },
  
  // Numbers & Money (25 lessons)
  { id: '141', english: 'Twenty-five percent discount', hindi: 'पच्चीस प्रतिशत की छूट', pronunciation: 'Pachchis pratishat ki chhoot', category: 'Numbers' },
  { id: '142', english: 'The deadline is in three weeks', hindi: 'समय सीमा तीन सप्ताह में है', pronunciation: 'Samay seema teen saptaah mein hai', category: 'Numbers' },
  { id: '143', english: 'I\'ll be there in fifteen minutes', hindi: 'मैं पंद्रह मिनट में वहां पहुंच जाऊंगा', pronunciation: 'Main pandrah minute mein vahaan pahunch jaunga', category: 'Numbers' },
  { id: '144', english: 'The temperature is thirty degrees', hindi: 'तापमान तीस डिग्री है', pronunciation: 'Taapmaan tees degree hai', category: 'Numbers' },
  { id: '145', english: 'It costs around fifty dollars', hindi: 'इसकी कीमत लगभग पचास डॉलर है', pronunciation: 'Iski keemat lagbhag pachaas dollar hai', category: 'Numbers' },
  { id: '146', english: 'Half past two in the afternoon', hindi: 'दोपहर ढाई बजे', pronunciation: 'Dopahar dhai baje', category: 'Numbers' },
  { id: '147', english: 'Can you give me change for a hundred?', hindi: 'क्या आप मुझे सौ का बदला दे सकते हैं?', pronunciation: 'Kya aap mujhe sau ka badla de sakte hain?', category: 'Numbers' },
  { id: '148', english: 'The price increased by twenty percent', hindi: 'कीमत में बीस प्रतिशत की वृद्धि हुई', pronunciation: 'Keemat mein bees pratishat ki vriddhi hui', category: 'Numbers' },
  { id: '149', english: 'I need approximately two thousand rupees', hindi: 'मुझे लगभग दो हजार रुपये चाहिए', pronunciation: 'Mujhe lagbhag do hazaar rupaye chahiye', category: 'Numbers' },
  { id: '150', english: 'One-third of the population', hindi: 'जनसंख्या का एक तिहाई', pronunciation: 'Jansankhya ka ek tihaai', category: 'Numbers' },
  
  // Weather & Nature (20 lessons)
  { id: '151', english: 'It\'s a beautiful sunny day', hindi: 'यह एक सुंदर धूप वाला दिन है', pronunciation: 'Yeh ek sundar dhoop wala din hai', category: 'Weather' },
  { id: '152', english: 'It looks like it\'s going to rain', hindi: 'ऐसा लगता है कि बारिश होने वाली है', pronunciation: 'Aisa lagta hai ki baarish hone waali hai', category: 'Weather' },
  { id: '153', english: 'The weather forecast says it will be cloudy', hindi: 'मौसम पूर्वानुमान कहता है कि बादल छाए रहेंगे', pronunciation: 'Mausam poorvaanumaan kahta hai ki baadal chhaaye rahenge', category: 'Weather' },
  { id: '154', english: 'It\'s freezing cold today', hindi: 'आज बहुत ठंड है', pronunciation: 'Aaj bahut thand hai', category: 'Weather' },
  { id: '155', english: 'The temperature has dropped significantly', hindi: 'तापमान में काफी गिरावट आई है', pronunciation: 'Taapmaan mein kaafi giraavat aayi hai', category: 'Weather' },
  { id: '156', english: 'What a pleasant breeze!', hindi: 'कितनी सुहानी हवा है!', pronunciation: 'Kitni suhaani hawa hai!', category: 'Weather' },
  { id: '157', english: 'The humidity is very high', hindi: 'आर्द्रता बहुत अधिक है', pronunciation: 'Aardrata bahut adhik hai', category: 'Weather' },
  { id: '158', english: 'We\'re expecting a storm tonight', hindi: 'आज रात तूफान आने की उम्मीद है', pronunciation: 'Aaj raat toofaan aane ki ummeed hai', category: 'Weather' },
  { id: '159', english: 'The flowers are blooming beautifully', hindi: 'फूल बहुत सुंदर खिल रहे हैं', pronunciation: 'Phool bahut sundar khil rahe hain', category: 'Weather' },
  { id: '160', english: 'Summer is my favorite season', hindi: 'गर्मी मेरी पसंदीदा ऋतु है', pronunciation: 'Garmi meri pasandeeda ritu hai', category: 'Weather' },
  
  // Family & Relationships (20 lessons)
  { id: '161', english: 'I live with my parents', hindi: 'मैं अपने माता-पिता के साथ रहता हूं', pronunciation: 'Main apne maata-pita ke saath rahta hoon', category: 'Family' },
  { id: '162', english: 'My brother is getting married next month', hindi: 'अगले महीने मेरे भाई की शादी है', pronunciation: 'Agle mahine mere bhai ki shaadi hai', category: 'Family' },
  { id: '163', english: 'She is my best friend', hindi: 'वह मेरी सबसे अच्छी दोस्त है', pronunciation: 'Vah meri sabse achhi dost hai', category: 'Family' },
  { id: '164', english: 'We\'ve been friends for ten years', hindi: 'हम दस साल से दोस्त हैं', pronunciation: 'Hum das saal se dost hain', category: 'Family' },
  { id: '165', english: 'My grandparents live in the village', hindi: 'मेरे दादा-दादी गांव में रहते हैं', pronunciation: 'Mere daada-daadi gaon mein rahte hain', category: 'Family' },
  { id: '166', english: 'I have two younger sisters', hindi: 'मेरी दो छोटी बहनें हैं', pronunciation: 'Meri do chhoti bahnen hain', category: 'Family' },
  { id: '167', english: 'My family is very supportive', hindi: 'मेरा परिवार बहुत सहयोगी है', pronunciation: 'Mera parivaar bahut sahyogi hai', category: 'Family' },
  { id: '168', english: 'We usually have dinner together', hindi: 'हम आमतौर पर साथ में रात का खाना खाते हैं', pronunciation: 'Hum aamtaur par saath mein raat ka khana khaate hain', category: 'Family' },
  { id: '169', english: 'My cousin is studying abroad', hindi: 'मेरा चचेरा भाई विदेश में पढ़ रहा है', pronunciation: 'Mera chachera bhai videsh mein padh raha hai', category: 'Family' },
  { id: '170', english: 'Family is everything to me', hindi: 'परिवार मेरे लिए सब कुछ है', pronunciation: 'Parivaar mere liye sab kuch hai', category: 'Family' },
  
  // Sports & Hobbies (20 lessons)
  { id: '171', english: 'I enjoy playing cricket', hindi: 'मुझे क्रिकेट खेलना पसंद है', pronunciation: 'Mujhe cricket khelna pasand hai', category: 'Hobbies' },
  { id: '172', english: 'My hobby is reading books', hindi: 'मेरा शौक किताबें पढ़ना है', pronunciation: 'Mera shauk kitaabein padhna hai', category: 'Hobbies' },
  { id: '173', english: 'I go to the gym regularly', hindi: 'मैं नियमित रूप से जिम जाता हूं', pronunciation: 'Main niyamit roop se gym jaata hoon', category: 'Hobbies' },
  { id: '174', english: 'She loves painting and drawing', hindi: 'उसे पेंटिंग और ड्रॉइंग बहुत पसंद है', pronunciation: 'Use painting aur drawing bahut pasand hai', category: 'Hobbies' },
  { id: '175', english: 'Do you play any musical instrument?', hindi: 'क्या आप कोई वाद्य यंत्र बजाते हैं?', pronunciation: 'Kya aap koi vaadya yantra bajaate hain?', category: 'Hobbies' },
  { id: '176', english: 'I like to travel in my free time', hindi: 'मुझे अपने खाली समय में यात्रा करना पसंद है', pronunciation: 'Mujhe apne khaali samay mein yaatra karna pasand hai', category: 'Hobbies' },
  { id: '177', english: 'Photography is my passion', hindi: 'फोटोग्राफी मेरा जुनून है', pronunciation: 'Photography mera junoon hai', category: 'Hobbies' },
  { id: '178', english: 'I watch movies every weekend', hindi: 'मैं हर सप्ताहांत फिल्में देखता हूं', pronunciation: 'Main har saptahaant filmein dekhta hoon', category: 'Hobbies' },
  { id: '179', english: 'Cooking is a great stress reliever', hindi: 'खाना बनाना तनाव दूर करने का अच्छा तरीका है', pronunciation: 'Khana banaana tanaav door karne ka achha tareeka hai', category: 'Hobbies' },
  { id: '180', english: 'I love listening to music', hindi: 'मुझे संगीत सुनना बहुत पसंद है', pronunciation: 'Mujhe sangeet sunna bahut pasand hai', category: 'Hobbies' },
  
  // Advanced Conversations (20 lessons)
  { id: '181', english: 'In my opinion, this is the best solution', hindi: 'मेरी राय में, यह सबसे अच्छा समाधान है', pronunciation: 'Meri raay mein, yeh sabse achha samadhaan hai', category: 'Advanced' },
  { id: '182', english: 'From my perspective, we should reconsider', hindi: 'मेरे दृष्टिकोण से, हमें पुनर्विचार करना चाहिए', pronunciation: 'Mere drishtikon se, hamein punarvichaar karna chahiye', category: 'Advanced' },
  { id: '183', english: 'The situation is more complicated than it appears', hindi: 'स्थिति जितनी दिखती है उससे अधिक जटिल है', pronunciation: 'Sthiti jitni dikhti hai usse adhik jatil hai', category: 'Advanced' },
  { id: '184', english: 'We need to address this issue immediately', hindi: 'हमें इस मुद्दे को तुरंत संबोधित करने की आवश्यकता है', pronunciation: 'Hamein is mudde ko turant sambodhit karne ki aavashyakta hai', category: 'Advanced' },
  { id: '185', english: 'That\'s a valid point to consider', hindi: 'यह विचार करने के लिए एक वैध बिंदु है', pronunciation: 'Yeh vichaar karne ke liye ek vaidh bindu hai', category: 'Advanced' },
  { id: '186', english: 'I completely agree with your assessment', hindi: 'मैं आपके आकलन से पूरी तरह सहमत हूं', pronunciation: 'Main aapke aakalan se poori tarah sahamat hoon', category: 'Advanced' },
  { id: '187', english: 'We should take a more strategic approach', hindi: 'हमें अधिक रणनीतिक दृष्टिकोण अपनाना चाहिए', pronunciation: 'Hamein adhik ranneetik drishtikon apnaana chahiye', category: 'Advanced' },
  { id: '188', english: 'The implications of this decision are significant', hindi: 'इस निर्णय के निहितार्थ महत्वपूर्ण हैं', pronunciation: 'Is nirnay ke nihitaarth mahatvapoorn hain', category: 'Advanced' },
  { id: '189', english: 'Let\'s analyze the pros and cons', hindi: 'चलिए फायदे और नुकसान का विश्लेषण करते हैं', pronunciation: 'Chaliye faayade aur nuks aan ka vishleshan karte hain', category: 'Advanced' },
  { id: '190', english: 'This requires careful consideration', hindi: 'इसके लिए सावधानीपूर्वक विचार की आवश्यकता है', pronunciation: 'Iske liye saavadhaneepoorvak vichaar ki aavashyakta hai', category: 'Advanced' },
  
  // Bonus Essential Phrases (10 lessons)
  { id: '191', english: 'I\'m looking forward to working with you', hindi: 'मैं आपके साथ काम करने के लिए उत्सुक हूं', pronunciation: 'Main aapke saath kaam karne ke liye utsuk hoon', category: 'Greetings' },
  { id: '192', english: 'Please feel free to contact me anytime', hindi: 'कृपया मुझसे किसी भी समय संपर्क करने में संकोच न करें', pronunciation: 'Kripya mujhse kisi bhi samay samparkKarne mein sankoch na karein', category: 'Daily' },
  { id: '193', english: 'I appreciate your patience', hindi: 'मैं आपके धैर्य की सराहना करता हूं', pronunciation: 'Main aapke dhairya ki saraahna karta hoon', category: 'Greetings' },
  { id: '194', english: 'Could you please clarify that?', hindi: 'क्या आप कृपया इसे स्पष्ट कर सकते हैं?', pronunciation: 'Kya aap kripya ise spasht kar sakte hain?', category: 'Daily' },
  { id: '195', english: 'I\'m interested in learning more about this', hindi: 'मुझे इसके बारे में और जानने में दिलचस्पी है', pronunciation: 'Mujhe iske baare mein aur jaanne mein dilchaspi hai', category: 'Education' },
  { id: '196', english: 'Thank you for your time and consideration', hindi: 'आपके समय और विचार के लिए धन्यवाद', pronunciation: 'Aapke samay aur vichaar ke liye dhanyavaad', category: 'Business' },
  { id: '197', english: 'I would be happy to assist you', hindi: 'मुझे आपकी सहायता करके खुशी होगी', pronunciation: 'Mujhe aapki sahaayata karke khushi hogi', category: 'Daily' },
  { id: '198', english: 'This is exactly what I was looking for', hindi: 'यह बिल्कुल वही है जिसे मैं ढूंढ रहा था', pronunciation: 'Yeh bilkul vahi hai jise main dhoondh raha tha', category: 'Shopping' },
  { id: '199', english: 'I\'m confident we can find a solution', hindi: 'मुझे विश्वास है कि हम एक समाधान खोज सकते हैं', pronunciation: 'Mujhe vishwaas hai ki hum ek samadhaan khoj sakte hain', category: 'Business' },
  { id: '200', english: 'It was a pleasure speaking with you', hindi: 'आपसे बात करके खुशी हुई', pronunciation: 'Aapse baat karke khushi hui', category: 'Greetings' },
];
