// Additional 500 lessons - Part 3: Extended Content
import { Lesson } from './lessonData';

export const lessonsPart3: Lesson[] = [
  // Extended Daily Conversations (100 lessons)
  { id: '501', english: 'Would you mind helping me with this task?', hindi: 'क्या आप इस काम में मेरी मदद करेंगे?', pronunciation: 'Kya aap is kaam mein meri madad karenge?', category: 'Daily' },
  { id: '502', english: 'I appreciate your patience', hindi: 'मैं आपके धैर्य की सराहना करता हूं', pronunciation: 'Main aapke dhairya ki sarahna karta hoon', category: 'Daily' },
  { id: '503', english: 'Let me know if you need anything', hindi: 'अगर आपको कुछ चाहिए तो मुझे बताएं', pronunciation: 'Agar aapko kuch chahiye to mujhe bataayein', category: 'Daily' },
  { id: '504', english: 'I completely understand your concern', hindi: 'मैं आपकी चिंता को पूरी तरह समझता हूं', pronunciation: 'Main aapki chinta ko poori tarah samajhta hoon', category: 'Daily' },
  { id: '505', english: 'That sounds reasonable to me', hindi: 'यह मुझे उचित लगता है', pronunciation: 'Yeh mujhe uchit lagta hai', category: 'Daily' },
  { id: '506', english: 'I need to reschedule our appointment', hindi: 'मुझे हमारी मुलाकात को पुनर्निर्धारित करना है', pronunciation: 'Mujhe hamaari mulaakat ko punarnidhaarit karna hai', category: 'Daily' },
  { id: '507', english: 'Could you repeat that please?', hindi: 'क्या आप इसे दोहरा सकते हैं?', pronunciation: 'Kya aap ise dohra sakte hain?', category: 'Daily' },
  { id: '508', english: 'I\'ll get back to you on that', hindi: 'मैं इस पर आपसे संपर्क करूंगा', pronunciation: 'Main is par aapse sampark karunga', category: 'Daily' },
  { id: '509', english: 'What would be a good time for you?', hindi: 'आपके लिए अच्छा समय क्या होगा?', pronunciation: 'Aapke liye achha samay kya hoga?', category: 'Daily' },
  { id: '510', english: 'I\'m afraid I can\'t make it', hindi: 'मुझे डर है कि मैं यह नहीं कर पाऊंगा', pronunciation: 'Mujhe dar hai ki main yeh nahin kar paaunga', category: 'Daily' },
  { id: '511', english: 'That works perfectly for me', hindi: 'यह मेरे लिए बिल्कुल सही है', pronunciation: 'Yeh mere liye bilkul sahi hai', category: 'Daily' },
  { id: '512', english: 'I was wondering if you could help', hindi: 'मैं सोच रहा था कि क्या आप मदद कर सकते हैं', pronunciation: 'Main soch raha tha ki kya aap madad kar sakte hain', category: 'Daily' },
  { id: '513', english: 'Let me check my schedule', hindi: 'मुझे अपना शेड्यूल चेक करने दें', pronunciation: 'Mujhe apna schedule check karne dein', category: 'Daily' },
  { id: '514', english: 'I\'ll keep you posted', hindi: 'मैं आपको सूचित रखूंगा', pronunciation: 'Main aapko soochit rakhunga', category: 'Daily' },
  { id: '515', english: 'Thanks for letting me know', hindi: 'मुझे बताने के लिए धन्यवाद', pronunciation: 'Mujhe bataane ke liye dhanyavaad', category: 'Daily' },
  { id: '516', english: 'I have a quick question', hindi: 'मेरे पास एक छोटा सा सवाल है', pronunciation: 'Mere paas ek chhota sa savaal hai', category: 'Daily' },
  { id: '517', english: 'Could you do me a favor?', hindi: 'क्या आप मुझ पर एक उपकार कर सकते हैं?', pronunciation: 'Kya aap mujh par ek upkaar kar sakte hain?', category: 'Daily' },
  { id: '518', english: 'I\'m running a bit late', hindi: 'मुझे थोड़ी देर हो रही है', pronunciation: 'Mujhe thodi der ho rahi hai', category: 'Daily' },
  { id: '519', english: 'No worries, take your time', hindi: 'कोई बात नहीं, अपना समय लें', pronunciation: 'Koi baat nahin, apna samay lein', category: 'Daily' },
  { id: '520', english: 'I\'ll be there in ten minutes', hindi: 'मैं दस मिनट में वहां पहुंच जाऊंगा', pronunciation: 'Main das minute mein vahaan pahunch jaunga', category: 'Daily' },
  { id: '521', english: 'Would it be possible to change the time?', hindi: 'क्या समय बदलना संभव होगा?', pronunciation: 'Kya samay badalna sambhav hoga?', category: 'Daily' },
  { id: '522', english: 'I really appreciate your understanding', hindi: 'मैं वास्तव में आपकी समझ की सराहना करता हूं', pronunciation: 'Main vaastav mein aapki samajh ki sarahna karta hoon', category: 'Daily' },
  { id: '523', english: 'That\'s very kind of you', hindi: 'यह आपकी बहुत दयालुता है', pronunciation: 'Yeh aapki bahut dayaaluta hai', category: 'Daily' },
  { id: '524', english: 'I didn\'t quite catch that', hindi: 'मुझे वह ठीक से समझ नहीं आया', pronunciation: 'Mujhe vah theek se samajh nahin aaya', category: 'Daily' },
  { id: '525', english: 'Can you speak up a little?', hindi: 'क्या आप थोड़ा जोर से बोल सकते हैं?', pronunciation: 'Kya aap thoda jor se bol sakte hain?', category: 'Daily' },
  { id: '526', english: 'I\'m sorry for the inconvenience', hindi: 'असुविधा के लिए मुझे खेद है', pronunciation: 'Asuvidha ke liye mujhe khed hai', category: 'Daily' },
  { id: '527', english: 'No problem at all', hindi: 'कोई समस्या नहीं है', pronunciation: 'Koi samasya nahin hai', category: 'Daily' },
  { id: '528', english: 'I\'ll take care of it right away', hindi: 'मैं इसका तुरंत ध्यान रखूंगा', pronunciation: 'Main iska turant dhyaan rakhunga', category: 'Daily' },
  { id: '529', english: 'When would be convenient for you?', hindi: 'आपके लिए कब सुविधाजनक होगा?', pronunciation: 'Aapke liye kab suvidhaajanak hoga?', category: 'Daily' },
  { id: '530', english: 'I\'m flexible with timing', hindi: 'मैं समय के साथ लचीला हूं', pronunciation: 'Main samay ke saath lacheela hoon', category: 'Daily' },
  { id: '531', english: 'Let\'s touch base next week', hindi: 'आइए अगले हफ्ते संपर्क करें', pronunciation: 'Aaiye agle hafte sampark karein', category: 'Daily' },
  { id: '532', english: 'I look forward to hearing from you', hindi: 'मैं आपसे सुनने की प्रतीक्षा कर रहा हूं', pronunciation: 'Main aapse sunne ki prateeksha kar raha hoon', category: 'Daily' },
  { id: '533', english: 'Please don\'t hesitate to ask', hindi: 'कृपया पूछने में संकोच न करें', pronunciation: 'Kripya poochhne mein sankoch na karein', category: 'Daily' },
  { id: '534', english: 'I\'ll make sure it gets done', hindi: 'मैं सुनिश्चित करूंगा कि यह हो जाए', pronunciation: 'Main sunishchit karunga ki yeh ho jaaye', category: 'Daily' },
  { id: '535', english: 'That would be great', hindi: 'यह बहुत अच्छा होगा', pronunciation: 'Yeh bahut achha hoga', category: 'Daily' },
  { id: '536', english: 'I\'m glad we could work this out', hindi: 'मुझे खुशी है कि हम इसे सुलझा सके', pronunciation: 'Mujhe khushi hai ki hum ise suljha sake', category: 'Daily' },
  { id: '537', english: 'Is there anything else I can help with?', hindi: 'क्या कुछ और है जिसमें मैं मदद कर सकता हूं?', pronunciation: 'Kya kuch aur hai jismein main madad kar sakta hoon?', category: 'Daily' },
  { id: '538', english: 'That\'s all for now', hindi: 'अभी के लिए बस इतना ही', pronunciation: 'Abhi ke liye bas itna hi', category: 'Daily' },
  { id: '539', english: 'I\'ll send you the details', hindi: 'मैं आपको विवरण भेजूंगा', pronunciation: 'Main aapko vivaran bhejunga', category: 'Daily' },
  { id: '540', english: 'Could you please confirm?', hindi: 'क्या आप कृपया पुष्टि कर सकते हैं?', pronunciation: 'Kya aap kripya pushti kar sakte hain?', category: 'Daily' },
  { id: '541', english: 'I wanted to follow up on our discussion', hindi: 'मैं हमारी चर्चा पर फॉलो अप करना चाहता था', pronunciation: 'Main hamaari charcha par follow up karna chaahta tha', category: 'Daily' },
  { id: '542', english: 'Just checking in to see how things are going', hindi: 'बस यह देखने के लिए कि चीजें कैसी चल रही हैं', pronunciation: 'Bas yeh dekhne ke liye ki chee zein kaisi chal rahi hain', category: 'Daily' },
  { id: '543', english: 'Everything is under control', hindi: 'सब कुछ नियंत्रण में है', pronunciation: 'Sab kuch niyantran mein hai', category: 'Daily' },
  { id: '544', english: 'I\'ll keep you in the loop', hindi: 'मैं आपको सूचित रखूंगा', pronunciation: 'Main aapko soochit rakhunga', category: 'Daily' },
  { id: '545', english: 'Thanks for the heads up', hindi: 'सूचना के लिए धन्यवाद', pronunciation: 'Soochna ke liye dhanyavaad', category: 'Daily' },
  { id: '546', english: 'I appreciate you taking the time', hindi: 'मैं समय निकालने के लिए आपकी सराहना करता हूं', pronunciation: 'Main samay nikaalne ke liye aapki sarahna karta hoon', category: 'Daily' },
  { id: '547', english: 'No rush, whenever you\'re ready', hindi: 'कोई जल्दी नहीं, जब आप तैयार हों', pronunciation: 'Koi jaldi nahin, jab aap taiyaar hon', category: 'Daily' },
  { id: '548', english: 'I\'ll try my best', hindi: 'मैं अपनी पूरी कोशिश करूंगा', pronunciation: 'Main apni poori koshish karunga', category: 'Daily' },
  { id: '549', english: 'That makes sense', hindi: 'यह समझ में आता है', pronunciation: 'Yeh samajh mein aata hai', category: 'Daily' },
  { id: '550', english: 'I see what you mean', hindi: 'मैं समझता हूं कि आपका क्या मतलब है', pronunciation: 'Main samajhta hoon ki aapka kya matlab hai', category: 'Daily' },
  { id: '551', english: 'Could you elaborate on that?', hindi: 'क्या आप इस पर विस्तार से बता सकते हैं?', pronunciation: 'Kya aap is par vistaar se bata sakte hain?', category: 'Daily' },
  { id: '552', english: 'I\'d be happy to explain', hindi: 'मुझे समझाने में खुशी होगी', pronunciation: 'Mujhe samjhaane mein khushi hogi', category: 'Daily' },
  { id: '553', english: 'Let me think about it', hindi: 'मुझे इसके बारे में सोचने दें', pronunciation: 'Mujhe iske baare mein sochne dein', category: 'Daily' },
  { id: '554', english: 'That\'s a valid point', hindi: 'यह एक वैध बिंदु है', pronunciation: 'Yeh ek vaidh bindu hai', category: 'Daily' },
  { id: '555', english: 'I hadn\'t thought of it that way', hindi: 'मैंने इस तरह से नहीं सोचा था', pronunciation: 'Maine is tarah se nahin socha tha', category: 'Daily' },
  { id: '556', english: 'You have a good point there', hindi: 'आपकी बात सही है', pronunciation: 'Aapki baat sahi hai', category: 'Daily' },
  { id: '557', english: 'I can\'t agree more', hindi: 'मैं अधिक सहमत नहीं हो सकता', pronunciation: 'Main adhik sahamat nahin ho sakta', category: 'Daily' },
  { id: '558', english: 'I respectfully disagree', hindi: 'मैं सम्मानपूर्वक असहमत हूं', pronunciation: 'Main sammaanpoorvak asahamat hoon', category: 'Daily' },
  { id: '559', english: 'Let\'s agree to disagree', hindi: 'चलिए असहमत होने पर सहमत हैं', pronunciation: 'Chaliye asahamat hone par sahamat hain', category: 'Daily' },
  { id: '560', english: 'I\'m open to suggestions', hindi: 'मैं सुझावों के लिए खुला हूं', pronunciation: 'Main sujhaavon ke liye khula hoon', category: 'Daily' },
  { id: '561', english: 'What do you think about this?', hindi: 'आप इसके बारे में क्या सोचते हैं?', pronunciation: 'Aap iske baare mein kya sochte hain?', category: 'Daily' },
  { id: '562', english: 'I value your opinion', hindi: 'मैं आपकी राय को महत्व देता हूं', pronunciation: 'Main aapki raay ko mahatva deta hoon', category: 'Daily' },
  { id: '563', english: 'Let me get back to you on that', hindi: 'मुझे इस पर आपसे वापस संपर्क करने दें', pronunciation: 'Mujhe is par aapse vaapas sampark karne dein', category: 'Daily' },
  { id: '564', english: 'I need some time to process this', hindi: 'मुझे इसे संसाधित करने के लिए कुछ समय चाहिए', pronunciation: 'Mujhe ise sansaadhit karne ke liye kuch samay chahiye', category: 'Daily' },
  { id: '565', english: 'Can we discuss this later?', hindi: 'क्या हम इस पर बाद में चर्चा कर सकते हैं?', pronunciation: 'Kya hum is par baad mein charcha kar sakte hain?', category: 'Daily' },
  { id: '566', english: 'I\'m tied up at the moment', hindi: 'मैं इस समय व्यस्त हूं', pronunciation: 'Main is samay vyast hoon', category: 'Daily' },
  { id: '567', english: 'I\'ll circle back with you', hindi: 'मैं आपके साथ वापस लौटूंगा', pronunciation: 'Main aapke saath vaapas lautunga', category: 'Daily' },
  { id: '568', english: 'Thanks for being patient', hindi: 'धैर्यवान होने के लिए धन्यवाद', pronunciation: 'Dhairyavaan hone ke liye dhanyavaad', category: 'Daily' },
  { id: '569', english: 'I completely forgot about that', hindi: 'मैं इसके बारे में पूरी तरह भूल गया', pronunciation: 'Main iske baare mein poori tarah bhool gaya', category: 'Daily' },
  { id: '570', english: 'My apologies for the oversight', hindi: 'निगरानी के लिए मेरी माफी', pronunciation: 'Nigarani ke liye meri maafi', category: 'Daily' },
  { id: '571', english: 'It slipped my mind', hindi: 'यह मेरे दिमाग से निकल गया', pronunciation: 'Yeh mere dimaag se nikal gaya', category: 'Daily' },
  { id: '572', english: 'I\'ll make a note of that', hindi: 'मैं इसका नोट बना लूंगा', pronunciation: 'Main iska note bana lunga', category: 'Daily' },
  { id: '573', english: 'Could you remind me later?', hindi: 'क्या आप मुझे बाद में याद दिला सकते हैं?', pronunciation: 'Kya aap mujhe baad mein yaad dila sakte hain?', category: 'Daily' },
  { id: '574', english: 'I\'ll set a reminder', hindi: 'मैं एक अनुस्मारक सेट करूंगा', pronunciation: 'Main ek anusmaarak set karunga', category: 'Daily' },
  { id: '575', english: 'Just to clarify', hindi: 'बस स्पष्ट करने के लिए', pronunciation: 'Bas spasht karne ke liye', category: 'Daily' },
  { id: '576', english: 'If I understand correctly', hindi: 'अगर मैं सही समझ रहा हूं', pronunciation: 'Agar main sahi samajh raha hoon', category: 'Daily' },
  { id: '577', english: 'Please correct me if I\'m wrong', hindi: 'अगर मैं गलत हूं तो कृपया मुझे सुधारें', pronunciation: 'Agar main galat hoon to kripya mujhe sudhaarein', category: 'Daily' },
  { id: '578', english: 'That\'s not exactly what I meant', hindi: 'मेरा मतलब बिल्कुल यह नहीं था', pronunciation: 'Mera matlab bilkul yeh nahin tha', category: 'Daily' },
  { id: '579', english: 'Let me rephrase that', hindi: 'मुझे इसे फिर से कहने दें', pronunciation: 'Mujhe ise phir se kahne dein', category: 'Daily' },
  { id: '580', english: 'In other words', hindi: 'दूसरे शब्दों में', pronunciation: 'Doosre shabdon mein', category: 'Daily' },
  { id: '581', english: 'To put it simply', hindi: 'सीधे शब्दों में कहें तो', pronunciation: 'Seedhe shabdon mein kahein to', category: 'Daily' },
  { id: '582', english: 'Long story short', hindi: 'संक्षेप में', pronunciation: 'Sankshep mein', category: 'Daily' },
  { id: '583', english: 'The bottom line is', hindi: 'मूल बात यह है', pronunciation: 'Mool baat yeh hai', category: 'Daily' },
  { id: '584', english: 'At the end of the day', hindi: 'दिन के अंत में', pronunciation: 'Din ke ant mein', category: 'Daily' },
  { id: '585', english: 'All things considered', hindi: 'सब बातों को ध्यान में रखते हुए', pronunciation: 'Sab baaton ko dhyaan mein rakhte hue', category: 'Daily' },
  { id: '586', english: 'From my perspective', hindi: 'मेरे दृष्टिकोण से', pronunciation: 'Mere drishtikon se', category: 'Daily' },
  { id: '587', english: 'As far as I know', hindi: 'जहां तक मुझे पता है', pronunciation: 'Jahaan tak mujhe pata hai', category: 'Daily' },
  { id: '588', english: 'To the best of my knowledge', hindi: 'मेरी जानकारी के अनुसार', pronunciation: 'Meri jaankaari ke anusaar', category: 'Daily' },
  { id: '589', english: 'I might be mistaken, but', hindi: 'मैं गलत हो सकता हूं, लेकिन', pronunciation: 'Main galat ho sakta hoon, lekin', category: 'Daily' },
  { id: '590', english: 'Don\'t quote me on this', hindi: 'इस पर मेरा हवाला न दें', pronunciation: 'Is par mera havaala na dein', category: 'Daily' },
  { id: '591', english: 'Take it with a grain of salt', hindi: 'इसे हल्के में लें', pronunciation: 'Ise halke mein lein', category: 'Daily' },
  { id: '592', english: 'It\'s worth considering', hindi: 'यह विचार करने योग्य है', pronunciation: 'Yeh vichaar karne yogya hai', category: 'Daily' },
  { id: '593', english: 'That\'s something to think about', hindi: 'यह सोचने लायक बात है', pronunciation: 'Yeh sochne laayak baat hai', category: 'Daily' },
  { id: '594', english: 'I\'ll give it some thought', hindi: 'मैं इस पर कुछ विचार करूंगा', pronunciation: 'Main is par kuch vichaar karunga', category: 'Daily' },
  { id: '595', english: 'That\'s an interesting perspective', hindi: 'यह एक दिलचस्प दृष्टिकोण है', pronunciation: 'Yeh ek dilchasp drishtikon hai', category: 'Daily' },
  { id: '596', english: 'I never looked at it that way', hindi: 'मैंने इसे कभी इस तरह से नहीं देखा', pronunciation: 'Maine ise kabhi is tarah se nahin dekha', category: 'Daily' },
  { id: '597', english: 'You\'ve given me something to consider', hindi: 'आपने मुझे विचार करने के लिए कुछ दिया है', pronunciation: 'Aapne mujhe vichaar karne ke liye kuch diya hai', category: 'Daily' },
  { id: '598', english: 'I\'ll bear that in mind', hindi: 'मैं इसे ध्यान में रखूंगा', pronunciation: 'Main ise dhyaan mein rakhunga', category: 'Daily' },
  { id: '599', english: 'Thanks for bringing that up', hindi: 'इसे उठाने के लिए धन्यवाद', pronunciation: 'Ise uthaane ke liye dhanyavaad', category: 'Daily' },
  { id: '600', english: 'That\'s a fair assessment', hindi: 'यह एक उचित मूल्यांकन है', pronunciation: 'Yeh ek uchit moolyaankan hai', category: 'Daily' },

  // Extended Business Communication (100 lessons)
  { id: '601', english: 'We need to align our objectives', hindi: 'हमें अपने उद्देश्यों को संरेखित करने की आवश्यकता है', pronunciation: 'Hamein apne uddeshyon ko sanrekhit karne ki aavashyakta hai', category: 'Business' },
  { id: '602', english: 'Let\'s leverage our strengths', hindi: 'चलिए अपनी ताकत का लाभ उठाएं', pronunciation: 'Chaliye apni taakat ka laabh uthaayein', category: 'Business' },
  { id: '603', english: 'The quarterly results exceeded expectations', hindi: 'त्रैमासिक परिणाम अपेक्षाओं से अधिक रहे', pronunciation: 'Traimaasik parinaam apekshaon se adhik rahe', category: 'Business' },
  { id: '604', english: 'We\'re implementing a new strategy', hindi: 'हम एक नई रणनीति लागू कर रहे हैं', pronunciation: 'Hum ek nayi ranneeti laagu kar rahe hain', category: 'Business' },
  { id: '605', english: 'The stakeholders have approved the plan', hindi: 'हितधारकों ने योजना को मंजूरी दे दी है', pronunciation: 'Hitdhaarakon ne yojana ko manjoori de di hai', category: 'Business' },
  { id: '606', english: 'We need to optimize our resources', hindi: 'हमें अपने संसाधनों को अनुकूलित करने की आवश्यकता है', pronunciation: 'Hamein apne sansaadhanon ko anukoolit karne ki aavashyakta hai', category: 'Business' },
  { id: '607', english: 'The market trends are shifting', hindi: 'बाजार के रुझान बदल रहे हैं', pronunciation: 'Baazaar ke ruzhaan badal rahe hain', category: 'Business' },
  { id: '608', english: 'We should conduct a SWOT analysis', hindi: 'हमें एक SWOT विश्लेषण करना चाहिए', pronunciation: 'Hamein ek SWOT vishleshan karna chahiye', category: 'Business' },
  { id: '609', english: 'The ROI is quite impressive', hindi: 'ROI काफी प्रभावशाली है', pronunciation: 'ROI kaafi prabhaavashali hai', category: 'Business' },
  { id: '610', english: 'Let\'s explore potential synergies', hindi: 'चलिए संभावित तालमेल का पता लगाएं', pronunciation: 'Chaliye sambhaavit taalmel ka pata lagaayein', category: 'Business' },
  { id: '611', english: 'We need to streamline the process', hindi: 'हमें प्रक्रिया को सुव्यवस्थित करने की आवश्यकता है', pronunciation: 'Hamein prakriya ko suvyavasthit karne ki aavashyakta hai', category: 'Business' },
  { id: '612', english: 'The overhead costs are too high', hindi: 'ओवरहेड लागत बहुत अधिक है', pronunciation: 'Overhead laagat bahut adhik hai', category: 'Business' },
  { id: '613', english: 'We should diversify our portfolio', hindi: 'हमें अपने पोर्टफोलियो में विविधता लानी चाहिए', pronunciation: 'Hamein apne portfolio mein vividhata laani chahiye', category: 'Business' },
  { id: '614', english: 'The profit margins are declining', hindi: 'लाभ मार्जिन घट रहे हैं', pronunciation: 'Laabh margin ghat rahe hain', category: 'Business' },
  { id: '615', english: 'We need to enhance customer engagement', hindi: 'हमें ग्राहक जुड़ाव बढ़ाने की आवश्यकता है', pronunciation: 'Hamein grahak judaav badhaane ki aavashyakta hai', category: 'Business' },
  { id: '616', english: 'The competitive landscape has changed', hindi: 'प्रतिस्पर्धी परिदृश्य बदल गया है', pronunciation: 'Pratisparddhi paridrishya badal gaya hai', category: 'Business' },
  { id: '617', english: 'Let\'s conduct a feasibility study', hindi: 'चलिए एक व्यवहार्यता अध्ययन करें', pronunciation: 'Chaliye ek vyavhaaryata adhyayan karein', category: 'Business' },
  { id: '618', english: 'The value proposition needs refinement', hindi: 'मूल्य प्रस्ताव को परिष्कृत करने की आवश्यकता है', pronunciation: 'Moolya prastav ko parishkrit karne ki aavashyakta hai', category: 'Business' },
  { id: '619', english: 'We should prioritize core competencies', hindi: 'हमें मुख्य दक्षताओं को प्राथमिकता देनी चाहिए', pronunciation: 'Hamein mukhya dakshataaon ko praathamikta deni chahiye', category: 'Business' },
  { id: '620', english: 'The market share is expanding', hindi: 'बाजार हिस्सेदारी बढ़ रही है', pronunciation: 'Baazaar hissedaari badh rahi hai', category: 'Business' },
  { id: '621', english: 'Let\'s implement agile methodologies', hindi: 'चलिए फुर्तीली पद्धतियों को लागू करें', pronunciation: 'Chaliye furteeli paddhatiyonko laagu karein', category: 'Business' },
  { id: '622', english: 'The cash flow needs monitoring', hindi: 'नकदी प्रवाह की निगरानी की आवश्यकता है', pronunciation: 'Nakdi pravaah ki nigarani ki aavashyakta hai', category: 'Business' },
  { id: '623', english: 'We need to establish KPIs', hindi: 'हमें KPI स्थापित करने की आवश्यकता है', pronunciation: 'Hamein KPI sthaapit karne ki aavashyakta hai', category: 'Business' },
  { id: '624', english: 'The business model requires innovation', hindi: 'व्यवसाय मॉडल को नवाचार की आवश्यकता है', pronunciation: 'Vyavasaay model ko navaachaar ki aavashyakta hai', category: 'Business' },
  { id: '625', english: 'Let\'s schedule a board meeting', hindi: 'चलिए एक बोर्ड मीटिंग शेड्यूल करें', pronunciation: 'Chaliye ek board meeting schedule karein', category: 'Business' },
  { id: '626', english: 'The brand equity is increasing', hindi: 'ब्रांड इक्विटी बढ़ रही है', pronunciation: 'Brand equity badh rahi hai', category: 'Business' },
  { id: '627', english: 'We should outsource non-core functions', hindi: 'हमें गैर-मुख्य कार्यों को आउटसोर्स करना चाहिए', pronunciation: 'Hamein gair-mukhya kaaryonko outsource karna chahiye', category: 'Business' },
  { id: '628', english: 'The inventory management needs improvement', hindi: 'इन्वेंटरी प्रबंधन में सुधार की आवश्यकता है', pronunciation: 'Inventory prabandhan mein sudhaar ki aavashyakta hai', category: 'Business' },
  { id: '629', english: 'Let\'s develop a go-to-market strategy', hindi: 'चलिए एक गो-टू-मार्केट रणनीति विकसित करें', pronunciation: 'Chaliye ek go-to-market ranneeti viksit karein', category: 'Business' },
  { id: '630', english: 'The supply chain needs optimization', hindi: 'आपूर्ति श्रृंखला को अनुकूलन की आवश्यकता है', pronunciation: 'Aapoorti shrinkhala ko anukolan ki aavashyakta hai', category: 'Business' },
  { id: '631', english: 'We need to build strategic partnerships', hindi: 'हमें रणनीतिक साझेदारी बनाने की आवश्यकता है', pronunciation: 'Hamein ranneetik saazhedaari banaane ki aavashyakta hai', category: 'Business' },
  { id: '632', english: 'The product lifecycle is shortening', hindi: 'उत्पाद जीवनचक्र छोटा हो रहा है', pronunciation: 'Utpaad jeevan chakra chhota ho raha hai', category: 'Business' },
  { id: '633', english: 'Let\'s conduct market research', hindi: 'चलिए बाजार अनुसंधान करें', pronunciation: 'Chaliye baazaar anusandhaan karein', category: 'Business' },
  { id: '634', english: 'The customer retention rate is high', hindi: 'ग्राहक प्रतिधारण दर उच्च है', pronunciation: 'Grahak pratidharan dar uchch hai', category: 'Business' },
  { id: '635', english: 'We should invest in R&D', hindi: 'हमें R&D में निवेश करना चाहिए', pronunciation: 'Hamein R&D mein nivesh karna chahiye', category: 'Business' },
  { id: '636', english: 'The operating expenses are escalating', hindi: 'परिचालन व्यय बढ़ रहे हैं', pronunciation: 'Parichaalan vyay badh rahe hain', category: 'Business' },
  { id: '637', english: 'Let\'s create a contingency plan', hindi: 'चलिए एक आकस्मिक योजना बनाएं', pronunciation: 'Chaliye ek aakasmik yojana banaayein', category: 'Business' },
  { id: '638', english: 'The organizational structure needs review', hindi: 'संगठनात्मक संरचना की समीक्षा की आवश्यकता है', pronunciation: 'Sangathanaa tmak sanrachna ki sameeksha ki aavashyakta hai', category: 'Business' },
  { id: '639', english: 'We need to improve employee morale', hindi: 'हमें कर्मचारी मनोबल में सुधार करने की आवश्यकता है', pronunciation: 'Hamein karmachaari manobal mein sudhaar karne ki aavashyakta hai', category: 'Business' },
  { id: '640', english: 'The merger negotiations are ongoing', hindi: 'विलय वार्ता जारी है', pronunciation: 'Vilay vaarta jaari hai', category: 'Business' },
  { id: '641', english: 'Let\'s implement quality assurance protocols', hindi: 'चलिए गुणवत्ता आश्वासन प्रोटोकॉल लागू करें', pronunciation: 'Chaliye gunavatta aashvaasan protocol laagu karein', category: 'Business' },
  { id: '642', english: 'The customer acquisition cost is rising', hindi: 'ग्राहक अधिग्रहण लागत बढ़ रही है', pronunciation: 'Grahak adhigrahan laagat badh rahi hai', category: 'Business' },
  { id: '643', english: 'We should focus on sustainable growth', hindi: 'हमें स्थायी विकास पर ध्यान देना चाहिए', pronunciation: 'Hamein sthaayi vikaas par dhyaan dena chahiye', category: 'Business' },
  { id: '644', english: 'The market penetration strategy is working', hindi: 'बाजार पैठ रणनीति काम कर रही है', pronunciation: 'Baazaar paith ranneeti kaam kar rahi hai', category: 'Business' },
  { id: '645', english: 'Let\'s review the performance metrics', hindi: 'चलिए प्रदर्शन मेट्रिक्स की समीक्षा करें', pronunciation: 'Chaliye pradarshan metrics ki sameeksha karein', category: 'Business' },
  { id: '646', english: 'The compliance requirements have changed', hindi: 'अनुपालन आवश्यकताएं बदल गई हैं', pronunciation: 'Anupalan aavashyaktaayein badal gayi hain', category: 'Business' },
  { id: '647', english: 'We need to address the skill gap', hindi: 'हमें कौशल अंतराल को संबोधित करने की आवश्यकता है', pronunciation: 'Hamein kaushal antaraal ko sambodhit karne ki aavashyakta hai', category: 'Business' },
  { id: '648', english: 'The product differentiation is crucial', hindi: 'उत्पाद विभेदन महत्वपूर्ण है', pronunciation: 'Utpaad vibhedan mahatvapoorn hai', category: 'Business' },
  { id: '649', english: 'Let\'s explore new market segments', hindi: 'चलिए नए बाजार खंडों का पता लगाएं', pronunciation: 'Chaliye naye baazaar khandon ka pata lagaayein', category: 'Business' },
  { id: '650', english: 'The succession planning is underway', hindi: 'उत्तराधिकार योजना चल रही है', pronunciation: 'Uttaraadhikaar yojana chal rahi hai', category: 'Business' },
  { id: '651', english: 'We should benchmark against competitors', hindi: 'हमें प्रतिस्पर्धियों के खिलाफ बेंचमार्क करना चाहिए', pronunciation: 'Hamein pratispardhiyon ke khilaaf benchmark karna chahiye', category: 'Business' },
  { id: '652', english: 'The organizational agility needs enhancement', hindi: 'संगठनात्मक चपलता में वृद्धि की आवश्यकता है', pronunciation: 'Sangathanaa tmak chapalata mein vriddhi ki aavashyakta hai', category: 'Business' },
  { id: '653', english: 'Let\'s conduct an internal audit', hindi: 'चलिए एक आंतरिक लेखा परीक्षा करें', pronunciation: 'Chaliye ek aantarik lekha pareeksha karein', category: 'Business' },
  { id: '654', english: 'The digital transformation is essential', hindi: 'डिजिटल परिवर्तन आवश्यक है', pronunciation: 'Digital parivartan aavashyak hai', category: 'Business' },
  { id: '655', english: 'We need to enhance our online presence', hindi: 'हमें अपनी ऑनलाइन उपस्थिति बढ़ाने की आवश्यकता है', pronunciation: 'Hamein apni online upasthiti badhaane ki aavashyakta hai', category: 'Business' },
  { id: '656', english: 'The sales funnel requires optimization', hindi: 'बिक्री फ़नल को अनुकूलन की आवश्यकता है', pronunciation: 'Bikri funnel ko anukolan ki aavashyakta hai', category: 'Business' },
  { id: '657', english: 'Let\'s implement a CRM system', hindi: 'चलिए एक CRM सिस्टम लागू करें', pronunciation: 'Chaliye ek CRM system laagu karein', category: 'Business' },
  { id: '658', english: 'The brand positioning needs clarity', hindi: 'ब्रांड पोजिशनिंग को स्पष्टता की आवश्यकता है', pronunciation: 'Brand positioning ko spashta ki aavashyakta hai', category: 'Business' },
  { id: '659', english: 'We should focus on core business activities', hindi: 'हमें मुख्य व्यावसायिक गतिविधियों पर ध्यान देना चाहिए', pronunciation: 'Hamein mukhya vyaavsaayik gatividhiyon par dhyaan dena chahiye', category: 'Business' },
  { id: '660', english: 'The pricing strategy needs revision', hindi: 'मूल्य निर्धारण रणनीति को संशोधन की आवश्यकता है', pronunciation: 'Moolya nirdhaaran ranneeti ko sanshodhan ki aavashyakta hai', category: 'Business' },
  { id: '661', english: 'Let\'s strengthen our vendor relationships', hindi: 'चलिए अपने विक्रेता संबंधों को मजबूत करें', pronunciation: 'Chaliye apne vikreta sambandhonko majboot karein', category: 'Business' },
  { id: '662', english: 'The profit forecast looks promising', hindi: 'लाभ पूर्वानुमान आशाजनक दिखता है', pronunciation: 'Laabh poorvaanumaan aashaajanak dikhta hai', category: 'Business' },
  { id: '663', english: 'We need to reduce operational bottlenecks', hindi: 'हमें परिचालन बाधाओं को कम करने की आवश्यकता है', pronunciation: 'Hamein parichaalan baadhaaon ko kam karne ki aavashyakta hai', category: 'Business' },
  { id: '664', english: 'The annual report will be published soon', hindi: 'वार्षिक रिपोर्ट जल्द ही प्रकाशित होगी', pronunciation: 'Vaarshik report jald hi prakaashit hogi', category: 'Business' },
  { id: '665', english: 'Let\'s develop employee retention strategies', hindi: 'चलिए कर्मचारी प्रतिधारण रणनीतियां विकसित करें', pronunciation: 'Chaliye karmachaari pratidharan ranneeti yaan viksit karein', category: 'Business' },
  { id: '666', english: 'The market volatility is concerning', hindi: 'बाजार की अस्थिरता चिंताजनक है', pronunciation: 'Baazaar ki asthirata chintaajanak hai', category: 'Business' },
  { id: '667', english: 'We should invest in employee training', hindi: 'हमें कर्मचारी प्रशिक्षण में निवेश करना चाहिए', pronunciation: 'Hamein karmachaari prashikshan mein nivesh karna chahiye', category: 'Business' },
  { id: '668', english: 'The expansion plans are on track', hindi: 'विस्तार योजनाएं ट्रैक पर हैं', pronunciation: 'Vistaar yojanaayein track par hain', category: 'Business' },
  { id: '669', english: 'Let\'s assess the competitive advantages', hindi: 'चलिए प्रतिस्पर्धात्मक लाभों का आकलन करें', pronunciation: 'Chaliye pratisparddhaatmak laabhonka aakalan karein', category: 'Business' },
  { id: '670', english: 'The restructuring will improve efficiency', hindi: 'पुनर्गठन दक्षता में सुधार करेगा', pronunciation: 'Punargathan dakshata mein sudhaar karega', category: 'Business' },
  { id: '671', english: 'We need to maintain regulatory compliance', hindi: 'हमें नियामक अनुपालन बनाए रखने की आवश्यकता है', pronunciation: 'Hamein niyaamak anupalan banaye rakhne ki aavashyakta hai', category: 'Business' },
  { id: '672', english: 'The business continuity plan is ready', hindi: 'व्यवसाय निरंतरता योजना तैयार है', pronunciation: 'Vyavasaay nirantarta yojana taiyaar hai', category: 'Business' },
  { id: '673', english: 'Let\'s enhance the customer experience', hindi: 'चलिए ग्राहक अनुभव को बढ़ाएं', pronunciation: 'Chaliye grahak anubhav ko badhaayein', category: 'Business' },
  { id: '674', english: 'The strategic initiative shows promise', hindi: 'रणनीतिक पहल आशाजनक दिखती है', pronunciation: 'Ranneetik pahal aashaajanak dikhti hai', category: 'Business' },
  { id: '675', english: 'We should capitalize on market opportunities', hindi: 'हमें बाजार के अवसरों का लाभ उठाना चाहिए', pronunciation: 'Hamein baazaar ke avasaron ka laabh uthaana chahiye', category: 'Business' },
  { id: '676', english: 'The leadership team is aligned', hindi: 'नेतृत्व टीम संरेखित है', pronunciation: 'Netritva team sanrekhit hai', category: 'Business' },
  { id: '677', english: 'Let\'s prioritize customer feedback', hindi: 'चलिए ग्राहक प्रतिक्रिया को प्राथमिकता दें', pronunciation: 'Chaliye grahak pratikriya ko praathamikta dein', category: 'Business' },
  { id: '678', english: 'The business ecosystem is evolving', hindi: 'व्यावसायिक पारिस्थितिकी तंत्र विकसित हो रहा है', pronunciation: 'Vyaavsaayik paaristhitiki tantra viksit ho raha hai', category: 'Business' },
  { id: '679', english: 'We need to mitigate potential risks', hindi: 'हमें संभावित जोखिमों को कम करने की आवश्यकता है', pronunciation: 'Hamein sambhaavit jokhimon ko kam karne ki aavashyakta hai', category: 'Business' },
  { id: '680', english: 'The strategic vision is clear', hindi: 'रणनीतिक दृष्टि स्पष्ट है', pronunciation: 'Ranneetik drishti spasht hai', category: 'Business' },
  { id: '681', english: 'Let\'s execute the action plan', hindi: 'चलिए कार्य योजना को निष्पादित करें', pronunciation: 'Chaliye kaarya yojana ko nishpaadit karein', category: 'Business' },
  { id: '682', english: 'The performance indicators are positive', hindi: 'प्रदर्शन संकेतक सकारात्मक हैं', pronunciation: 'Pradarshan sanketakसकारात्मक हैं', pronunciation: 'Pradarshan sanketak sakaraatmak hain', category: 'Business' },
  { id: '683', english: 'We should maintain transparency', hindi: 'हमें पारदर्शिता बनाए रखनी चाहिए', pronunciation: 'Hamein paaradarshita banaye rakhni chahiye', category: 'Business' },
  { id: '684', english: 'The growth trajectory is sustainable', hindi: 'विकास प्रक्षेपवक्र स्थायी है', pronunciation: 'Vikaas prakshepvakra sthaayi hai', category: 'Business' },
  { id: '685', english: 'Let\'s foster innovation culture', hindi: 'चलिए नवाचार संस्कृति को बढ़ावा दें', pronunciation: 'Chaliye navaachaar sanskriti ko badhaava dein', category: 'Business' },
  { id: '686', english: 'The market dynamics are changing', hindi: 'बाजार की गतिशीलता बदल रही है', pronunciation: 'Baazaar ki gatisheelta badal rahi hai', category: 'Business' },
  { id: '687', english: 'We need to establish clear milestones', hindi: 'हमें स्पष्ट मील के पत्थर स्थापित करने की आवश्यकता है', pronunciation: 'Hamein spasht mile ke patthar sthaapit karne ki aavashyakta hai', category: 'Business' },
  { id: '688', english: 'The competitive positioning is strong', hindi: 'प्रतिस्पर्धी स्थिति मजबूत है', pronunciation: 'Pratisparddhi sthiti majboot hai', category: 'Business' },
  { id: '689', english: 'Let\'s maximize shareholder value', hindi: 'चलिए शेयरधारक मूल्य को अधिकतम करें', pronunciation: 'Chaliye sheyardharak moolya ko adhiktam karein', category: 'Business' },
  { id: '690', english: 'The operational framework is robust', hindi: 'परिचालन ढांचा मजबूत है', pronunciation: 'Parichaalan dhaancha majboot hai', category: 'Business' },
  { id: '691', english: 'We should embrace digital innovation', hindi: 'हमें डिजिटल नवाचार को अपनाना चाहिए', pronunciation: 'Hamein digital navaachaar ko apnaana chahiye', category: 'Business' },
  { id: '692', english: 'The business model is scalable', hindi: 'व्यवसाय मॉडल स्केलेबल है', pronunciation: 'Vyavasaay model scalable hai', category: 'Business' },
  { id: '693', english: 'Let\'s ensure quality consistency', hindi: 'चलिए गुणवत्ता स्थिरता सुनिश्चित करें', pronunciation: 'Chaliye gunavatta sthirata sunishchit karein', category: 'Business' },
  { id: '694', english: 'The financial projections are accurate', hindi: 'वित्तीय अनुमान सटीक हैं', pronunciation: 'Vitteya anumaan sateek hain', category: 'Business' },
  { id: '695', english: 'We need to strengthen market position', hindi: 'हमें बाजार स्थिति को मजबूत करने की आवश्यकता है', pronunciation: 'Hamein baazaar sthiti ko majboot karne ki aavashyakta hai', category: 'Business' },
  { id: '696', english: 'The collaborative approach works well', hindi: 'सहयोगात्मक दृष्टिकोण अच्छी तरह काम करता है', pronunciation: 'Sahyogaatmak drishtikon achhi tarah kaam karta hai', category: 'Business' },
  { id: '697', english: 'Let\'s maintain competitive edge', hindi: 'चलिए प्रतिस्पर्धात्मक बढ़त बनाए रखें', pronunciation: 'Chaliye pratisparddhaatmak badhat banaye rakhein', category: 'Business' },
  { id: '698', english: 'The value chain needs optimization', hindi: 'मूल्य श्रृंखला को अनुकूलन की आवश्यकता है', pronunciation: 'Moolya shrinkhala ko anukolan ki aavashyakta hai', category: 'Business' },
  { id: '699', english: 'We should enhance operational excellence', hindi: 'हमें परिचालन उत्कृष्टता बढ़ानी चाहिए', pronunciation: 'Hamein parichaalan utkrishta badhaani chahiye', category: 'Business' },
  { id: '700', english: 'The business transformation is successful', hindi: 'व्यवसाय परिवर्तन सफल है', pronunciation: 'Vyavasaay parivartan saphal hai', category: 'Business' },

  // Extended Technology (100 lessons)
  { id: '701', english: 'Artificial intelligence is transforming industries', hindi: 'कृत्रिम बुद्धिमत्ता उद्योगों को बदल रही है', pronunciation: 'Kritrim buddhimatta udyogon ko badal rahi hai', category: 'Technology' },
  { id: '702', english: 'Machine learning algorithms improve accuracy', hindi: 'मशीन लर्निंग एल्गोरिदम सटीकता में सुधार करते हैं', pronunciation: 'Machine learning algorithm sateekta mein sudhaar karte hain', category: 'Technology' },
  { id: '703', english: 'Cloud computing offers scalability', hindi: 'क्लाउड कंप्यूटिंग स्केलेबिलिटी प्रदान करती है', pronunciation: 'Cloud computing scalability pradaan karti hai', category: 'Technology' },
  { id: '704', english: 'Cybersecurity threats are evolving', hindi: 'साइबर सुरक्षा खतरे विकसित हो रहे हैं', pronunciation: 'Cyber suraksha khatre viksit ho rahe hain', category: 'Technology' },
  { id: '705', english: 'Big data analytics drives insights', hindi: 'बिग डेटा एनालिटिक्स अंतर्दृष्टि को बढ़ावा देती है', pronunciation: 'Big data analytics antardrishti ko badhaava deti hai', category: 'Technology' },
  { id: '706', english: 'IoT devices are interconnected', hindi: 'IoT उपकरण आपस में जुड़े हुए हैं', pronunciation: 'IoT upkaran aapas mein jude hue hain', category: 'Technology' },
  { id: '707', english: 'Quantum computing shows potential', hindi: 'क्वांटम कंप्यूटिंग क्षमता दिखाती है', pronunciation: 'Quantum computing kshamata dikhaati hai', category: 'Technology' },
  { id: '708', english: 'API integration enables connectivity', hindi: 'API एकीकरण कनेक्टिविटी सक्षम करता है', pronunciation: 'API eekeekaran connectivity saksham karta hai', category: 'Technology' },
  { id: '709', english: 'Automation reduces manual work', hindi: 'स्वचालन मैनुअल कार्य को कम करता है', pronunciation: 'Swachalan manual kaarya ko kam karta hai', category: 'Technology' },
  { id: '710', english: 'DevOps improves deployment speed', hindi: 'DevOps परिनियोजन गति में सुधार करता है', pronunciation: 'DevOps pariniyojan gati mein sudhaar karta hai', category: 'Technology' },
  { id: '711', english: 'Microservices architecture is modular', hindi: 'माइक्रोसर्विसेज आर्किटेक्चर मॉड्यूलर है', pronunciation: 'Microservices architecture modular hai', category: 'Technology' },
  { id: '712', english: 'Containerization simplifies deployment', hindi: 'कंटेनराइजेशन परिनियोजन को सरल बनाता है', pronunciation: 'Containerization pariniyojan ko saral banaata hai', category: 'Technology' },
  { id: '713', english: 'Version control manages code changes', hindi: 'संस्करण नियंत्रण कोड परिवर्तनों को प्रबंधित करता है', pronunciation: 'Sanskaran niyantran code parivartanon ko prabandhit karta hai', category: 'Technology' },
  { id: '714', english: 'Database optimization enhances performance', hindi: 'डेटाबेस अनुकूलन प्रदर्शन को बढ़ाता है', pronunciation: 'Database anukolan pradarshan ko badhaata hai', category: 'Technology' },
  { id: '715', english: 'Network security prevents breaches', hindi: 'नेटवर्क सुरक्षा उल्लंघनों को रोकती है', pronunciation: 'Network suraksha ullanghanon ko rokti hai', category: 'Technology' },
  { id: '716', english: 'Responsive design adapts to devices', hindi: 'रेस्पॉन्सिव डिज़ाइन उपकरणों के अनुकूल होता है', pronunciation: 'Responsive design upkaranon ke anukool hota hai', category: 'Technology' },
  { id: '717', english: 'Serverless architecture reduces costs', hindi: 'सर्वररहित आर्किटेक्चर लागत कम करता है', pronunciation: 'Serverless architecture laagat kam karta hai', category: 'Technology' },
  { id: '718', english: 'Continuous integration improves quality', hindi: 'निरंतर एकीकरण गुणवत्ता में सुधार करता है', pronunciation: 'Nirantar eekeekaran gunavatta mein sudhaar karta hai', category: 'Technology' },
  { id: '719', english: 'Artificial intelligence transforms workflows', hindi: 'कृत्रिम बुद्धिमत्ता कार्यप्रवाह को बदल देती है', pronunciation: 'Kritrim buddhimatta kaaryapravah ko badal deti hai', category: 'Technology' },
  { id: '720', english: 'Data visualization helps decision making', hindi: 'डेटा विज़ुअलाइज़ेशन निर्णय लेने में मदद करता है', pronunciation: 'Data visualization nirnay lene mein madad karta hai', category: 'Technology' },
];

export default lessonsPart3;